
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: Dec  9 2025 03:22:34

// Verification Directory fv/BFP16_add 

module COMP_4bit(i_data_a, i_data_b, o_less, o_equal);
  input [3:0] i_data_a, i_data_b;
  output o_less, o_equal;
  wire [3:0] i_data_a, i_data_b;
  wire o_less, o_equal;
  wire n_3, n_4, n_6, n_7, n_9, n_10, n_11, n_16;
  wire n_17, n_21, n_24, n_29, n_30, n_34, n_36, n_38;
  wire n_43, n_44, n_48, n_50, n_52, n_53, n_55, n_60;
  wire n_65, n_69, n_74, n_75, n_76, n_77, n_78, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  not g1 (n_3, i_data_a[3]);
  and g11 (n_17, n_9, i_data_b[1]);
  and g14 (n_21, n_6, i_data_b[2]);
  and g16 (n_24, n_3, i_data_b[3]);
  not g2 (n_4, i_data_a[2]);
  and g23 (n_30, n_3, n_7);
  and g29 (n_36, n_30, i_data_b[2]);
  and g3 (n_6, n_3, n_4);
  and g30 (n_38, n_36, i_data_b[1]);
  and g37 (n_44, n_4, n_7);
  not g4 (n_7, i_data_a[1]);
  and g43 (n_50, n_44, i_data_b[3]);
  and g44 (n_52, n_50, i_data_b[1]);
  and g46 (n_53, n_4, i_data_b[3]);
  and g47 (n_55, n_53, i_data_b[2]);
  and g5 (n_9, n_6, n_7);
  not g6 (n_10, i_data_a[0]);
  and g7 (n_11, n_9, n_10);
  xor g70 (n_75, i_data_a[0], i_data_b[0]);
  xor g71 (n_76, i_data_a[1], i_data_b[1]);
  xor g72 (n_77, i_data_a[2], i_data_b[2]);
  xor g73 (n_78, i_data_a[3], i_data_b[3]);
  nor g74 (o_equal, n_78, n_77, n_76, n_75);
  or g75 (n_81, n_16, n_17, n_21, n_24);
  or g76 (n_82, n_29, n_34, n_38, n_43);
  or g77 (n_83, n_48, n_52, n_55, n_60);
  or g78 (n_84, n_65, n_69, n_74);
  or g79 (o_less, n_81, n_82, n_83, n_84);
  and g8 (n_16, n_11, i_data_b[0]);
  and g80 (n_29, n_6, n_10, i_data_b[1], i_data_b[0]);
  and g81 (n_34, n_30, n_10, i_data_b[2], i_data_b[0]);
  and g82 (n_85, n_3, n_10);
  and g83 (n_43, i_data_b[2], i_data_b[1], i_data_b[0], n_85);
  and g84 (n_48, n_44, n_10, i_data_b[3], i_data_b[0]);
  and g85 (n_86, n_4, n_10);
  and g86 (n_60, i_data_b[3], i_data_b[1], i_data_b[0], n_86);
  and g87 (n_87, n_7, n_10);
  and g88 (n_65, i_data_b[3], i_data_b[2], i_data_b[0], n_87);
  and g89 (n_69, n_7, i_data_b[3], i_data_b[2], i_data_b[1]);
  and g90 (n_88, n_10, i_data_b[3]);
  and g91 (n_74, i_data_b[2], i_data_b[1], i_data_b[0], n_88);
endmodule

module COMP_8bit_SIZE_DATA8(i_data_a, i_data_b, o_less);
  input [7:0] i_data_a, i_data_b;
  output o_less;
  wire [7:0] i_data_a, i_data_b;
  wire o_less;
  wire n_17, w_equal_high, w_equal_low, w_less_high, w_less_low;
  COMP_4bit u_high(.i_data_a (i_data_a[7:4]), .i_data_b
       (i_data_b[7:4]), .o_less (w_less_high), .o_equal (w_equal_high));
  COMP_4bit u_low(.i_data_a (i_data_a[3:0]), .i_data_b (i_data_b[3:0]),
       .o_less (w_less_low), .o_equal (w_equal_low));
  and g1 (n_17, w_equal_high, w_less_low);
  or g2 (o_less, w_less_high, n_17);
endmodule

module CLA_4bit(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire [3:0] w_g;
  wire [3:0] w_p;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_17;
  wire n_19, n_21, n_22, n_23, n_25, n_27, n_29, n_32;
  wire n_34, n_41, n_42, \w_c[1] , \w_c[2] , \w_c[3] ;
  and g1 (w_g[0], a[0], b[0]);
  and g10 (n_14, w_p[2], w_g[1]);
  and g12 (n_15, w_p[2], w_p[1]);
  and g13 (n_17, n_15, w_g[0]);
  and g16 (n_19, n_15, w_p[0]);
  and g17 (n_21, n_19, cin);
  xor g2 (w_p[1], a[1], b[1]);
  and g21 (n_22, w_p[3], w_g[2]);
  and g23 (n_23, w_p[3], w_p[2]);
  and g24 (n_25, n_23, w_g[1]);
  and g27 (n_27, n_23, w_p[1]);
  and g28 (n_29, n_27, w_g[0]);
  and g3 (n_9, w_p[0], cin);
  and g32 (n_32, n_27, w_p[0]);
  and g33 (n_34, n_32, cin);
  and g35 (w_g[1], a[1], b[1]);
  and g36 (w_g[2], a[2], b[2]);
  and g37 (w_g[3], a[3], b[3]);
  xor g38 (w_p[0], a[0], b[0]);
  xor g39 (w_p[2], a[2], b[2]);
  or g4 (\w_c[1] , w_g[0], n_9);
  xor g40 (w_p[3], a[3], b[3]);
  xor g41 (sum[0], w_p[0], cin);
  xor g42 (sum[1], w_p[1], \w_c[1] );
  xor g43 (sum[2], w_p[2], \w_c[2] );
  xor g44 (sum[3], w_p[3], \w_c[3] );
  nand g45 (n_41, w_p[3], w_p[2], w_p[1], w_p[0]);
  not g46 (o_p, n_41);
  or g47 (\w_c[3] , w_g[2], n_14, n_17, n_21);
  or g48 (n_42, w_g[3], n_22);
  or g49 (o_g, n_25, n_29, n_34, n_42);
  and g5 (n_10, w_p[1], w_g[0]);
  or g6 (n_12, w_g[1], n_10);
  and g7 (n_11, w_p[1], w_p[0]);
  and g8 (n_13, n_11, cin);
  or g9 (\w_c[2] , n_12, n_13);
endmodule

module CLA_8bit(i_carry, i_data_a, i_data_b, o_sum, o_carry);
  input i_carry;
  input [7:0] i_data_a, i_data_b;
  output [7:0] o_sum;
  output o_carry;
  wire i_carry;
  wire [7:0] i_data_a, i_data_b;
  wire [7:0] o_sum;
  wire o_carry;
  wire n_18, n_23, w_C, w_G, w_G_22, w_P, w_P_20;
  CLA_4bit CLA_4BIT_UNIT_0(.a (i_data_a[3:0]), .b (i_data_b[3:0]), .cin
       (i_carry), .sum (o_sum[3:0]), .o_p (w_P), .o_g (w_G));
  CLA_4bit CLA_4BIT_UNIT_1(.a (i_data_a[7:4]), .b (i_data_b[7:4]), .cin
       (w_C), .sum (o_sum[7:4]), .o_p (w_P_20), .o_g (w_G_22));
  and g1 (n_18, w_P, i_carry);
  or g2 (w_C, w_G, n_18);
  and g5 (n_23, w_P_20, w_C);
  or g6 (o_carry, w_G_22, n_23);
endmodule

module EXP_adjust_SIZE_EXP8_SIZE_LOPD8(i_overflow, i_underflow,
     i_zero_flag, i_lopd_value, i_exp_value, o_exp_result);
  input i_overflow, i_underflow, i_zero_flag;
  input [7:0] i_lopd_value, i_exp_value;
  output [7:0] o_exp_result;
  wire i_overflow, i_underflow, i_zero_flag;
  wire [7:0] i_lopd_value, i_exp_value;
  wire [7:0] o_exp_result;
  wire [7:0] w_data_b;
  wire [7:0] w_exp_result;
  wire UNCONNECTED, n_28, n_52, n_137, n_140, n_141, w_i_carry;
  CLA_8bit CLA_8BIT_UNIT(.i_carry (w_i_carry), .i_data_a (i_exp_value),
       .i_data_b (w_data_b), .o_sum (w_exp_result), .o_carry
       (UNCONNECTED));
  not g10 (n_28, i_lopd_value[0]);
  CDN_mux3 mux_21_19_g56(.sel0 (w_i_carry), .data0 (n_28), .sel1
       (n_137), .data1 (1'b0), .sel2 (i_overflow), .data2 (1'b1), .z
       (w_data_b[0]));
  not g79 (w_i_carry, n_52);
  not g87 (n_140, i_underflow);
  not g88 (n_141, i_overflow);
  nand g89 (n_52, n_141, n_140);
  nor g90 (n_137, w_i_carry, i_overflow);
  and g91 (o_exp_result[7], w_exp_result[7], wc);
  not gc (wc, i_zero_flag);
  and g92 (o_exp_result[6], w_exp_result[6], wc0);
  not gc0 (wc0, i_zero_flag);
  and g93 (o_exp_result[5], w_exp_result[5], wc1);
  not gc1 (wc1, i_zero_flag);
  and g94 (o_exp_result[4], w_exp_result[4], wc2);
  not gc2 (wc2, i_zero_flag);
  and g95 (o_exp_result[3], w_exp_result[3], wc3);
  not gc3 (wc3, i_zero_flag);
  and g96 (o_exp_result[2], w_exp_result[2], wc4);
  not gc4 (wc4, i_zero_flag);
  and g97 (o_exp_result[1], w_exp_result[1], wc5);
  not gc5 (wc5, i_zero_flag);
  and g98 (o_exp_result[0], w_exp_result[0], wc6);
  not gc6 (wc6, i_zero_flag);
  nor g99 (w_data_b[7], n_52, i_lopd_value[7]);
  nor g100 (w_data_b[6], n_52, i_lopd_value[6]);
  nor g101 (w_data_b[5], n_52, i_lopd_value[5]);
  nor g102 (w_data_b[4], n_52, i_lopd_value[4]);
  nor g103 (w_data_b[3], n_52, i_lopd_value[3]);
  nor g104 (w_data_b[2], n_52, i_lopd_value[2]);
  nor g105 (w_data_b[1], n_52, i_lopd_value[1]);
endmodule

module LOPD_8bit(i_data, o_pos_one, o_zero_flag);
  input [7:0] i_data;
  output [2:0] o_pos_one;
  output o_zero_flag;
  wire [7:0] i_data;
  wire [2:0] o_pos_one;
  wire o_zero_flag;
  wire [2:0] w_o_pos_one;
  wire n_10, n_13, n_15, n_20, n_21, n_25, n_28, n_31;
  wire n_33, n_37, n_38, n_41, n_44, n_46, n_48, n_52;
  wire n_53, n_58, n_63, n_74, n_75, n_76, n_77, n_105;
  wire n_106, n_107, n_108, n_109, n_110, n_111, n_112, n_113;
  wire n_114, n_115, n_116, n_117, n_118, n_119, n_120, n_121;
  wire n_122, n_123, n_124, n_125, n_126, n_127, n_128, n_129;
  wire n_130, n_131;
  nor g72 (n_10, i_data[7], i_data[5]);
  nor g76 (n_31, n_74, i_data[3]);
  nor g79 (n_46, n_74, i_data[5]);
  nor g83 (o_zero_flag, n_74, n_75, n_76, n_77);
  not g157 (n_105, i_data[5]);
  not g158 (n_106, i_data[7]);
  not g159 (n_107, i_data[3]);
  not g160 (n_108, i_data[6]);
  not g161 (n_109, i_data[4]);
  not g162 (n_110, i_data[2]);
  not g163 (n_111, i_data[0]);
  not g164 (n_112, i_data[1]);
  not g165 (n_113, n_10);
  nand g166 (n_74, n_106, n_108);
  not g167 (n_114, n_31);
  not g168 (n_115, n_46);
  nand g169 (n_75, n_105, n_109);
  nand g170 (n_76, n_107, n_110);
  nand g171 (n_77, n_112, n_111);
  nor g172 (n_28, i_data[7], n_108);
  not g173 (n_116, n_28);
  nor g174 (n_41, n_74, n_109);
  not g175 (n_117, n_41);
  nor g176 (n_44, n_74, n_105);
  not g177 (n_118, n_44);
  nor g178 (n_13, n_113, i_data[3]);
  not g179 (n_119, n_13);
  nor g180 (n_25, n_113, n_109);
  not g181 (n_120, n_25);
  nor g182 (n_48, n_115, i_data[4]);
  not g183 (n_121, n_48);
  nor g184 (n_33, n_114, i_data[2]);
  not g185 (n_122, n_33);
  nor g186 (n_15, n_119, i_data[1]);
  not g187 (n_123, n_15);
  nor g188 (n_21, n_119, n_110);
  not g189 (n_124, n_21);
  nor g190 (n_52, n_121, n_111);
  not g191 (n_125, n_52);
  nor g192 (n_53, n_121, n_112);
  not g193 (n_126, n_53);
  nor g194 (n_58, n_121, n_110);
  not g195 (n_127, n_58);
  nor g196 (n_63, n_121, n_107);
  not g197 (n_128, n_63);
  nor g198 (n_37, n_122, n_111);
  not g199 (n_129, n_37);
  nor g200 (n_38, n_122, n_112);
  not g201 (n_130, n_38);
  nor g202 (n_20, n_123, n_111);
  not g203 (n_131, n_20);
  nand g204 (w_o_pos_one[2], n_125, n_126, n_127, n_128);
  nand g205 (w_o_pos_one[1], n_117, n_118, n_129, n_130);
  nand g206 (w_o_pos_one[0], n_116, n_120, n_124, n_131);
  or g207 (o_pos_one[2], o_zero_flag, w_o_pos_one[2]);
  or g208 (o_pos_one[1], o_zero_flag, w_o_pos_one[1]);
  or g209 (o_pos_one[0], o_zero_flag, w_o_pos_one[0]);
endmodule

module MAN_ALU_SIZE_MAN8(i_sign_a, i_sign_b, i_carry, i_man_max,
     i_man_min, o_man_alu, o_overflow);
  input i_sign_a, i_sign_b, i_carry;
  input [7:0] i_man_max, i_man_min;
  output [7:0] o_man_alu;
  output o_overflow;
  wire i_sign_a, i_sign_b, i_carry;
  wire [7:0] i_man_max, i_man_min;
  wire [7:0] o_man_alu;
  wire o_overflow;
  wire [7:0] w_i_man_b;
  wire n_20, w_i_carry_alu, w_i_fpu_op, w_overflow;
  CLA_8bit ALU_SUB_UNIT(.i_carry (w_i_carry_alu), .i_data_a
       (i_man_max), .i_data_b (w_i_man_b), .o_sum (o_man_alu), .o_carry
       (w_overflow));
  xor g1 (n_20, i_sign_a, i_sign_b);
  not g2 (w_i_fpu_op, n_20);
  xor g13 (w_i_man_b[7], i_man_min[7], n_20);
  xor g14 (w_i_man_b[6], i_man_min[6], n_20);
  xor g15 (w_i_man_b[5], i_man_min[5], n_20);
  xor g16 (w_i_man_b[4], i_man_min[4], n_20);
  xor g17 (w_i_man_b[3], i_man_min[3], n_20);
  xor g18 (w_i_man_b[2], i_man_min[2], n_20);
  xor g19 (w_i_man_b[1], i_man_min[1], n_20);
  xor g20 (w_i_man_b[0], i_man_min[0], n_20);
  nor g25 (w_i_carry_alu, w_i_fpu_op, i_carry);
  and g26 (o_overflow, w_overflow, wc7);
  not gc7 (wc7, n_20);
endmodule

module SHF_left_SIZE_DATA8_SIZE_SHIFT3(i_shift_number, i_data, o_data);
  input [2:0] i_shift_number;
  input [7:0] i_data;
  output [7:0] o_data;
  wire [2:0] i_shift_number;
  wire [7:0] i_data;
  wire [7:0] o_data;
  wire [7:0] \stage[1] ;
  wire [7:0] \stage[2] ;
  wire n_6, n_13, n_17, n_19, n_23, n_89;
  CDN_bmux2 mux_20_33_g3(.sel0 (i_shift_number[0]), .data0 (i_data[5]),
       .data1 (i_data[4]), .z (\stage[1] [5]));
  CDN_bmux2 mux_20_33_g4(.sel0 (i_shift_number[0]), .data0 (i_data[4]),
       .data1 (i_data[3]), .z (\stage[1] [4]));
  CDN_bmux2 mux_20_33_g5(.sel0 (i_shift_number[0]), .data0 (i_data[3]),
       .data1 (i_data[2]), .z (\stage[1] [3]));
  CDN_bmux2 mux_20_33_g6(.sel0 (i_shift_number[0]), .data0 (i_data[2]),
       .data1 (i_data[1]), .z (\stage[1] [2]));
  CDN_bmux2 mux_20_33_g7(.sel0 (i_shift_number[0]), .data0 (i_data[1]),
       .data1 (i_data[0]), .z (\stage[1] [1]));
  CDN_bmux2 mux_20_4_g5(.sel0 (i_shift_number[1]), .data0 (\stage[1]
       [3]), .data1 (\stage[1] [1]), .z (\stage[2] [3]));
  CDN_bmux2 mux_20_4_g6(.sel0 (i_shift_number[1]), .data0 (\stage[1]
       [2]), .data1 (\stage[1] [0]), .z (\stage[2] [2]));
  CDN_bmux2 g1(.sel0 (i_shift_number[0]), .data0 (i_data[7]), .data1
       (i_data[6]), .z (n_6));
  CDN_bmux2 g2(.sel0 (i_shift_number[1]), .data0 (n_6), .data1
       (\stage[1] [5]), .z (n_89));
  CDN_bmux2 g3(.sel0 (i_shift_number[2]), .data0 (n_89), .data1
       (\stage[2] [3]), .z (o_data[7]));
  CDN_bmux2 g4(.sel0 (i_shift_number[1]), .data0 (\stage[1] [5]),
       .data1 (\stage[1] [3]), .z (n_13));
  CDN_bmux2 g5(.sel0 (i_shift_number[2]), .data0 (n_13), .data1
       (\stage[2] [1]), .z (o_data[5]));
  CDN_bmux2 g6(.sel0 (i_shift_number[0]), .data0 (i_data[6]), .data1
       (i_data[5]), .z (n_17));
  CDN_bmux2 g7(.sel0 (i_shift_number[1]), .data0 (n_17), .data1
       (\stage[1] [4]), .z (n_19));
  CDN_bmux2 g8(.sel0 (i_shift_number[2]), .data0 (n_19), .data1
       (\stage[2] [2]), .z (o_data[6]));
  CDN_bmux2 g9(.sel0 (i_shift_number[1]), .data0 (\stage[1] [4]),
       .data1 (\stage[1] [2]), .z (n_23));
  CDN_bmux2 g10(.sel0 (i_shift_number[2]), .data0 (n_23), .data1
       (\stage[2] [0]), .z (o_data[4]));
  and g85 (\stage[1] [0], i_data[0], wc8);
  not gc8 (wc8, i_shift_number[0]);
  and g86 (\stage[2] [1], \stage[1] [1], wc9);
  not gc9 (wc9, i_shift_number[1]);
  and g87 (\stage[2] [0], \stage[1] [0], wc10);
  not gc10 (wc10, i_shift_number[1]);
  and g88 (o_data[3], \stage[2] [3], wc11);
  not gc11 (wc11, i_shift_number[2]);
  and g89 (o_data[2], \stage[2] [2], wc12);
  not gc12 (wc12, i_shift_number[2]);
  and g90 (o_data[1], \stage[2] [1], wc13);
  not gc13 (wc13, i_shift_number[2]);
  and g91 (o_data[0], \stage[2] [0], wc14);
  not gc14 (wc14, i_shift_number[2]);
endmodule

module NOR_unit_SIZE_LOPD3_SIZE_DATA8(i_overflow, i_zero_flag,
     i_one_position, i_mantissa, o_mantissa);
  input i_overflow, i_zero_flag;
  input [2:0] i_one_position;
  input [7:0] i_mantissa;
  output [7:0] o_mantissa;
  wire i_overflow, i_zero_flag;
  wire [2:0] i_one_position;
  wire [7:0] i_mantissa;
  wire [7:0] o_mantissa;
  wire [7:0] w_shift_left;
  wire n_5, n_6, n_7, n_9, n_12, n_21, n_22, n_23;
  wire n_27, n_28, n_29, n_30, n_34, n_35, n_36, n_48;
  wire n_49, n_50, n_51, n_55, n_56, n_57, n_58, n_164;
  wire n_165, n_166, n_167, n_168, n_169, n_232, n_233, n_234;
  wire n_235;
  SHF_left_SIZE_DATA8_SIZE_SHIFT3 SHF_left_unit(.i_shift_number
       (i_one_position), .i_data (i_mantissa), .o_data (w_shift_left));
  CDN_bmux2 g1(.sel0 (i_mantissa[7]), .data0 (w_shift_left[6]), .data1
       (i_mantissa[6]), .z (n_5));
  CDN_bmux2 g2(.sel0 (i_overflow), .data0 (n_5), .data1
       (i_mantissa[7]), .z (n_6));
  not g3 (n_7, n_6);
  or g4 (n_9, n_7, i_zero_flag);
  not g5 (o_mantissa[6], n_9);
  not g6 (n_165, w_shift_left[7]);
  or g7 (n_12, i_mantissa[7], i_overflow);
  not g8 (n_164, n_12);
  and g9 (n_166, n_164, n_165);
  or g10 (n_167, n_166, i_zero_flag);
  not g11 (o_mantissa[7], n_167);
  CDN_bmux2 g12(.sel0 (i_mantissa[7]), .data0 (w_shift_left[5]), .data1
       (i_mantissa[5]), .z (n_168));
  CDN_bmux2 g13(.sel0 (i_overflow), .data0 (n_168), .data1
       (i_mantissa[6]), .z (n_21));
  not g14 (n_22, n_21);
  or g15 (n_23, n_22, i_zero_flag);
  not g16 (o_mantissa[5], n_23);
  CDN_bmux2 g17(.sel0 (i_mantissa[7]), .data0 (w_shift_left[4]), .data1
       (i_mantissa[4]), .z (n_27));
  CDN_bmux2 g18(.sel0 (i_overflow), .data0 (n_27), .data1
       (i_mantissa[5]), .z (n_28));
  not g19 (n_29, n_28);
  or g20 (n_30, n_29, i_zero_flag);
  not g21 (o_mantissa[4], n_30);
  CDN_bmux2 g22(.sel0 (i_mantissa[7]), .data0 (w_shift_left[3]), .data1
       (i_mantissa[3]), .z (n_34));
  CDN_bmux2 g23(.sel0 (i_overflow), .data0 (n_34), .data1
       (i_mantissa[4]), .z (n_35));
  not g24 (n_36, n_35);
  or g25 (n_169, n_36, i_zero_flag);
  not g26 (o_mantissa[3], n_169);
  CDN_bmux2 g27(.sel0 (i_mantissa[7]), .data0 (w_shift_left[2]), .data1
       (i_mantissa[2]), .z (n_232));
  CDN_bmux2 g28(.sel0 (i_overflow), .data0 (n_232), .data1
       (i_mantissa[3]), .z (n_233));
  not g29 (n_234, n_233);
  or g30 (n_235, n_234, i_zero_flag);
  not g31 (o_mantissa[2], n_235);
  CDN_bmux2 g32(.sel0 (i_mantissa[7]), .data0 (w_shift_left[1]), .data1
       (i_mantissa[1]), .z (n_48));
  CDN_bmux2 g33(.sel0 (i_overflow), .data0 (n_48), .data1
       (i_mantissa[2]), .z (n_49));
  not g34 (n_50, n_49);
  or g35 (n_51, n_50, i_zero_flag);
  not g36 (o_mantissa[1], n_51);
  CDN_bmux2 g37(.sel0 (i_mantissa[7]), .data0 (w_shift_left[0]), .data1
       (i_mantissa[0]), .z (n_55));
  CDN_bmux2 g38(.sel0 (i_overflow), .data0 (n_55), .data1
       (i_mantissa[1]), .z (n_56));
  not g39 (n_57, n_56);
  or g40 (n_58, n_57, i_zero_flag);
  not g41 (o_mantissa[0], n_58);
endmodule

module PSC_unit(i_sign_a, i_exp_a, i_man_a, i_sign_b, i_exp_b, i_man_b,
     o_sel_exp, o_sel_man);
  input i_sign_a, i_sign_b;
  input [7:0] i_exp_a, i_exp_b;
  input [23:0] i_man_a, i_man_b;
  output o_sel_exp;
  output [1:0] o_sel_man;
  wire i_sign_a, i_sign_b;
  wire [7:0] i_exp_a, i_exp_b;
  wire [23:0] i_man_a, i_man_b;
  wire o_sel_exp;
  wire [1:0] o_sel_man;
  wire n_63, n_64, n_65, n_66, n_73, n_78, n_82, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_96, n_97, n_98, n_99;
  wire n_100, n_101, n_102, n_103, w_E_one_A, w_E_one_B, w_M_zero_A,
       w_M_zero_B;
  assign o_sel_man[1] = o_sel_exp;
  nand g1 (n_83, i_exp_a[7], i_exp_a[6], i_exp_a[5], i_exp_a[4]);
  and g10 (n_66, w_E_one_A, n_64);
  nand g2 (n_84, i_exp_b[3], i_exp_b[2], i_exp_b[1], i_exp_b[0]);
  nand g22 (n_82, i_exp_a[3], i_exp_a[2], i_exp_a[1], i_exp_a[0]);
  nor g23 (w_E_one_A, n_82, n_83);
  nand g24 (n_85, i_exp_b[7], i_exp_b[6], i_exp_b[5], i_exp_b[4]);
  nor g25 (w_E_one_B, n_84, n_85);
  nor g26 (n_86, i_man_a[22], i_man_a[21], i_man_a[20], i_man_a[19]);
  nor g27 (n_87, i_man_a[18], i_man_a[17], i_man_a[16], i_man_a[15]);
  nor g28 (n_89, i_man_a[10], i_man_a[9], i_man_a[8], i_man_a[7]);
  nor g29 (n_90, i_man_a[6], i_man_a[5], i_man_a[4], i_man_a[3]);
  nor g3 (n_88, i_man_a[14], i_man_a[13], i_man_a[12], i_man_a[11]);
  nor g30 (n_91, i_man_a[2], i_man_a[1], i_man_a[0]);
  nand g31 (n_93, n_86, n_87, n_88, n_89);
  nand g32 (n_92, n_90, n_91);
  nor g33 (w_M_zero_A, n_92, n_93);
  nor g34 (n_94, i_man_b[22], i_man_b[21], i_man_b[20], i_man_b[19]);
  nor g35 (n_95, i_man_b[18], i_man_b[17], i_man_b[16], i_man_b[15]);
  nor g36 (n_96, i_man_b[14], i_man_b[13], i_man_b[12], i_man_b[11]);
  nor g37 (n_98, i_man_b[6], i_man_b[5], i_man_b[4], i_man_b[3]);
  nor g38 (n_99, i_man_b[2], i_man_b[1], i_man_b[0]);
  nand g39 (n_101, n_94, n_95, n_96, n_97);
  nor g4 (n_97, i_man_b[10], i_man_b[9], i_man_b[8], i_man_b[7]);
  nand g40 (n_100, n_98, n_99);
  nor g41 (w_M_zero_B, n_100, n_101);
  or g42 (o_sel_man[0], n_65, n_66, n_73, n_78);
  and g43 (n_73, n_102, w_E_one_A, i_sign_b, w_E_one_B);
  not g44 (n_102, i_sign_a);
  and g45 (n_78, n_103, i_sign_a, w_E_one_A, w_E_one_B);
  not g46 (n_103, i_sign_b);
  or g5 (o_sel_exp, w_E_one_A, w_E_one_B);
  not g7 (n_63, w_M_zero_B);
  and g8 (n_65, w_E_one_B, n_63);
  not g9 (n_64, w_M_zero_A);
endmodule

module SHF_right_SIZE_DATA16_SIZE_SHIFT4(i_shift_number, i_data,
     o_data);
  input [3:0] i_shift_number;
  input [15:0] i_data;
  output [15:0] o_data;
  wire [3:0] i_shift_number;
  wire [15:0] i_data;
  wire [15:0] o_data;
  wire [15:0] \stage[1] ;
  wire [15:0] \stage[2] ;
  wire n_2, n_4, n_7, n_9, n_14, n_15, n_20, n_21;
  wire n_22, n_27, n_28, n_29, n_30, n_32, n_33, n_34;
  wire n_37, n_39, n_40, n_41, n_42, n_43, n_45, n_46;
  wire n_50, n_52, n_53, n_54, n_55, n_57, n_58, n_59;
  wire n_203, n_204;
  assign o_data[0] = 1'b0;
  assign o_data[1] = 1'b0;
  assign o_data[2] = 1'b0;
  assign o_data[3] = 1'b0;
  assign o_data[4] = 1'b0;
  assign o_data[5] = 1'b0;
  assign o_data[6] = 1'b0;
  CDN_bmux2 mux_19_33_g2(.sel0 (i_shift_number[0]), .data0
       (i_data[14]), .data1 (i_data[15]), .z (\stage[1] [14]));
  CDN_bmux2 mux_19_33_g3(.sel0 (i_shift_number[0]), .data0
       (i_data[13]), .data1 (i_data[14]), .z (\stage[1] [13]));
  CDN_bmux2 mux_19_33_g4(.sel0 (i_shift_number[0]), .data0
       (i_data[12]), .data1 (i_data[13]), .z (\stage[1] [12]));
  CDN_bmux2 mux_19_33_g5(.sel0 (i_shift_number[0]), .data0
       (i_data[11]), .data1 (i_data[12]), .z (\stage[1] [11]));
  CDN_bmux2 mux_19_33_g6(.sel0 (i_shift_number[0]), .data0
       (i_data[10]), .data1 (i_data[11]), .z (\stage[1] [10]));
  CDN_bmux2 mux_19_33_g7(.sel0 (i_shift_number[0]), .data0 (i_data[9]),
       .data1 (i_data[10]), .z (\stage[1] [9]));
  CDN_bmux2 mux_19_33_g8(.sel0 (i_shift_number[0]), .data0 (i_data[8]),
       .data1 (i_data[9]), .z (\stage[1] [8]));
  CDN_bmux2 mux_19_5_g3(.sel0 (i_shift_number[1]), .data0
       (\stage[1] [13]), .data1 (\stage[1] [15]), .z (\stage[2] [13]));
  CDN_bmux2 mux_19_5_g4(.sel0 (i_shift_number[1]), .data0
       (\stage[1] [12]), .data1 (\stage[1] [14]), .z (\stage[2] [12]));
  CDN_bmux2 mux_19_5_g5(.sel0 (i_shift_number[1]), .data0
       (\stage[1] [11]), .data1 (\stage[1] [13]), .z (\stage[2] [11]));
  not g1 (n_2, i_data[15]);
  or g2 (n_4, n_2, i_shift_number[0]);
  not g3 (\stage[1] [15], n_4);
  or g4 (n_7, n_4, i_shift_number[1]);
  or g5 (n_9, n_7, i_shift_number[2]);
  CDN_bmux2 g7(.sel0 (i_shift_number[1]), .data0 (\stage[1] [9]),
       .data1 (\stage[1] [11]), .z (n_14));
  CDN_bmux2 g8(.sel0 (i_shift_number[2]), .data0 (n_14), .data1
       (\stage[2] [13]), .z (n_15));
  not g9 (n_203, n_15);
  or g10 (n_204, n_203, i_shift_number[3]);
  not g11 (o_data[9], n_204);
  not g12 (n_20, \stage[2] [13]);
  or g13 (n_21, n_20, i_shift_number[2]);
  or g14 (n_22, n_21, i_shift_number[3]);
  not g15 (o_data[13], n_22);
  CDN_bmux2 g16(.sel0 (i_shift_number[1]), .data0 (\stage[1] [8]),
       .data1 (\stage[1] [10]), .z (n_27));
  CDN_bmux2 g17(.sel0 (i_shift_number[2]), .data0 (n_27), .data1
       (\stage[2] [12]), .z (n_28));
  not g18 (n_29, n_28);
  or g19 (n_30, n_29, i_shift_number[3]);
  not g20 (o_data[8], n_30);
  not g21 (n_32, \stage[2] [12]);
  or g22 (n_33, n_32, i_shift_number[2]);
  or g23 (n_34, n_33, i_shift_number[3]);
  not g24 (o_data[12], n_34);
  CDN_bmux2 g25(.sel0 (i_shift_number[1]), .data0 (\stage[1] [10]),
       .data1 (\stage[1] [12]), .z (n_37));
  not g26 (n_41, n_37);
  not g27 (n_39, \stage[1] [14]);
  or g28 (n_40, i_shift_number[1], n_39);
  CDN_bmux2 g29(.sel0 (i_shift_number[2]), .data0 (n_41), .data1
       (n_40), .z (n_42));
  or g30 (n_43, n_42, i_shift_number[3]);
  not g31 (o_data[10], n_43);
  or g32 (n_45, n_40, i_shift_number[2]);
  or g33 (n_46, n_45, i_shift_number[3]);
  not g34 (o_data[14], n_46);
  CDN_bmux2 g35(.sel0 (i_shift_number[0]), .data0 (i_data[7]), .data1
       (i_data[8]), .z (n_50));
  CDN_bmux2 g36(.sel0 (i_shift_number[1]), .data0 (n_50), .data1
       (\stage[1] [9]), .z (n_52));
  CDN_bmux2 g37(.sel0 (i_shift_number[2]), .data0 (n_52), .data1
       (\stage[2] [11]), .z (n_53));
  not g38 (n_54, n_53);
  CDN_bmux2 g39(.sel0 (i_shift_number[3]), .data0 (n_54), .data1 (n_9),
       .z (n_55));
  not g40 (o_data[7], n_55);
  not g41 (n_57, \stage[2] [11]);
  CDN_bmux2 g42(.sel0 (i_shift_number[2]), .data0 (n_57), .data1 (n_7),
       .z (n_58));
  or g43 (n_59, n_58, i_shift_number[3]);
  not g44 (o_data[11], n_59);
  nor g228 (o_data[15], i_shift_number[3], n_9);
endmodule

module SIGN_unit(i_comp_man, i_sign_man_a, i_sign_man_b, o_sign_s);
  input i_comp_man, i_sign_man_a, i_sign_man_b;
  output o_sign_s;
  wire i_comp_man, i_sign_man_a, i_sign_man_b;
  wire o_sign_s;
  wire n_4, n_5, n_6;
  and g1 (n_5, i_sign_man_b, i_comp_man);
  not g2 (n_4, i_comp_man);
  and g3 (n_6, i_sign_man_a, n_4);
  or g4 (o_sign_s, n_5, n_6);
endmodule

module SWAP_unit_SIZE_DATA8(i_comp_less, i_data_a, i_data_b,
     o_data_max, o_data_min);
  input i_comp_less;
  input [7:0] i_data_a, i_data_b;
  output [7:0] o_data_max, o_data_min;
  wire i_comp_less;
  wire [7:0] i_data_a, i_data_b;
  wire [7:0] o_data_max, o_data_min;
  CDN_bmux2 mux_12_19_g1(.sel0 (i_comp_less), .data0 (i_data_a[7]),
       .data1 (i_data_b[7]), .z (o_data_max[7]));
  CDN_bmux2 mux_12_19_g2(.sel0 (i_comp_less), .data0 (i_data_a[6]),
       .data1 (i_data_b[6]), .z (o_data_max[6]));
  CDN_bmux2 mux_12_19_g3(.sel0 (i_comp_less), .data0 (i_data_a[5]),
       .data1 (i_data_b[5]), .z (o_data_max[5]));
  CDN_bmux2 mux_12_19_g4(.sel0 (i_comp_less), .data0 (i_data_a[4]),
       .data1 (i_data_b[4]), .z (o_data_max[4]));
  CDN_bmux2 mux_12_19_g5(.sel0 (i_comp_less), .data0 (i_data_a[3]),
       .data1 (i_data_b[3]), .z (o_data_max[3]));
  CDN_bmux2 mux_12_19_g6(.sel0 (i_comp_less), .data0 (i_data_a[2]),
       .data1 (i_data_b[2]), .z (o_data_max[2]));
  CDN_bmux2 mux_12_19_g7(.sel0 (i_comp_less), .data0 (i_data_a[1]),
       .data1 (i_data_b[1]), .z (o_data_max[1]));
  CDN_bmux2 mux_12_19_g8(.sel0 (i_comp_less), .data0 (i_data_a[0]),
       .data1 (i_data_b[0]), .z (o_data_max[0]));
  CDN_bmux2 mux_13_19_g1(.sel0 (i_comp_less), .data0 (i_data_b[7]),
       .data1 (i_data_a[7]), .z (o_data_min[7]));
  CDN_bmux2 mux_13_19_g2(.sel0 (i_comp_less), .data0 (i_data_b[6]),
       .data1 (i_data_a[6]), .z (o_data_min[6]));
  CDN_bmux2 mux_13_19_g3(.sel0 (i_comp_less), .data0 (i_data_b[5]),
       .data1 (i_data_a[5]), .z (o_data_min[5]));
  CDN_bmux2 mux_13_19_g4(.sel0 (i_comp_less), .data0 (i_data_b[4]),
       .data1 (i_data_a[4]), .z (o_data_min[4]));
  CDN_bmux2 mux_13_19_g5(.sel0 (i_comp_less), .data0 (i_data_b[3]),
       .data1 (i_data_a[3]), .z (o_data_min[3]));
  CDN_bmux2 mux_13_19_g6(.sel0 (i_comp_less), .data0 (i_data_b[2]),
       .data1 (i_data_a[2]), .z (o_data_min[2]));
  CDN_bmux2 mux_13_19_g7(.sel0 (i_comp_less), .data0 (i_data_b[1]),
       .data1 (i_data_a[1]), .z (o_data_min[1]));
  CDN_bmux2 mux_13_19_g8(.sel0 (i_comp_less), .data0 (i_data_b[0]),
       .data1 (i_data_a[0]), .z (o_data_min[0]));
endmodule

module BFP16_add(i_data_a, i_data_b, o_bfu_add);
  input [31:0] i_data_a, i_data_b;
  output [31:0] o_bfu_add;
  wire [31:0] i_data_a, i_data_b;
  wire [31:0] o_bfu_add;
  wire [7:0] w_swap_man0_max;
  wire [15:0] w_shf_right_man1_min;
  wire [7:0] w_alu_man_result;
  wire [2:0] w_lopd_one_pos;
  wire [7:0] w_swap_exp_max;
  wire [7:0] w_exp_adjust;
  wire [7:0] w_swap_man1_max;
  wire [7:0] w_swap_man1_min;
  wire [7:0] w_nor_man;
  wire [1:0] w_sel_man;
  wire [7:0] w_sub_exp_result;
  wire [7:0] w_swap_man0_min;
  wire [7:0] w_swap_exp_min;
  wire UNCONNECTED0, n_60, n_61, n_62, n_63, n_68, n_101, n_105;
  wire n_113, n_116, n_117, w_alu_man_overflow, w_comp_exp_less,
       w_comp_man_less, w_lopd_zero_flag, w_sel_exp;
  assign o_bfu_add[0] = 1'b0;
  assign o_bfu_add[1] = 1'b0;
  assign o_bfu_add[2] = 1'b0;
  assign o_bfu_add[3] = 1'b0;
  assign o_bfu_add[4] = 1'b0;
  assign o_bfu_add[5] = 1'b0;
  assign o_bfu_add[6] = 1'b0;
  assign o_bfu_add[7] = 1'b0;
  assign o_bfu_add[8] = 1'b0;
  assign o_bfu_add[9] = 1'b0;
  assign o_bfu_add[10] = 1'b0;
  assign o_bfu_add[11] = 1'b0;
  assign o_bfu_add[12] = 1'b0;
  assign o_bfu_add[13] = 1'b0;
  assign o_bfu_add[14] = 1'b0;
  assign o_bfu_add[15] = 1'b0;
  COMP_8bit_SIZE_DATA8 COMP_EXP_UNIT(.i_data_a (i_data_a[30:23]),
       .i_data_b (i_data_b[30:23]), .o_less (w_comp_exp_less));
  COMP_8bit_SIZE_DATA8 COMP_MAN_UNIT(.i_data_a (w_swap_man0_max),
       .i_data_b (w_shf_right_man1_min[15:8]), .o_less
       (w_comp_man_less));
  EXP_adjust_SIZE_EXP8_SIZE_LOPD8 EXP_ADJUSTION_UNIT(.i_overflow
       (w_alu_man_overflow), .i_underflow (w_alu_man_result[7]),
       .i_zero_flag (w_lopd_zero_flag), .i_lopd_value ({5'b00000,
       w_lopd_one_pos}), .i_exp_value (w_swap_exp_max), .o_exp_result
       (w_exp_adjust));
  LOPD_8bit LOPD_UNIT(.i_data (w_alu_man_result), .o_pos_one
       (w_lopd_one_pos), .o_zero_flag (w_lopd_zero_flag));
  MAN_ALU_SIZE_MAN8 MAN_ALU_UNIT(.i_sign_a (i_data_a[31]), .i_sign_b
       (i_data_b[31]), .i_carry (w_shf_right_man1_min[7]), .i_man_max
       (w_swap_man1_max), .i_man_min (w_swap_man1_min), .o_man_alu
       (w_alu_man_result), .o_overflow (w_alu_man_overflow));
  NOR_unit_SIZE_LOPD3_SIZE_DATA8 NOR_UNIT(.i_overflow
       (w_alu_man_overflow), .i_zero_flag (w_lopd_zero_flag),
       .i_one_position (w_lopd_one_pos), .i_mantissa
       (w_alu_man_result), .o_mantissa (w_nor_man));
  PSC_unit PSC_UNIT(.i_sign_a (i_data_a[31]), .i_exp_a
       (i_data_a[30:23]), .i_man_a ({1'b1, i_data_a[22:0]}), .i_sign_b
       (i_data_b[31]), .i_exp_b (i_data_b[30:23]), .i_man_b ({1'b1,
       i_data_b[22:0]}), .o_sel_exp (w_sel_exp), .o_sel_man
       (w_sel_man));
  SHF_right_SIZE_DATA16_SIZE_SHIFT4 SHF_RIGHT_MAN_UNIT(.i_shift_number
       (w_sub_exp_result[3:0]), .i_data ({w_swap_man0_min,
       8'b00000000}), .o_data (w_shf_right_man1_min));
  SIGN_unit SIGN_UNIT(.i_comp_man (n_68), .i_sign_man_a (i_data_a[31]),
       .i_sign_man_b (i_data_b[31]), .o_sign_s (o_bfu_add[31]));
  CLA_8bit SUB_EXP_UNIT(.i_carry (1'b1), .i_data_a (w_swap_exp_max),
       .i_data_b ({4'b0000, n_63, n_62, n_61, n_60}), .o_sum
       (w_sub_exp_result), .o_carry (UNCONNECTED0));
  SWAP_unit_SIZE_DATA8 SWAP_EXP_UNIT(.i_comp_less (w_comp_exp_less),
       .i_data_a (i_data_a[30:23]), .i_data_b (i_data_b[30:23]),
       .o_data_max (w_swap_exp_max), .o_data_min (w_swap_exp_min));
  SWAP_unit_SIZE_DATA8 SWAP_MAN0_UNIT(.i_comp_less (w_comp_exp_less),
       .i_data_a ({1'b1, i_data_a[22:16]}), .i_data_b ({1'b1,
       i_data_b[22:16]}), .o_data_max (w_swap_man0_max), .o_data_min
       (w_swap_man0_min));
  SWAP_unit_SIZE_DATA8 SWAP_MAN1_UNIT(.i_comp_less (w_comp_man_less),
       .i_data_a (w_swap_man0_max), .i_data_b
       (w_shf_right_man1_min[15:8]), .o_data_max (w_swap_man1_max),
       .o_data_min (w_swap_man1_min));
  not g5 (n_63, w_swap_exp_min[3]);
  not g7 (n_62, w_swap_exp_min[2]);
  not g8 (n_61, w_swap_exp_min[1]);
  not g9 (n_60, w_swap_exp_min[0]);
  CDN_mux3 mux_165_23_g14(.sel0 (n_101), .data0 (w_nor_man[6]), .sel1
       (n_105), .data1 (1'b0), .sel2 (n_113), .data2 (1'b1), .z
       (o_bfu_add[22]));
  not g11 (n_101, w_sel_man[1]);
  not g32 (n_116, w_comp_man_less);
  not g33 (n_117, w_comp_exp_less);
  nor g34 (n_105, n_101, w_sel_man[0]);
  nand g35 (n_68, n_117, n_116);
  nor g36 (n_113, n_101, n_105);
  or g37 (o_bfu_add[30], w_sel_exp, w_exp_adjust[7]);
  or g38 (o_bfu_add[29], w_sel_exp, w_exp_adjust[6]);
  or g39 (o_bfu_add[28], w_sel_exp, w_exp_adjust[5]);
  or g40 (o_bfu_add[27], w_sel_exp, w_exp_adjust[4]);
  or g41 (o_bfu_add[26], w_sel_exp, w_exp_adjust[3]);
  or g42 (o_bfu_add[25], w_sel_exp, w_exp_adjust[2]);
  or g43 (o_bfu_add[24], w_sel_exp, w_exp_adjust[1]);
  or g44 (o_bfu_add[23], w_sel_exp, w_exp_adjust[0]);
  and g45 (o_bfu_add[21], w_nor_man[5], wc15);
  not gc15 (wc15, w_sel_man[1]);
  and g46 (o_bfu_add[20], w_nor_man[4], wc16);
  not gc16 (wc16, w_sel_man[1]);
  and g47 (o_bfu_add[19], w_nor_man[3], wc17);
  not gc17 (wc17, w_sel_man[1]);
  and g48 (o_bfu_add[18], w_nor_man[2], wc18);
  not gc18 (wc18, w_sel_man[1]);
  and g49 (o_bfu_add[17], w_nor_man[1], wc19);
  not gc19 (wc19, w_sel_man[1]);
  and g50 (o_bfu_add[16], w_nor_man[0], wc20);
  not gc20 (wc20, w_sel_man[1]);
endmodule

`ifdef RC_CDN_GENERIC_GATE
`else
`ifdef ONE_HOT_MUX // captures one-hot property of select inputs
module CDN_mux3(sel0, data0, sel1, data1, sel2, data2, z);
  input sel0, data0, sel1, data1, sel2, data2;
  output z;
  wire sel0, data0, sel1, data1, sel2, data2;
  reg  z;
  always 
    @(sel0 or sel1 or sel2 or data0 or data1 or data2) 
      case ({sel0, sel1, sel2})
       3'b100: z = data0;
       3'b010: z = data1;
       3'b001: z = data2;
       default: z = 1'bX;
      endcase
endmodule
`else
module CDN_mux3(sel0, data0, sel1, data1, sel2, data2, z);
  input sel0, data0, sel1, data1, sel2, data2;
  output z;
  wire sel0, data0, sel1, data1, sel2, data2;
  wire z;
  wire w_0, w_1, w_2;
  and a_0 (w_0, sel0, data0);
  and a_1 (w_1, sel1, data1);
  and a_2 (w_2, sel2, data2);
  or org (z, w_0, w_1, w_2);
endmodule
`endif // ONE_HOT_MUX
`endif
`ifdef RC_CDN_GENERIC_GATE
`else
`ifdef ONE_HOT_MUX
module CDN_bmux2(sel0, data0, data1, z);
  input sel0, data0, data1;
  output z;
  wire sel0, data0, data1;
  reg  z;
  always 
    @(sel0 or data0 or data1) 
      case ({sel0})
       1'b0: z = data0;
       1'b1: z = data1;
      endcase
endmodule
`else
module CDN_bmux2(sel0, data0, data1, z);
  input sel0, data0, data1;
  output z;
  wire sel0, data0, data1;
  wire z;
  wire inv_sel0, w_0, w_1;
  not i_0 (inv_sel0, sel0);
  and a_0 (w_0, inv_sel0, data0);
  and a_1 (w_1, sel0, data1);
  or org (z, w_0, w_1);
endmodule
`endif // ONE_HOT_MUX
`endif
