
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: Dec  9 2025 03:22:37

// Verification Directory fv/BFP16_add 

module COMP_4bit_1(i_data_a, i_data_b, o_less, o_equal);
  input [3:0] i_data_a, i_data_b;
  output o_less, o_equal;
  wire [3:0] i_data_a, i_data_b;
  wire o_less, o_equal;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_18, n_19;
  OAI21X1HVT g334(.A0 (n_14), .A1 (n_19), .B0 (n_18), .Y (o_less));
  AOI21X1HVT g335(.A0 (n_11), .A1 (n_12), .B0 (n_9), .Y (n_19));
  AOI21X1HVT g336(.A0 (n_13), .A1 (n_10), .B0 (n_8), .Y (n_18));
  NOR2X1HVT g337(.A (n_15), .B (n_16), .Y (o_equal));
  NAND2X1HVT g338(.A (n_1), .B (n_0), .Y (n_16));
  NAND2X1HVT g339(.A (n_3), .B (n_2), .Y (n_15));
  OAI2BB1X1HVT g340(.A0N (i_data_a[2]), .A1N (n_5), .B0 (n_10), .Y
       (n_14));
  NOR2X1HVT g345(.A (i_data_a[2]), .B (n_5), .Y (n_13));
  NAND2X1HVT g346(.A (i_data_a[1]), .B (n_6), .Y (n_12));
  NOR2X1HVT g347(.A (i_data_a[0]), .B (n_7), .Y (n_11));
  NOR2X1HVT g348(.A (i_data_a[1]), .B (n_6), .Y (n_9));
  NOR2X1HVT g349(.A (i_data_a[3]), .B (n_4), .Y (n_8));
  NAND2X1HVT g350(.A (i_data_a[3]), .B (n_4), .Y (n_10));
  INVX1HVT g351(.A (i_data_b[0]), .Y (n_7));
  INVX1HVT g352(.A (i_data_b[1]), .Y (n_6));
  INVX1HVT g353(.A (i_data_b[2]), .Y (n_5));
  INVX1HVT g354(.A (i_data_b[3]), .Y (n_4));
  MXI2XLHVT g2(.A (i_data_b[0]), .B (n_7), .S0 (i_data_a[0]), .Y (n_3));
  MXI2XLHVT g359(.A (i_data_b[2]), .B (n_5), .S0 (i_data_a[2]), .Y
       (n_2));
  MXI2XLHVT g360(.A (i_data_b[1]), .B (n_6), .S0 (i_data_a[1]), .Y
       (n_1));
  MXI2XLHVT g361(.A (i_data_b[3]), .B (n_4), .S0 (i_data_a[3]), .Y
       (n_0));
endmodule

module COMP_4bit(i_data_a, i_data_b, o_less, o_equal);
  input [3:0] i_data_a, i_data_b;
  output o_less, o_equal;
  wire [3:0] i_data_a, i_data_b;
  wire o_less, o_equal;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10;
  assign o_equal = 1'b0;
  OAI21X1HVT g1203(.A0 (n_3), .A1 (n_10), .B0 (n_6), .Y (o_less));
  NOR3X1HVT g1204(.A (n_7), .B (n_8), .C (n_9), .Y (n_10));
  NOR3X1HVT g1205(.A (n_5), .B (n_0), .C (n_1), .Y (n_9));
  NOR2X1HVT g1206(.A (n_0), .B (n_4), .Y (n_8));
  NOR2BX1HVT g1207(.AN (i_data_b[2]), .B (i_data_a[2]), .Y (n_7));
  NAND2BX1HVT g1209(.AN (i_data_a[3]), .B (i_data_b[3]), .Y (n_6));
  NOR2X1HVT g1210(.A (i_data_b[1]), .B (n_2), .Y (n_5));
  NAND2X1HVT g1211(.A (i_data_b[1]), .B (n_2), .Y (n_4));
  NOR2BX1HVT g1212(.AN (i_data_a[3]), .B (i_data_b[3]), .Y (n_3));
  INVX1HVT g1215(.A (i_data_a[1]), .Y (n_2));
  NAND2BX1HVT g2(.AN (i_data_a[0]), .B (i_data_b[0]), .Y (n_1));
  NOR2BX1HVT g1217(.AN (i_data_a[2]), .B (i_data_b[2]), .Y (n_0));
endmodule

module COMP_8bit_SIZE_DATA8(i_data_a, i_data_b, o_less);
  input [7:0] i_data_a, i_data_b;
  output o_less;
  wire [7:0] i_data_a, i_data_b;
  wire o_less;
  wire n_0, n_1, n_2, w_equal_high, w_equal_low, w_less_high,
       w_less_low;
  COMP_4bit_1 u_high(.i_data_a (i_data_a[7:4]), .i_data_b
       (i_data_b[7:4]), .o_less (w_less_high), .o_equal (w_equal_high));
  COMP_4bit u_low(.i_data_a (i_data_a[3:0]), .i_data_b (i_data_b[3:0]),
       .o_less (w_less_low), .o_equal (w_equal_low));
  CLKINVX6HVT g19(.A (n_2), .Y (o_less));
  AOI21X4HVT g20(.A0 (n_1), .A1 (w_less_low), .B0 (n_0), .Y (n_2));
  BUFX2HVT drc_bufs(.A (w_equal_high), .Y (n_1));
  BUFX3HVT drc_bufs21(.A (w_less_high), .Y (n_0));
endmodule

module COMP_4bit_3(i_data_a, i_data_b, o_less, o_equal);
  input [3:0] i_data_a, i_data_b;
  output o_less, o_equal;
  wire [3:0] i_data_a, i_data_b;
  wire o_less, o_equal;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_13;
  NAND2XLHVT g308(.A (n_8), .B (n_0), .Y (o_less));
  AOI21X1HVT g310(.A0 (i_data_a[1]), .A1 (n_3), .B0 (n_9), .Y (n_13));
  NOR2X1HVT g311(.A (n_11), .B (n_10), .Y (o_equal));
  NAND2X1HVT g312(.A (i_data_b[3]), .B (n_7), .Y (n_11));
  NAND2X1HVT g313(.A (n_6), .B (n_5), .Y (n_10));
  AOI21X1HVT g314(.A0 (n_4), .A1 (i_data_b[0]), .B0 (i_data_b[1]), .Y
       (n_9));
  NAND3X1HVT g315(.A (n_2), .B (i_data_b[3]), .C (i_data_b[2]), .Y
       (n_8));
  XNOR2X1HVT g316(.A (i_data_a[0]), .B (i_data_b[0]), .Y (n_7));
  MXI2XLHVT g317(.A (i_data_a[2]), .B (n_2), .S0 (i_data_b[2]), .Y
       (n_6));
  XNOR2X1HVT g318(.A (i_data_a[1]), .B (i_data_b[1]), .Y (n_5));
  NOR2X1HVT g319(.A (i_data_a[1]), .B (i_data_a[0]), .Y (n_4));
  NAND2BXLHVT g320(.AN (i_data_a[0]), .B (i_data_b[0]), .Y (n_3));
  INVX1HVT g321(.A (i_data_a[2]), .Y (n_2));
  NAND3X1HVT g2(.A (n_1), .B (i_data_b[3]), .C (n_13), .Y (n_0));
  OR2X1HVT g3(.A (n_2), .B (i_data_b[2]), .Y (n_1));
endmodule

module COMP_4bit_2(i_data_a, i_data_b, o_less, o_equal);
  input [3:0] i_data_a, i_data_b;
  output o_less, o_equal;
  wire [3:0] i_data_a, i_data_b;
  wire o_less, o_equal;
  wire n_0, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10;
  assign o_equal = 1'b0;
  AOI22X1HVT g248(.A0 (n_9), .A1 (n_7), .B0 (n_4), .B1 (i_data_b[2]),
       .Y (n_10));
  OAI32X2HVT g249(.A0 (n_0), .A1 (n_5), .A2 (n_8), .B0 (i_data_a[1]),
       .B1 (n_3), .Y (n_9));
  NOR2BX1HVT g250(.AN (i_data_a[1]), .B (i_data_b[1]), .Y (n_8));
  OR2XLHVT g251(.A (n_4), .B (i_data_b[2]), .Y (n_7));
  NOR2BX1HVT g252(.AN (i_data_a[3]), .B (i_data_b[3]), .Y (n_6));
  INVX1HVT g253(.A (i_data_b[0]), .Y (n_5));
  INVX1HVT g254(.A (i_data_a[2]), .Y (n_4));
  INVX1HVT g256(.A (i_data_b[1]), .Y (n_3));
  OAI21X1HVT g2(.A0 (n_6), .A1 (n_10), .B0 (n_2), .Y (o_less));
  NAND2BXLHVT g3(.AN (i_data_a[3]), .B (i_data_b[3]), .Y (n_2));
  BUFX2HVT drc_bufs(.A (i_data_a[0]), .Y (n_0));
endmodule

module COMP_8bit_SIZE_DATA8_1(i_data_a, i_data_b, o_less);
  input [7:0] i_data_a, i_data_b;
  output o_less;
  wire [7:0] i_data_a, i_data_b;
  wire o_less;
  wire w_equal_high, w_equal_low, w_less_high, w_less_low;
  COMP_4bit_3 u_high(.i_data_a ({1'b1, i_data_a[6:4]}), .i_data_b
       (i_data_b[7:4]), .o_less (w_less_high), .o_equal (w_equal_high));
  COMP_4bit_2 u_low(.i_data_a (i_data_a[3:0]), .i_data_b
       (i_data_b[3:0]), .o_less (w_less_low), .o_equal (w_equal_low));
  AO21X1HVT g16(.A0 (w_equal_high), .A1 (w_less_low), .B0
       (w_less_high), .Y (o_less));
endmodule

module CLA_4bit_2(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_14, n_15, n_16, n_17;
  wire n_20, n_22;
  XNOR2X1HVT g285(.A (n_10), .B (n_22), .Y (sum[3]));
  OAI21X1HVT g286(.A0 (n_7), .A1 (n_20), .B0 (n_4), .Y (n_22));
  XOR2XLHVT g287(.A (n_7), .B (n_20), .Y (sum[2]));
  AOI21X1HVT g288(.A0 (n_11), .A1 (n_16), .B0 (n_5), .Y (n_20));
  OAI22X1HVT g289(.A0 (n_3), .A1 (n_15), .B0 (n_10), .B1 (n_17), .Y
       (o_g));
  XOR2XLHVT g290(.A (n_11), .B (n_16), .Y (sum[1]));
  OA21X1HVT g291(.A0 (n_7), .A1 (n_14), .B0 (n_4), .Y (n_17));
  OAI21XLHVT g292(.A0 (n_3), .A1 (n_2), .B0 (n_6), .Y (n_16));
  NOR2X1HVT g293(.A (a[3]), .B (o_p), .Y (n_15));
  NOR2X1HVT g294(.A (n_5), .B (n_12), .Y (n_14));
  MX2XLHVT g295(.A (n_3), .B (cin), .S0 (n_2), .Y (sum[0]));
  NOR2X1HVT g297(.A (n_6), .B (n_9), .Y (n_12));
  INVX1HVT g298(.A (n_9), .Y (n_11));
  XNOR2X1HVT g299(.A (a[3]), .B (cin), .Y (n_10));
  XNOR2X1HVT g300(.A (a[1]), .B (b[1]), .Y (n_9));
  XNOR2X1HVT g301(.A (a[0]), .B (b[0]), .Y (n_8));
  XNOR2X1HVT g302(.A (a[2]), .B (b[2]), .Y (n_7));
  NAND2XLHVT g303(.A (a[0]), .B (b[0]), .Y (n_6));
  AND2XLHVT g304(.A (a[1]), .B (b[1]), .Y (n_5));
  NAND2X1HVT g305(.A (a[2]), .B (b[2]), .Y (n_4));
  INVX1HVT g306(.A (cin), .Y (n_3));
  BUFX2HVT fopt(.A (n_8), .Y (n_2));
  NOR3X2HVT g2(.A (n_1), .B (n_9), .C (n_8), .Y (o_p));
  OR2X6HVT g3(.A (n_10), .B (n_7), .Y (n_1));
endmodule

module CLA_4bit_3(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_0, n_1, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_12, n_13;
  assign o_g = 1'b0;
  assign o_p = 1'b0;
  XNOR2X1HVT g288(.A (n_6), .B (n_0), .Y (sum[3]));
  XNOR2X1HVT g289(.A (n_4), .B (n_13), .Y (sum[2]));
  XNOR2X1HVT g290(.A (n_3), .B (n_12), .Y (sum[1]));
  OAI21X1HVT g291(.A0 (n_3), .A1 (n_10), .B0 (n_7), .Y (n_13));
  OAI2BB1X1HVT g293(.A0N (a[0]), .A1N (b[0]), .B0 (n_10), .Y (n_12));
  XNOR2X1HVT g294(.A (cin), .B (n_5), .Y (sum[0]));
  NAND2BX1HVT g295(.AN (n_5), .B (cin), .Y (n_10));
  AOI21X1HVT g296(.A0 (a[2]), .A1 (b[0]), .B0 (n_8), .Y (n_9));
  INVX1HVT g297(.A (n_7), .Y (n_8));
  OAI21X1HVT g298(.A0 (a[0]), .A1 (a[1]), .B0 (b[0]), .Y (n_7));
  XNOR2X1HVT g299(.A (a[3]), .B (b[0]), .Y (n_6));
  XNOR2X1HVT g300(.A (a[0]), .B (b[0]), .Y (n_5));
  XNOR2X1HVT g301(.A (a[2]), .B (b[0]), .Y (n_4));
  XNOR2X1HVT g302(.A (a[1]), .B (b[0]), .Y (n_3));
  OAI21X1HVT g5(.A0 (n_1), .A1 (n_10), .B0 (n_9), .Y (n_0));
  OR2X1HVT g6(.A (n_4), .B (n_3), .Y (n_1));
endmodule

module CLA_8bit_1(i_carry, i_data_a, i_data_b, o_sum, o_carry);
  input i_carry;
  input [7:0] i_data_a, i_data_b;
  output [7:0] o_sum;
  output o_carry;
  wire i_carry;
  wire [7:0] i_data_a, i_data_b;
  wire [7:0] o_sum;
  wire o_carry;
  wire w_C, w_G, w_G_22, w_P, w_P_20;
  assign o_carry = 1'b0;
  CLA_4bit_2 CLA_4BIT_UNIT_0(.a (i_data_a[3:0]), .b ({1'b0,
       i_data_b[2:0]}), .cin (i_data_b[3]), .sum (o_sum[3:0]), .o_p
       (w_P), .o_g (w_G));
  CLA_4bit_3 CLA_4BIT_UNIT_1(.a (i_data_a[7:4]), .b ({3'b000,
       i_data_b[3]}), .cin (w_C), .sum (o_sum[7:4]), .o_p (w_P_20),
       .o_g (w_G_22));
  AO21XLHVT g20(.A0 (i_data_b[3]), .A1 (w_P), .B0 (w_G), .Y (w_C));
endmodule

module EXP_adjust_SIZE_EXP8_SIZE_LOPD8(i_overflow, i_underflow,
     i_zero_flag, i_lopd_value, i_exp_value, o_exp_result);
  input i_overflow, i_underflow, i_zero_flag;
  input [7:0] i_lopd_value, i_exp_value;
  output [7:0] o_exp_result;
  wire i_overflow, i_underflow, i_zero_flag;
  wire [7:0] i_lopd_value, i_exp_value;
  wire [7:0] o_exp_result;
  wire [7:0] w_data_b;
  wire [7:0] w_exp_result;
  wire UNCONNECTED, n_0, w_i_carry;
  CLA_8bit_1 CLA_8BIT_UNIT(.i_carry (1'b0), .i_data_a (i_exp_value),
       .i_data_b ({4'b0000, w_i_carry, w_data_b[2:0]}), .o_sum
       (w_exp_result), .o_carry (UNCONNECTED));
  NOR2BX1HVT g143(.AN (w_i_carry), .B (i_lopd_value[2]), .Y
       (w_data_b[2]));
  NOR2BX1HVT g144(.AN (w_i_carry), .B (i_lopd_value[1]), .Y
       (w_data_b[1]));
  OAI21X1HVT g145(.A0 (i_underflow), .A1 (i_lopd_value[0]), .B0 (n_0),
       .Y (w_data_b[0]));
  NOR2X1HVT g146(.A (i_overflow), .B (i_underflow), .Y (w_i_carry));
  INVX1HVT g147(.A (i_overflow), .Y (n_0));
  NOR2BX1HVT g154(.AN (w_exp_result[4]), .B (i_zero_flag), .Y
       (o_exp_result[4]));
  NOR2BX1HVT g155(.AN (w_exp_result[6]), .B (i_zero_flag), .Y
       (o_exp_result[6]));
  NOR2BX1HVT g156(.AN (w_exp_result[7]), .B (i_zero_flag), .Y
       (o_exp_result[7]));
  NOR2BX1HVT g157(.AN (w_exp_result[0]), .B (i_zero_flag), .Y
       (o_exp_result[0]));
  NOR2BX1HVT g158(.AN (w_exp_result[2]), .B (i_zero_flag), .Y
       (o_exp_result[2]));
  NOR2BX1HVT g159(.AN (w_exp_result[5]), .B (i_zero_flag), .Y
       (o_exp_result[5]));
  NOR2BX1HVT g160(.AN (w_exp_result[3]), .B (i_zero_flag), .Y
       (o_exp_result[3]));
  NOR2BX1HVT g161(.AN (w_exp_result[1]), .B (i_zero_flag), .Y
       (o_exp_result[1]));
endmodule

module LOPD_8bit(i_data, o_pos_one, o_zero_flag);
  input [7:0] i_data;
  output [2:0] o_pos_one;
  output o_zero_flag;
  wire [7:0] i_data;
  wire [2:0] o_pos_one;
  wire o_zero_flag;
  wire n_1, n_2, n_3, n_4, n_5, n_7, n_9;
  AOI2BB1XLHVT g406(.A0N (n_9), .A1N (i_data[6]), .B0 (i_data[7]), .Y
       (o_pos_one[0]));
  NOR2X1HVT g407(.A (n_7), .B (i_data[5]), .Y (n_9));
  AND2X1HVT g408(.A (o_pos_one[2]), .B (n_4), .Y (o_zero_flag));
  NOR2X1HVT g409(.A (n_5), .B (i_data[4]), .Y (n_7));
  AOI211X2HVT g410(.A0 (n_2), .A1 (n_3), .B0 (i_data[6]), .C0
       (i_data[7]), .Y (o_pos_one[1]));
  NOR2X1HVT g412(.A (n_1), .B (i_data[3]), .Y (n_5));
  NOR3X1HVT g413(.A (i_data[0]), .B (i_data[1]), .C (n_2), .Y (n_4));
  NOR2X1HVT g415(.A (i_data[4]), .B (i_data[5]), .Y (n_3));
  NOR2BX1HVT g416(.AN (i_data[1]), .B (i_data[2]), .Y (n_1));
  OR2X1HVT g417(.A (i_data[2]), .B (i_data[3]), .Y (n_2));
  NOR3BX1HVT g2(.AN (n_3), .B (i_data[6]), .C (i_data[7]), .Y
       (o_pos_one[2]));
endmodule

module CLA_4bit(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_14, n_15, n_16, n_17;
  wire n_20, n_22;
  XNOR2X1HVT g308(.A (n_3), .B (n_22), .Y (sum[3]));
  AOI21XLHVT g309(.A0 (n_9), .A1 (n_20), .B0 (n_8), .Y (n_22));
  CLKXOR2X1HVT g310(.A (n_9), .B (n_20), .Y (sum[2]));
  OAI21X1HVT g311(.A0 (n_7), .A1 (n_17), .B0 (n_2), .Y (n_20));
  OAI2BB1XLHVT g312(.A0N (n_3), .A1N (n_16), .B0 (n_0), .Y (o_g));
  CLKXOR2X1HVT g313(.A (n_7), .B (n_17), .Y (sum[1]));
  AOI21XLHVT g314(.A0 (cin), .A1 (n_6), .B0 (n_5), .Y (n_17));
  NAND2BX1HVT g315(.AN (n_8), .B (n_15), .Y (n_16));
  NAND2X1HVT g317(.A (n_9), .B (n_14), .Y (n_15));
  OAI2BB1X1HVT g318(.A0N (n_5), .A1N (n_4), .B0 (n_2), .Y (n_14));
  XOR2XLHVT g319(.A (n_6), .B (cin), .Y (sum[0]));
  NOR2X1HVT g320(.A (n_11), .B (n_10), .Y (o_p));
  NAND2X2HVT g321(.A (n_3), .B (n_6), .Y (n_11));
  NAND2X2HVT g322(.A (n_4), .B (n_9), .Y (n_10));
  INVX1HVT g323(.A (n_4), .Y (n_7));
  ADDHX1HVT g324(.A (a[2]), .B (b[2]), .CO (n_8), .S (n_9));
  ADDHX1HVT g325(.A (a[0]), .B (b[0]), .CO (n_5), .S (n_6));
  XOR2XLHVT g326(.A (a[1]), .B (b[1]), .Y (n_4));
  XOR2XLHVT g327(.A (a[3]), .B (b[3]), .Y (n_3));
  NAND2X1HVT g328(.A (a[1]), .B (b[1]), .Y (n_2));
  AOI21X1HVT g2(.A0 (cin), .A1 (o_p), .B0 (n_1), .Y (n_0));
  AND2X1HVT g3(.A (a[3]), .B (b[3]), .Y (n_1));
endmodule

module CLA_4bit_1(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_13, n_14, n_16, n_17;
  wire n_20, n_22;
  XNOR2X1HVT g349(.A (n_5), .B (n_22), .Y (sum[2]));
  AOI21XLHVT g350(.A0 (n_9), .A1 (n_0), .B0 (n_8), .Y (n_22));
  XNOR2X1HVT g351(.A (n_7), .B (n_20), .Y (sum[3]));
  OAI2BB1X1HVT g352(.A0N (n_10), .A1N (n_2), .B0 (n_13), .Y (n_20));
  OAI2BB1X1HVT g353(.A0N (o_p), .A1N (n_1), .B0 (n_17), .Y (o_g));
  CLKXOR2X1HVT g354(.A (n_9), .B (n_0), .Y (sum[1]));
  AOI22X1HVT g355(.A0 (n_4), .A1 (n_16), .B0 (a[3]), .B1 (b[3]), .Y
       (n_17));
  NAND2X1HVT g357(.A (n_13), .B (n_14), .Y (n_16));
  NAND2BX1HVT g358(.AN (n_3), .B (n_10), .Y (n_14));
  NOR2BX1HVT g359(.AN (n_10), .B (n_11), .Y (o_p));
  CLKXOR2X1HVT g360(.A (n_1), .B (n_6), .Y (sum[0]));
  AOI22X1HVT g361(.A0 (n_8), .A1 (n_5), .B0 (a[2]), .B1 (b[2]), .Y
       (n_13));
  NAND2X1HVT g362(.A (n_4), .B (n_6), .Y (n_11));
  AND2XLHVT g363(.A (n_9), .B (n_5), .Y (n_10));
  INVX1HVT g364(.A (n_4), .Y (n_7));
  ADDHX1HVT g365(.A (a[1]), .B (b[1]), .CO (n_8), .S (n_9));
  XOR2XLHVT g366(.A (a[0]), .B (b[0]), .Y (n_6));
  XOR2XLHVT g367(.A (a[2]), .B (b[2]), .Y (n_5));
  XOR2XLHVT g368(.A (a[3]), .B (b[3]), .Y (n_4));
  NAND2X1HVT g369(.A (a[0]), .B (b[0]), .Y (n_3));
  OAI2BB1XLHVT g370_dup(.A0N (n_6), .A1N (cin), .B0 (n_3), .Y (n_2));
  BUFX2HVT fopt(.A (cin), .Y (n_1));
  OAI2BB1XLHVT g356_dup372(.A0N (n_6), .A1N (n_1), .B0 (n_3), .Y (n_0));
endmodule

module CLA_8bit(i_carry, i_data_a, i_data_b, o_sum, o_carry);
  input i_carry;
  input [7:0] i_data_a, i_data_b;
  output [7:0] o_sum;
  output o_carry;
  wire i_carry;
  wire [7:0] i_data_a, i_data_b;
  wire [7:0] o_sum;
  wire o_carry;
  wire UNCONNECTED0, n_0, n_1, n_2, n_3, w_C, w_G, w_G_22;
  wire w_P, w_P_20;
  CLA_4bit CLA_4BIT_UNIT_0(.a (i_data_a[3:0]), .b (i_data_b[3:0]), .cin
       (i_carry), .sum (o_sum[3:0]), .o_p (w_P), .o_g (w_G));
  CLA_4bit_1 CLA_4BIT_UNIT_1(.a (i_data_a[7:4]), .b (i_data_b[7:4]),
       .cin (w_C), .sum (o_sum[7:4]), .o_p (w_P_20), .o_g (w_G_22));
  OR2XLHVT g5(.A (n_3), .B (w_G), .Y (w_C));
  AND2X1HVT g6(.A (i_carry), .B (w_P), .Y (n_3));
  OR2XLHVT g21(.A (n_2), .B (w_G_22), .Y (o_carry));
  BUFX2HVT drc_bufs(.A (w_P_20), .Y (n_1));
  BUFX2HVT drc_bufs22(.A (w_C), .Y (n_0));
  ADDHX1HVT g24(.A (n_1), .B (n_0), .CO (n_2), .S (UNCONNECTED0));
endmodule

module MAN_ALU_SIZE_MAN8(i_sign_a, i_sign_b, i_carry, i_man_max,
     i_man_min, o_man_alu, o_overflow);
  input i_sign_a, i_sign_b, i_carry;
  input [7:0] i_man_max, i_man_min;
  output [7:0] o_man_alu;
  output o_overflow;
  wire i_sign_a, i_sign_b, i_carry;
  wire [7:0] i_man_max, i_man_min;
  wire [7:0] o_man_alu;
  wire o_overflow;
  wire [7:0] w_i_man_b;
  wire n_0, n_18, w_i_carry_alu, w_overflow;
  CLA_8bit ALU_SUB_UNIT(.i_carry (w_i_carry_alu), .i_data_a
       (i_man_max), .i_data_b (w_i_man_b), .o_sum (o_man_alu), .o_carry
       (w_overflow));
  NOR2BX1HVT g34(.AN (w_overflow), .B (n_18), .Y (o_overflow));
  MX2XLHVT g123(.A (n_18), .B (n_0), .S0 (i_man_min[4]), .Y
       (w_i_man_b[4]));
  MX2XLHVT g124(.A (n_18), .B (n_0), .S0 (i_man_min[6]), .Y
       (w_i_man_b[6]));
  MX2XLHVT g125(.A (n_18), .B (n_0), .S0 (i_man_min[7]), .Y
       (w_i_man_b[7]));
  MXI2XLHVT g126(.A (n_0), .B (n_18), .S0 (i_man_min[0]), .Y
       (w_i_man_b[0]));
  MXI2XLHVT g127(.A (n_0), .B (n_18), .S0 (i_man_min[2]), .Y
       (w_i_man_b[2]));
  MXI2XLHVT g128(.A (n_0), .B (n_18), .S0 (i_man_min[5]), .Y
       (w_i_man_b[5]));
  MX2XLHVT g129(.A (n_18), .B (n_0), .S0 (i_man_min[3]), .Y
       (w_i_man_b[3]));
  MX2XLHVT g130(.A (n_18), .B (n_0), .S0 (i_man_min[1]), .Y
       (w_i_man_b[1]));
  NOR2XLHVT g131(.A (n_0), .B (i_carry), .Y (w_i_carry_alu));
  INVX1HVT g132(.A (n_0), .Y (n_18));
  XNOR2X1HVT g133(.A (i_sign_b), .B (i_sign_a), .Y (n_0));
endmodule

module SHF_left_SIZE_DATA8_SIZE_SHIFT3(i_shift_number, i_data, o_data);
  input [2:0] i_shift_number;
  input [7:0] i_data;
  output [7:0] o_data;
  wire [2:0] i_shift_number;
  wire [7:0] i_data;
  wire [7:0] o_data;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_16;
  wire n_19;
  assign o_data[7] = 1'b0;
  OAI222X1HVT g404(.A0 (n_10), .A1 (n_12), .B0 (n_7), .B1 (n_19), .C0
       (n_13), .C1 (n_8), .Y (o_data[6]));
  NOR2XLHVT g405(.A (i_shift_number[2]), .B (n_19), .Y (o_data[2]));
  OAI222XLHVT g406(.A0 (n_10), .A1 (n_13), .B0 (n_2), .B1 (n_8), .C0
       (n_11), .C1 (n_9), .Y (o_data[4]));
  OAI222X1HVT g407(.A0 (n_9), .A1 (n_0), .B0 (n_10), .B1 (n_14), .C0
       (n_16), .C1 (n_8), .Y (o_data[5]));
  MX2XLHVT g408(.A (n_2), .B (n_11), .S0 (i_shift_number[1]), .Y
       (n_19));
  OAI22X1HVT g409(.A0 (n_10), .A1 (n_16), .B0 (n_0), .B1 (n_8), .Y
       (o_data[3]));
  NOR2X1HVT g410(.A (n_10), .B (n_0), .Y (o_data[1]));
  NOR2X1HVT g411(.A (n_10), .B (n_11), .Y (o_data[0]));
  AOI22XLHVT g412(.A0 (i_data[5]), .A1 (n_4), .B0 (i_data[4]), .B1
       (n_5), .Y (n_14));
  AOI22XLHVT g413(.A0 (i_data[3]), .A1 (n_4), .B0 (i_data[2]), .B1
       (n_5), .Y (n_16));
  AOI22XLHVT g414(.A0 (i_data[6]), .A1 (n_4), .B0 (i_data[5]), .B1
       (n_5), .Y (n_12));
  AOI22XLHVT g416(.A0 (i_data[4]), .A1 (n_4), .B0 (i_data[3]), .B1
       (n_5), .Y (n_13));
  NAND2XLHVT g418(.A (i_data[0]), .B (n_6), .Y (n_11));
  OR2X1HVT g419(.A (i_shift_number[2]), .B (i_shift_number[1]), .Y
       (n_10));
  NAND2BXLHVT g420(.AN (i_shift_number[1]), .B (i_shift_number[2]), .Y
       (n_9));
  NAND2X1HVT g421(.A (i_shift_number[1]), .B (n_7), .Y (n_8));
  INVX1HVT g422(.A (i_shift_number[2]), .Y (n_7));
  INVX1HVT g423(.A (i_shift_number[0]), .Y (n_6));
  BUFX2HVT fopt424(.A (i_shift_number[0]), .Y (n_5));
  BUFX3HVT fopt425(.A (n_6), .Y (n_4));
  AOI21X1HVT g2(.A0 (i_data[2]), .A1 (n_6), .B0 (n_3), .Y (n_2));
  AND2XLHVT g3(.A (i_data[1]), .B (n_5), .Y (n_3));
  AOI21XLHVT g426(.A0 (i_data[1]), .A1 (n_4), .B0 (n_1), .Y (n_0));
  AND2X1HVT g427(.A (i_data[0]), .B (n_5), .Y (n_1));
endmodule

module NOR_unit_SIZE_LOPD3_SIZE_DATA8(i_overflow, i_zero_flag,
     i_one_position, i_mantissa, o_mantissa);
  input i_overflow, i_zero_flag;
  input [2:0] i_one_position;
  input [7:0] i_mantissa;
  output [7:0] o_mantissa;
  wire i_overflow, i_zero_flag;
  wire [2:0] i_one_position;
  wire [7:0] i_mantissa;
  wire [7:0] o_mantissa;
  wire [7:0] w_shift_left;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10;
  assign o_mantissa[7] = 1'b0;
  SHF_left_SIZE_DATA8_SIZE_SHIFT3 SHF_left_unit(.i_shift_number
       (i_one_position), .i_data ({1'b0, i_mantissa[6:0]}), .o_data
       (w_shift_left));
  OAI2BB1X1HVT g423(.A0N (n_3), .A1N (w_shift_left[5]), .B0 (n_6), .Y
       (o_mantissa[5]));
  OAI2BB1X1HVT g424(.A0N (n_3), .A1N (w_shift_left[4]), .B0 (n_8), .Y
       (o_mantissa[4]));
  OAI2BB1X1HVT g425(.A0N (n_3), .A1N (w_shift_left[2]), .B0 (n_9), .Y
       (o_mantissa[2]));
  OAI2BB1X1HVT g426(.A0N (n_3), .A1N (w_shift_left[1]), .B0 (n_7), .Y
       (o_mantissa[1]));
  OAI2BB1X1HVT g427(.A0N (n_3), .A1N (w_shift_left[3]), .B0 (n_10), .Y
       (o_mantissa[3]));
  OAI2BB1X1HVT g428(.A0N (n_3), .A1N (w_shift_left[0]), .B0 (n_5), .Y
       (o_mantissa[0]));
  OAI2BB1X1HVT g429(.A0N (n_3), .A1N (w_shift_left[6]), .B0 (n_4), .Y
       (o_mantissa[6]));
  AOI22X1HVT g430(.A0 (i_mantissa[3]), .A1 (n_2), .B0 (i_mantissa[4]),
       .B1 (n_0), .Y (n_10));
  AOI22X1HVT g431(.A0 (i_mantissa[2]), .A1 (n_2), .B0 (i_mantissa[3]),
       .B1 (n_0), .Y (n_9));
  AOI22X1HVT g432(.A0 (i_mantissa[4]), .A1 (n_2), .B0 (i_mantissa[5]),
       .B1 (n_0), .Y (n_8));
  AOI22X1HVT g433(.A0 (i_mantissa[1]), .A1 (n_2), .B0 (i_mantissa[2]),
       .B1 (n_0), .Y (n_7));
  AOI22X1HVT g434(.A0 (i_mantissa[5]), .A1 (n_2), .B0 (i_mantissa[6]),
       .B1 (n_0), .Y (n_6));
  AOI22X1HVT g435(.A0 (i_mantissa[0]), .A1 (n_2), .B0 (i_mantissa[1]),
       .B1 (n_0), .Y (n_5));
  OAI21X1HVT g436(.A0 (n_1), .A1 (n_0), .B0 (i_mantissa[7]), .Y (n_4));
  NOR3X1HVT g437(.A (i_overflow), .B (i_mantissa[7]), .C (i_zero_flag),
       .Y (n_3));
  NOR3BX1HVT g438(.AN (i_mantissa[7]), .B (i_overflow), .C
       (i_zero_flag), .Y (n_2));
  NOR2BX1HVT g439(.AN (i_mantissa[6]), .B (i_zero_flag), .Y (n_1));
  NOR2BX1HVT g440(.AN (i_overflow), .B (i_zero_flag), .Y (n_0));
endmodule

module PSC_unit(i_sign_a, i_exp_a, i_man_a, i_sign_b, i_exp_b, i_man_b,
     o_sel_exp, o_sel_man);
  input i_sign_a, i_sign_b;
  input [7:0] i_exp_a, i_exp_b;
  input [23:0] i_man_a, i_man_b;
  output o_sel_exp;
  output [1:0] o_sel_man;
  wire i_sign_a, i_sign_b;
  wire [7:0] i_exp_a, i_exp_b;
  wire [23:0] i_man_a, i_man_b;
  wire o_sel_exp;
  wire [1:0] o_sel_man;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_24;
  wire n_25, n_26;
  assign o_sel_man[1] = 1'b0;
  OAI22X1HVT g466(.A0 (n_18), .A1 (n_26), .B0 (n_20), .B1 (n_25), .Y
       (o_sel_man[0]));
  AOI2BB1X1HVT g467(.A0N (n_4), .A1N (n_20), .B0 (n_24), .Y (n_26));
  NOR4X1HVT g468(.A (i_man_a[0]), .B (n_0), .C (n_9), .D (n_21), .Y
       (n_25));
  NAND3BXLHVT g469(.AN (n_22), .B (n_6), .C (n_7), .Y (n_24));
  OR2X1HVT g470(.A (n_17), .B (n_19), .Y (o_sel_exp));
  NAND4X1HVT g471(.A (n_12), .B (n_1), .C (n_2), .D (n_8), .Y (n_22));
  NAND4X1HVT g472(.A (n_10), .B (n_11), .C (n_3), .D (n_5), .Y (n_21));
  INVX1HVT g473(.A (n_19), .Y (n_20));
  NOR2X1HVT g474(.A (n_14), .B (n_13), .Y (n_19));
  INVX1HVT g475(.A (n_17), .Y (n_18));
  NOR2X1HVT g476(.A (n_16), .B (n_15), .Y (n_17));
  NAND4X1HVT g477(.A (i_exp_b[0]), .B (i_exp_b[1]), .C (i_exp_b[2]), .D
       (i_exp_b[3]), .Y (n_16));
  NAND4X1HVT g478(.A (i_exp_b[4]), .B (i_exp_b[5]), .C (i_exp_b[6]), .D
       (i_exp_b[7]), .Y (n_15));
  NAND4X1HVT g479(.A (i_exp_a[0]), .B (i_exp_a[1]), .C (i_exp_a[2]), .D
       (i_exp_a[3]), .Y (n_14));
  NAND4X1HVT g480(.A (i_exp_a[4]), .B (i_exp_a[5]), .C (i_exp_a[6]), .D
       (i_exp_a[7]), .Y (n_13));
  NOR3X1HVT g481(.A (i_man_b[21]), .B (i_man_b[22]), .C (i_man_b[4]),
       .Y (n_12));
  NOR4X1HVT g482(.A (i_man_a[19]), .B (i_man_a[20]), .C (i_man_a[21]),
       .D (i_man_a[22]), .Y (n_11));
  NOR4X1HVT g483(.A (i_man_a[7]), .B (i_man_a[8]), .C (i_man_a[9]), .D
       (i_man_a[10]), .Y (n_10));
  OR4X1HVT g484(.A (i_man_a[1]), .B (i_man_a[2]), .C (i_man_a[3]), .D
       (i_man_a[4]), .Y (n_9));
  NOR4X1HVT g485(.A (i_man_b[17]), .B (i_man_b[18]), .C (i_man_b[19]),
       .D (i_man_b[20]), .Y (n_8));
  NOR4X1HVT g486(.A (i_man_b[11]), .B (i_man_b[12]), .C (i_man_b[13]),
       .D (i_man_b[14]), .Y (n_7));
  NOR4X1HVT g487(.A (i_man_b[7]), .B (i_man_b[8]), .C (i_man_b[9]), .D
       (i_man_b[10]), .Y (n_6));
  NOR4X1HVT g488(.A (i_man_a[15]), .B (i_man_a[16]), .C (i_man_a[17]),
       .D (i_man_a[18]), .Y (n_5));
  XNOR2X1HVT g489(.A (i_sign_b), .B (i_sign_a), .Y (n_4));
  NOR4X1HVT g490(.A (i_man_a[11]), .B (i_man_a[12]), .C (i_man_a[13]),
       .D (i_man_a[14]), .Y (n_3));
  NOR4X1HVT g491(.A (i_man_b[2]), .B (i_man_b[3]), .C (i_man_b[15]), .D
       (i_man_b[16]), .Y (n_2));
  NOR4X1HVT g492(.A (i_man_b[0]), .B (i_man_b[1]), .C (i_man_b[5]), .D
       (i_man_b[6]), .Y (n_1));
  OR2XLHVT g493(.A (i_man_a[5]), .B (i_man_a[6]), .Y (n_0));
endmodule

module SHF_right_SIZE_DATA16_SIZE_SHIFT4(i_shift_number, i_data,
     o_data);
  input [3:0] i_shift_number;
  input [15:0] i_data;
  output [15:0] o_data;
  wire [3:0] i_shift_number;
  wire [15:0] i_data;
  wire [15:0] o_data;
  wire n_0, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_29;
  assign o_data[0] = 1'b0;
  assign o_data[1] = 1'b0;
  assign o_data[2] = 1'b0;
  assign o_data[3] = 1'b0;
  assign o_data[4] = 1'b0;
  assign o_data[5] = 1'b0;
  assign o_data[6] = 1'b0;
  NOR2X1HVT g993(.A (i_shift_number[3]), .B (n_29), .Y (o_data[9]));
  NOR2X1HVT g994(.A (i_shift_number[3]), .B (n_0), .Y (o_data[8]));
  OAI222X1HVT g995(.A0 (n_25), .A1 (n_7), .B0 (n_26), .B1 (n_5), .C0
       (n_15), .C1 (n_4), .Y (o_data[7]));
  OAI22X1HVT g996(.A0 (n_20), .A1 (n_7), .B0 (n_17), .B1 (n_5), .Y
       (o_data[10]));
  OAI22X1HVT g997(.A0 (n_26), .A1 (n_7), .B0 (n_6), .B1 (n_5), .Y
       (o_data[11]));
  MXI2XLHVT g998(.A (n_21), .B (n_23), .S0 (i_shift_number[2]), .Y
       (n_29));
  NOR2BX1HVT g1000(.AN (n_22), .B (n_7), .Y (o_data[12]));
  NOR2BX1HVT g1001(.AN (n_23), .B (n_7), .Y (o_data[13]));
  AOI32X1HVT g1002(.A0 (i_data[8]), .A1 (i_shift_number[0]), .A2 (n_2),
       .B0 (n_13), .B1 (i_shift_number[1]), .Y (n_25));
  OAI22X1HVT g1003(.A0 (n_14), .A1 (i_shift_number[1]), .B0 (n_10), .B1
       (n_2), .Y (n_24));
  MX2XLHVT g1004(.A (n_16), .B (n_9), .S0 (i_shift_number[1]), .Y
       (n_26));
  OAI22X1HVT g1005(.A0 (n_12), .A1 (i_shift_number[1]), .B0 (n_16), .B1
       (n_2), .Y (n_21));
  MX2XLHVT g1006(.A (n_10), .B (n_11), .S0 (i_shift_number[1]), .Y
       (n_20));
  OAI22X1HVT g1007(.A0 (n_9), .A1 (i_shift_number[1]), .B0
       (i_shift_number[0]), .B1 (n_2), .Y (n_23));
  OAI22X1HVT g1008(.A0 (n_11), .A1 (i_shift_number[1]), .B0 (n_8), .B1
       (n_2), .Y (n_22));
  NOR2X1HVT g1009(.A (n_17), .B (n_7), .Y (o_data[14]));
  NOR2X1HVT g1010(.A (n_15), .B (i_shift_number[3]), .Y (o_data[15]));
  AOI22X1HVT g1011(.A0 (i_data[8]), .A1 (n_3), .B0 (i_data[9]), .B1
       (i_shift_number[0]), .Y (n_14));
  OR2XLHVT g1012(.A (n_8), .B (i_shift_number[1]), .Y (n_17));
  AOI22X1HVT g1013(.A0 (i_data[11]), .A1 (n_3), .B0 (i_data[12]), .B1
       (i_shift_number[0]), .Y (n_16));
  OR2X1HVT g1014(.A (i_shift_number[2]), .B (n_6), .Y (n_15));
  INVX1HVT g1015(.A (n_12), .Y (n_13));
  AOI22X1HVT g1016(.A0 (i_data[9]), .A1 (n_3), .B0 (i_data[10]), .B1
       (i_shift_number[0]), .Y (n_12));
  AOI22X1HVT g1017(.A0 (i_data[12]), .A1 (n_3), .B0 (i_data[13]), .B1
       (i_shift_number[0]), .Y (n_11));
  AOI22X1HVT g1018(.A0 (i_data[10]), .A1 (n_3), .B0 (i_data[11]), .B1
       (i_shift_number[0]), .Y (n_10));
  AOI22X1HVT g1019(.A0 (i_data[13]), .A1 (n_3), .B0 (i_data[14]), .B1
       (i_shift_number[0]), .Y (n_9));
  NOR2X1HVT g1020(.A (i_data[14]), .B (i_shift_number[0]), .Y (n_8));
  OR2X1HVT g1021(.A (i_shift_number[2]), .B (i_shift_number[3]), .Y
       (n_7));
  NAND2X1HVT g1022(.A (n_3), .B (n_2), .Y (n_6));
  NAND2X1HVT g1023(.A (i_shift_number[2]), .B (n_4), .Y (n_5));
  INVX1HVT g1024(.A (i_shift_number[3]), .Y (n_4));
  INVX1HVT g1026(.A (i_shift_number[0]), .Y (n_3));
  INVX1HVT g1027(.A (i_shift_number[1]), .Y (n_2));
  MXI2XLHVT g2(.A (n_24), .B (n_22), .S0 (i_shift_number[2]), .Y (n_0));
endmodule

module SIGN_unit(i_comp_man, i_sign_man_a, i_sign_man_b, o_sign_s);
  input i_comp_man, i_sign_man_a, i_sign_man_b;
  output o_sign_s;
  wire i_comp_man, i_sign_man_a, i_sign_man_b;
  wire o_sign_s;
  wire n_0, n_2;
  MX2X1HVT g23(.A (i_sign_man_a), .B (i_sign_man_b), .S0 (i_comp_man),
       .Y (n_2));
  BUFX6HVT drc_bufs(.A (n_2), .Y (n_0));
  CLKBUFX20HVT drc_bufs24(.A (n_0), .Y (o_sign_s));
endmodule

module CLA_4bit_4(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_0, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_10, n_12, n_14;
  assign o_g = 1'b0;
  assign o_p = 1'b0;
  CLKXOR2X1HVT g202(.A (n_8), .B (n_14), .Y (sum[3]));
  AOI2BB1XLHVT g203(.A0N (n_7), .A1N (n_12), .B0 (n_3), .Y (n_14));
  CLKXOR2X1HVT g204(.A (n_7), .B (n_12), .Y (sum[2]));
  AOI22X1HVT g205(.A0 (n_6), .A1 (n_10), .B0 (a[1]), .B1 (b[1]), .Y
       (n_12));
  CLKXOR2X1HVT g206(.A (n_6), .B (n_10), .Y (sum[1]));
  NAND2X4HVT g207(.A (n_2), .B (sum[0]), .Y (n_10));
  XNOR2X1HVT g208(.A (a[3]), .B (b[3]), .Y (n_8));
  NOR2X6HVT g209(.A (n_5), .B (n_4), .Y (sum[0]));
  XNOR2X1HVT g210(.A (a[2]), .B (b[2]), .Y (n_7));
  XOR2XLHVT g211(.A (a[1]), .B (b[1]), .Y (n_6));
  NOR2X1HVT g212(.A (a[0]), .B (n_2), .Y (n_5));
  NOR2BX2HVT g213(.AN (a[0]), .B (n_0), .Y (n_4));
  AND2XLHVT g214(.A (a[2]), .B (b[2]), .Y (n_3));
  INVX1HVT g215(.A (b[0]), .Y (n_2));
  BUFX2HVT fopt(.A (b[0]), .Y (n_0));
endmodule

module CLA_8bit_2(i_carry, i_data_a, i_data_b, o_sum, o_carry);
  input i_carry;
  input [7:0] i_data_a, i_data_b;
  output [7:0] o_sum;
  output o_carry;
  wire i_carry;
  wire [7:0] i_data_a, i_data_b;
  wire [7:0] o_sum;
  wire o_carry;
  wire w_G, w_P;
  assign o_carry = 1'b0;
  assign o_sum[4] = 1'b0;
  assign o_sum[5] = 1'b0;
  assign o_sum[6] = 1'b0;
  assign o_sum[7] = 1'b0;
  CLA_4bit_4 CLA_4BIT_UNIT_0(.a (i_data_a[3:0]), .b (i_data_b[3:0]),
       .cin (1'b1), .sum (o_sum[3:0]), .o_p (w_P), .o_g (w_G));
endmodule

module SWAP_unit_SIZE_DATA8(i_comp_less, i_data_a, i_data_b,
     o_data_max, o_data_min);
  input i_comp_less;
  input [7:0] i_data_a, i_data_b;
  output [7:0] o_data_max, o_data_min;
  wire i_comp_less;
  wire [7:0] i_data_a, i_data_b;
  wire [7:0] o_data_max, o_data_min;
  assign o_data_min[4] = 1'b0;
  assign o_data_min[5] = 1'b0;
  assign o_data_min[6] = 1'b0;
  assign o_data_min[7] = 1'b0;
  MX2XLHVT g199(.A (i_data_a[7]), .B (i_data_b[7]), .S0 (i_comp_less),
       .Y (o_data_max[7]));
  MX2XLHVT g200(.A (i_data_a[4]), .B (i_data_b[4]), .S0 (i_comp_less),
       .Y (o_data_max[4]));
  MX2XLHVT g201(.A (i_data_a[1]), .B (i_data_b[1]), .S0 (i_comp_less),
       .Y (o_data_max[1]));
  MX2XLHVT g202(.A (i_data_a[0]), .B (i_data_b[0]), .S0 (i_comp_less),
       .Y (o_data_max[0]));
  MX2XLHVT g203(.A (i_data_a[3]), .B (i_data_b[3]), .S0 (i_comp_less),
       .Y (o_data_max[3]));
  MX2XLHVT g204(.A (i_data_b[3]), .B (i_data_a[3]), .S0 (i_comp_less),
       .Y (o_data_min[3]));
  MX2XLHVT g205(.A (i_data_b[2]), .B (i_data_a[2]), .S0 (i_comp_less),
       .Y (o_data_min[2]));
  MX2XLHVT g206(.A (i_data_a[6]), .B (i_data_b[6]), .S0 (i_comp_less),
       .Y (o_data_max[6]));
  MX2XLHVT g207(.A (i_data_a[5]), .B (i_data_b[5]), .S0 (i_comp_less),
       .Y (o_data_max[5]));
  MX2XLHVT g208(.A (i_data_b[1]), .B (i_data_a[1]), .S0 (i_comp_less),
       .Y (o_data_min[1]));
  MX2X1HVT g209(.A (i_data_a[2]), .B (i_data_b[2]), .S0 (i_comp_less),
       .Y (o_data_max[2]));
  MX2X1HVT g2(.A (i_data_b[0]), .B (i_data_a[0]), .S0 (i_comp_less), .Y
       (o_data_min[0]));
endmodule

module SWAP_unit_SIZE_DATA8_1(i_comp_less, i_data_a, i_data_b,
     o_data_max, o_data_min);
  input i_comp_less;
  input [7:0] i_data_a, i_data_b;
  output [7:0] o_data_max, o_data_min;
  wire i_comp_less;
  wire [7:0] i_data_a, i_data_b;
  wire [7:0] o_data_max, o_data_min;
  assign o_data_min[7] = 1'b1;
  assign o_data_max[7] = 1'b1;
  MX2XLHVT g226(.A (i_data_b[5]), .B (i_data_a[5]), .S0 (i_comp_less),
       .Y (o_data_min[5]));
  MX2X1HVT g227(.A (i_data_a[5]), .B (i_data_b[5]), .S0 (i_comp_less),
       .Y (o_data_max[5]));
  MX2XLHVT g228(.A (i_data_a[3]), .B (i_data_b[3]), .S0 (i_comp_less),
       .Y (o_data_max[3]));
  MX2XLHVT g229(.A (i_data_a[0]), .B (i_data_b[0]), .S0 (i_comp_less),
       .Y (o_data_max[0]));
  MX2XLHVT g230(.A (i_data_b[6]), .B (i_data_a[6]), .S0 (i_comp_less),
       .Y (o_data_min[6]));
  MX2XLHVT g231(.A (i_data_a[2]), .B (i_data_b[2]), .S0 (i_comp_less),
       .Y (o_data_max[2]));
  MX2XLHVT g232(.A (i_data_a[6]), .B (i_data_b[6]), .S0 (i_comp_less),
       .Y (o_data_max[6]));
  MX2XLHVT g233(.A (i_data_b[0]), .B (i_data_a[0]), .S0 (i_comp_less),
       .Y (o_data_min[0]));
  MX2XLHVT g234(.A (i_data_b[3]), .B (i_data_a[3]), .S0 (i_comp_less),
       .Y (o_data_min[3]));
  MX2X1HVT g235(.A (i_data_a[4]), .B (i_data_b[4]), .S0 (i_comp_less),
       .Y (o_data_max[4]));
  MX2XLHVT g236(.A (i_data_b[2]), .B (i_data_a[2]), .S0 (i_comp_less),
       .Y (o_data_min[2]));
  MX2XLHVT g237(.A (i_data_b[1]), .B (i_data_a[1]), .S0 (i_comp_less),
       .Y (o_data_min[1]));
  MX2XLHVT g238(.A (i_data_a[1]), .B (i_data_b[1]), .S0 (i_comp_less),
       .Y (o_data_max[1]));
  MX2XLHVT g239(.A (i_data_b[4]), .B (i_data_a[4]), .S0 (i_comp_less),
       .Y (o_data_min[4]));
endmodule

module SWAP_unit_SIZE_DATA8_2(i_comp_less, i_data_a, i_data_b,
     o_data_max, o_data_min);
  input i_comp_less;
  input [7:0] i_data_a, i_data_b;
  output [7:0] o_data_max, o_data_min;
  wire i_comp_less;
  wire [7:0] i_data_a, i_data_b;
  wire [7:0] o_data_max, o_data_min;
  wire n_1, n_2, n_3, n_4;
  MX2XLHVT g227(.A (i_data_b[4]), .B (i_data_a[4]), .S0 (n_4), .Y
       (o_data_min[4]));
  MX2XLHVT g228(.A (i_data_a[5]), .B (i_data_b[5]), .S0 (n_4), .Y
       (o_data_max[5]));
  MX2XLHVT g229(.A (i_data_a[3]), .B (i_data_b[3]), .S0 (n_3), .Y
       (o_data_max[3]));
  MX2XLHVT g230(.A (i_data_a[0]), .B (i_data_b[0]), .S0 (n_3), .Y
       (o_data_max[0]));
  MX2XLHVT g231(.A (i_data_b[6]), .B (i_data_a[6]), .S0 (n_4), .Y
       (o_data_min[6]));
  MX2XLHVT g232(.A (i_data_b[5]), .B (i_data_a[5]), .S0 (n_4), .Y
       (o_data_min[5]));
  MX2XLHVT g233(.A (i_data_a[6]), .B (i_data_b[6]), .S0 (n_4), .Y
       (o_data_max[6]));
  MX2XLHVT g235(.A (i_data_a[2]), .B (i_data_b[2]), .S0 (n_3), .Y
       (o_data_max[2]));
  MX2XLHVT g236(.A (i_data_b[3]), .B (i_data_a[3]), .S0 (n_2), .Y
       (o_data_min[3]));
  MX2XLHVT g237(.A (i_data_b[2]), .B (i_data_a[2]), .S0 (n_2), .Y
       (o_data_min[2]));
  MX2XLHVT g238(.A (i_data_b[1]), .B (i_data_a[1]), .S0 (i_comp_less),
       .Y (o_data_min[1]));
  MX2XLHVT g239(.A (i_data_a[1]), .B (i_data_b[1]), .S0 (n_3), .Y
       (o_data_max[1]));
  MX2XLHVT g240(.A (i_data_a[4]), .B (i_data_b[4]), .S0 (n_4), .Y
       (o_data_max[4]));
  NAND2BXLHVT g241(.AN (i_data_b[7]), .B (n_4), .Y (o_data_max[7]));
  OR2XLHVT g242(.A (i_data_b[7]), .B (n_4), .Y (o_data_min[7]));
  BUFX3HVT fopt244(.A (n_3), .Y (n_4));
  INVX1HVT fopt245(.A (n_1), .Y (n_3));
  INVX1HVT fopt246(.A (n_1), .Y (n_2));
  INVX2HVT fopt247(.A (i_comp_less), .Y (n_1));
  MX2XLHVT g2(.A (i_data_a[0]), .B (i_data_b[0]), .S0 (n_1), .Y
       (o_data_min[0]));
endmodule

module BFP16_add(i_data_a, i_data_b, o_bfu_add);
  input [31:0] i_data_a, i_data_b;
  output [31:0] o_bfu_add;
  wire [31:0] i_data_a, i_data_b;
  wire [31:0] o_bfu_add;
  wire [7:0] w_swap_man0_max;
  wire [15:0] w_shf_right_man1_min;
  wire [7:0] w_alu_man_result;
  wire [2:0] w_lopd_one_pos;
  wire [7:0] w_swap_exp_max;
  wire [7:0] w_exp_adjust;
  wire [7:0] w_swap_man1_max;
  wire [7:0] w_swap_man1_min;
  wire [7:0] w_nor_man;
  wire [1:0] w_sel_man;
  wire [7:0] w_sub_exp_result;
  wire [7:0] w_swap_man0_min;
  wire [7:0] w_swap_exp_min;
  wire UNCONNECTED1, UNCONNECTED2, UNCONNECTED3, UNCONNECTED4, n_0,
       n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_42, w_alu_man_overflow,
       w_comp_exp_less;
  wire w_comp_man_less, w_lopd_zero_flag, w_sel_exp;
  assign o_bfu_add[0] = 1'b0;
  assign o_bfu_add[1] = 1'b0;
  assign o_bfu_add[2] = 1'b0;
  assign o_bfu_add[3] = 1'b0;
  assign o_bfu_add[4] = 1'b0;
  assign o_bfu_add[5] = 1'b0;
  assign o_bfu_add[6] = 1'b0;
  assign o_bfu_add[7] = 1'b0;
  assign o_bfu_add[8] = 1'b0;
  assign o_bfu_add[9] = 1'b0;
  assign o_bfu_add[10] = 1'b0;
  assign o_bfu_add[11] = 1'b0;
  assign o_bfu_add[12] = 1'b0;
  assign o_bfu_add[13] = 1'b0;
  assign o_bfu_add[14] = 1'b0;
  assign o_bfu_add[15] = 1'b0;
  COMP_8bit_SIZE_DATA8 COMP_EXP_UNIT(.i_data_a (i_data_a[30:23]),
       .i_data_b (i_data_b[30:23]), .o_less (w_comp_exp_less));
  COMP_8bit_SIZE_DATA8_1 COMP_MAN_UNIT(.i_data_a ({1'b1,
       w_swap_man0_max[6:0]}), .i_data_b (w_shf_right_man1_min[15:8]),
       .o_less (w_comp_man_less));
  EXP_adjust_SIZE_EXP8_SIZE_LOPD8 EXP_ADJUSTION_UNIT(.i_overflow
       (w_alu_man_overflow), .i_underflow (w_alu_man_result[7]),
       .i_zero_flag (w_lopd_zero_flag), .i_lopd_value ({5'b00000,
       w_lopd_one_pos}), .i_exp_value (w_swap_exp_max), .o_exp_result
       (w_exp_adjust));
  LOPD_8bit LOPD_UNIT(.i_data (w_alu_man_result), .o_pos_one
       (w_lopd_one_pos), .o_zero_flag (w_lopd_zero_flag));
  MAN_ALU_SIZE_MAN8 MAN_ALU_UNIT(.i_sign_a (i_data_a[31]), .i_sign_b
       (i_data_b[31]), .i_carry (w_shf_right_man1_min[7]), .i_man_max
       (w_swap_man1_max), .i_man_min (w_swap_man1_min), .o_man_alu
       (w_alu_man_result), .o_overflow (w_alu_man_overflow));
  NOR_unit_SIZE_LOPD3_SIZE_DATA8 NOR_UNIT(.i_overflow
       (w_alu_man_overflow), .i_zero_flag (w_lopd_zero_flag),
       .i_one_position (w_lopd_one_pos), .i_mantissa
       (w_alu_man_result), .o_mantissa (w_nor_man));
  PSC_unit PSC_UNIT(.i_sign_a (i_data_a[31]), .i_exp_a
       (i_data_a[30:23]), .i_man_a ({1'b1, i_data_a[22:0]}), .i_sign_b
       (i_data_b[31]), .i_exp_b (i_data_b[30:23]), .i_man_b ({1'b1,
       i_data_b[22:0]}), .o_sel_exp (w_sel_exp), .o_sel_man
       ({UNCONNECTED1, w_sel_man[0]}));
  SHF_right_SIZE_DATA16_SIZE_SHIFT4 SHF_RIGHT_MAN_UNIT(.i_shift_number
       (w_sub_exp_result[3:0]), .i_data ({1'b1, w_swap_man0_min[6:0],
       8'b00000000}), .o_data (w_shf_right_man1_min));
  SIGN_unit SIGN_UNIT(.i_comp_man (n_42), .i_sign_man_a (i_data_a[31]),
       .i_sign_man_b (i_data_b[31]), .o_sign_s (o_bfu_add[31]));
  CLA_8bit_2 SUB_EXP_UNIT(.i_carry (1'b1), .i_data_a ({4'b0000,
       w_swap_exp_max[3:0]}), .i_data_b ({4'b0000, n_6, n_8, n_5,
       n_7}), .o_sum (w_sub_exp_result), .o_carry (UNCONNECTED2));
  SWAP_unit_SIZE_DATA8 SWAP_EXP_UNIT(.i_comp_less (w_comp_exp_less),
       .i_data_a (i_data_a[30:23]), .i_data_b (i_data_b[30:23]),
       .o_data_max (w_swap_exp_max), .o_data_min (w_swap_exp_min));
  SWAP_unit_SIZE_DATA8_1 SWAP_MAN0_UNIT(.i_comp_less (w_comp_exp_less),
       .i_data_a ({1'b1, i_data_a[22:16]}), .i_data_b ({1'b1,
       i_data_b[22:16]}), .o_data_max ({UNCONNECTED3,
       w_swap_man0_max[6:0]}), .o_data_min ({UNCONNECTED4,
       w_swap_man0_min[6:0]}));
  SWAP_unit_SIZE_DATA8_2 SWAP_MAN1_UNIT(.i_comp_less (w_comp_man_less),
       .i_data_a ({1'b1, w_swap_man0_max[6:0]}), .i_data_b
       (w_shf_right_man1_min[15:8]), .o_data_max (w_swap_man1_max),
       .o_data_min (w_swap_man1_min));
  INVX1HVT g56(.A (w_swap_exp_min[2]), .Y (n_8));
  INVX1HVT g57(.A (w_swap_exp_min[0]), .Y (n_7));
  INVX1HVT g55(.A (w_swap_exp_min[3]), .Y (n_6));
  INVX1HVT g58(.A (w_swap_exp_min[1]), .Y (n_5));
  MX2X1HVT g111(.A (w_nor_man[6]), .B (w_sel_man[0]), .S0 (w_sel_exp),
       .Y (n_4));
  CLKAND2X12HVT g112(.A (n_0), .B (w_nor_man[5]), .Y (o_bfu_add[21]));
  OR2X8HVT g113(.A (w_sel_exp), .B (w_exp_adjust[6]), .Y
       (o_bfu_add[29]));
  OR2X1HVT g114(.A (w_sel_exp), .B (w_exp_adjust[0]), .Y (n_3));
  CLKAND2X12HVT g115(.A (n_0), .B (w_nor_man[0]), .Y (o_bfu_add[16]));
  OR2X8HVT g116(.A (w_sel_exp), .B (w_exp_adjust[4]), .Y
       (o_bfu_add[27]));
  OR2X8HVT g117(.A (w_sel_exp), .B (w_exp_adjust[3]), .Y
       (o_bfu_add[26]));
  OR2X8HVT g118(.A (w_sel_exp), .B (w_exp_adjust[7]), .Y
       (o_bfu_add[30]));
  CLKAND2X12HVT g119(.A (n_0), .B (w_nor_man[1]), .Y (o_bfu_add[17]));
  OR2X1HVT g120(.A (w_sel_exp), .B (w_exp_adjust[2]), .Y (n_2));
  CLKAND2X12HVT g121(.A (n_0), .B (w_nor_man[4]), .Y (o_bfu_add[20]));
  CLKAND2X12HVT g122(.A (n_0), .B (w_nor_man[3]), .Y (o_bfu_add[19]));
  OR2X1HVT g123(.A (w_sel_exp), .B (w_exp_adjust[1]), .Y (n_1));
  CLKAND2X12HVT g124(.A (n_0), .B (w_nor_man[2]), .Y (o_bfu_add[18]));
  OR2X8HVT g125(.A (w_sel_exp), .B (w_exp_adjust[5]), .Y
       (o_bfu_add[28]));
  INVX3HVT g126(.A (w_sel_exp), .Y (n_0));
  CLKBUFX20HVT drc_bufs(.A (n_3), .Y (o_bfu_add[23]));
  CLKBUFX20HVT drc_bufs128(.A (n_2), .Y (o_bfu_add[25]));
  CLKBUFX20HVT drc_bufs130(.A (n_1), .Y (o_bfu_add[24]));
  CLKBUFX20HVT drc_bufs139(.A (n_4), .Y (o_bfu_add[22]));
  OR2XLHVT g51(.A (w_comp_exp_less), .B (w_comp_man_less), .Y (n_42));
endmodule

