
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: Dec  9 2025 12:36:06

// Verification Directory fv/BFP16_add 

module COMP_4bit_1(i_data_a, i_data_b, o_less, o_equal);
  input [3:0] i_data_a, i_data_b;
  output o_less, o_equal;
  wire [3:0] i_data_a, i_data_b;
  wire o_less, o_equal;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_19, n_20;
  OAI21X1HVT g334(.A0 (n_15), .A1 (n_20), .B0 (n_19), .Y (o_less));
  AOI21X1HVT g335(.A0 (n_12), .A1 (n_13), .B0 (n_8), .Y (n_20));
  AOI21X1HVT g336(.A0 (n_14), .A1 (n_11), .B0 (n_10), .Y (n_19));
  NOR2X1HVT g337(.A (n_16), .B (n_17), .Y (o_equal));
  NAND2X1HVT g338(.A (n_1), .B (n_0), .Y (n_17));
  NAND2X1HVT g339(.A (n_3), .B (n_2), .Y (n_16));
  NAND2X1HVT g340(.A (n_9), .B (n_11), .Y (n_15));
  NOR2X1HVT g345(.A (i_data_a[2]), .B (n_5), .Y (n_14));
  NAND2X1HVT g346(.A (i_data_a[1]), .B (n_6), .Y (n_13));
  NOR2X1HVT g347(.A (i_data_a[0]), .B (n_7), .Y (n_12));
  NOR2X1HVT g348(.A (i_data_a[3]), .B (n_4), .Y (n_10));
  NAND2X1HVT g349(.A (i_data_a[2]), .B (n_5), .Y (n_9));
  NOR2X1HVT g350(.A (i_data_a[1]), .B (n_6), .Y (n_8));
  NAND2X1HVT g351(.A (i_data_a[3]), .B (n_4), .Y (n_11));
  INVX1HVT g352(.A (i_data_b[0]), .Y (n_7));
  INVX1HVT g353(.A (i_data_b[1]), .Y (n_6));
  INVX1HVT g354(.A (i_data_b[2]), .Y (n_5));
  INVX1HVT g355(.A (i_data_b[3]), .Y (n_4));
  MXI2XLHVT g2(.A (i_data_b[0]), .B (n_7), .S0 (i_data_a[0]), .Y (n_3));
  MXI2XLHVT g360(.A (i_data_b[2]), .B (n_5), .S0 (i_data_a[2]), .Y
       (n_2));
  MXI2XLHVT g361(.A (i_data_b[1]), .B (n_6), .S0 (i_data_a[1]), .Y
       (n_1));
  MXI2XLHVT g362(.A (i_data_b[3]), .B (n_4), .S0 (i_data_a[3]), .Y
       (n_0));
endmodule

module COMP_4bit(i_data_a, i_data_b, o_less, o_equal);
  input [3:0] i_data_a, i_data_b;
  output o_less, o_equal;
  wire [3:0] i_data_a, i_data_b;
  wire o_less, o_equal;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11;
  assign o_equal = 1'b0;
  OAI21X1HVT g1661(.A0 (n_9), .A1 (n_11), .B0 (n_10), .Y (o_less));
  AOI21X1HVT g1662(.A0 (n_1), .A1 (n_7), .B0 (n_6), .Y (n_11));
  AOI21X1HVT g1663(.A0 (n_8), .A1 (n_0), .B0 (n_4), .Y (n_10));
  NAND2X1HVT g1664(.A (n_5), .B (n_0), .Y (n_9));
  NOR2X1HVT g1665(.A (i_data_a[2]), .B (n_3), .Y (n_8));
  NAND2X1HVT g1666(.A (i_data_a[1]), .B (n_2), .Y (n_7));
  NOR2X1HVT g1667(.A (i_data_a[1]), .B (n_2), .Y (n_6));
  NAND2X1HVT g1668(.A (i_data_a[2]), .B (n_3), .Y (n_5));
  NOR2BX1HVT g1669(.AN (i_data_b[3]), .B (i_data_a[3]), .Y (n_4));
  INVX1HVT g1674(.A (i_data_b[2]), .Y (n_3));
  INVX2HVT g1675(.A (i_data_b[1]), .Y (n_2));
  NOR2BX1HVT g2(.AN (i_data_b[0]), .B (i_data_a[0]), .Y (n_1));
  NAND2BX1HVT g1676(.AN (i_data_b[3]), .B (i_data_a[3]), .Y (n_0));
endmodule

module COMP_8bit_SIZE_DATA8(i_data_a, i_data_b, o_less);
  input [7:0] i_data_a, i_data_b;
  output o_less;
  wire [7:0] i_data_a, i_data_b;
  wire o_less;
  wire w_equal_high, w_equal_low, w_less_high, w_less_low;
  COMP_4bit_1 u_high(.i_data_a (i_data_a[7:4]), .i_data_b
       (i_data_b[7:4]), .o_less (w_less_high), .o_equal (w_equal_high));
  COMP_4bit u_low(.i_data_a (i_data_a[3:0]), .i_data_b (i_data_b[3:0]),
       .o_less (w_less_low), .o_equal (w_equal_low));
  AO21X4HVT g2(.A0 (w_equal_high), .A1 (w_less_low), .B0 (w_less_high),
       .Y (o_less));
endmodule

module COMP_4bit_3(i_data_a, i_data_b, o_less, o_equal);
  input [3:0] i_data_a, i_data_b;
  output o_less, o_equal;
  wire [3:0] i_data_a, i_data_b;
  wire o_less, o_equal;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_13;
  NAND2X1HVT g308(.A (n_5), .B (n_13), .Y (o_less));
  OAI211X1HVT g309(.A0 (i_data_b[1]), .A1 (n_4), .B0 (n_9), .C0 (n_8),
       .Y (n_13));
  NOR2X1HVT g310(.A (n_11), .B (n_10), .Y (o_equal));
  NAND2X1HVT g311(.A (i_data_b[3]), .B (n_3), .Y (n_11));
  NAND2X1HVT g312(.A (n_7), .B (n_2), .Y (n_10));
  NOR2BX1HVT g313(.AN (i_data_b[3]), .B (n_6), .Y (n_9));
  OAI21X1HVT g314(.A0 (i_data_a[0]), .A1 (n_0), .B0 (i_data_a[1]), .Y
       (n_8));
  ADDHX1HVT g315(.A (i_data_a[2]), .B (n_1), .CO (n_6), .S (n_7));
  NAND3BXLHVT g316(.AN (i_data_a[2]), .B (i_data_b[3]), .C
       (i_data_b[2]), .Y (n_5));
  NOR3X1HVT g317(.A (i_data_a[1]), .B (i_data_a[0]), .C (n_0), .Y
       (n_4));
  MXI2XLHVT g318(.A (i_data_b[0]), .B (n_0), .S0 (i_data_a[0]), .Y
       (n_3));
  XNOR2X1HVT g319(.A (i_data_a[1]), .B (i_data_b[1]), .Y (n_2));
  INVX1HVT g320(.A (i_data_b[2]), .Y (n_1));
  INVX1HVT g321(.A (i_data_b[0]), .Y (n_0));
endmodule

module COMP_4bit_2(i_data_a, i_data_b, o_less, o_equal);
  input [3:0] i_data_a, i_data_b;
  output o_less, o_equal;
  wire [3:0] i_data_a, i_data_b;
  wire o_less, o_equal;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10;
  assign o_equal = 1'b0;
  NOR2X1HVT g248(.A (n_7), .B (n_9), .Y (n_10));
  NOR2X1HVT g249(.A (n_8), .B (n_4), .Y (n_9));
  AOI22X1HVT g250(.A0 (n_6), .A1 (n_5), .B0 (n_2), .B1 (i_data_b[1]),
       .Y (n_8));
  NOR2BX1HVT g251(.AN (i_data_b[2]), .B (i_data_a[2]), .Y (n_7));
  OR2XLHVT g252(.A (n_2), .B (i_data_b[1]), .Y (n_6));
  NOR2BX1HVT g253(.AN (i_data_b[0]), .B (i_data_a[0]), .Y (n_5));
  NOR2BX1HVT g254(.AN (i_data_a[2]), .B (i_data_b[2]), .Y (n_4));
  NOR2BX1HVT g255(.AN (i_data_a[3]), .B (i_data_b[3]), .Y (n_3));
  INVX1HVT g257(.A (i_data_a[1]), .Y (n_2));
  OAI21X1HVT g2(.A0 (n_3), .A1 (n_10), .B0 (n_1), .Y (o_less));
  NAND2BXLHVT g3(.AN (i_data_a[3]), .B (i_data_b[3]), .Y (n_1));
endmodule

module COMP_8bit_SIZE_DATA8_1(i_data_a, i_data_b, o_less);
  input [7:0] i_data_a, i_data_b;
  output o_less;
  wire [7:0] i_data_a, i_data_b;
  wire o_less;
  wire w_equal_high, w_equal_low, w_less_high, w_less_low;
  COMP_4bit_3 u_high(.i_data_a ({1'b1, i_data_a[6:4]}), .i_data_b
       (i_data_b[7:4]), .o_less (w_less_high), .o_equal (w_equal_high));
  COMP_4bit_2 u_low(.i_data_a (i_data_a[3:0]), .i_data_b
       (i_data_b[3:0]), .o_less (w_less_low), .o_equal (w_equal_low));
  AO21X1HVT g16(.A0 (w_equal_high), .A1 (w_less_low), .B0
       (w_less_high), .Y (o_less));
endmodule

module CLA_4bit_2(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_0, n_1, n_2, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_15, n_16, n_17;
  wire n_18, n_19, n_22, n_24;
  XNOR2X1HVT g285(.A (n_11), .B (n_24), .Y (sum[3]));
  OAI21X1HVT g286(.A0 (n_9), .A1 (n_22), .B0 (n_6), .Y (n_24));
  XOR2XLHVT g287(.A (n_9), .B (n_22), .Y (sum[2]));
  AOI21X1HVT g288(.A0 (n_12), .A1 (n_18), .B0 (n_7), .Y (n_22));
  OAI21X2HVT g289(.A0 (n_11), .A1 (n_17), .B0 (n_19), .Y (o_g));
  XOR2XLHVT g290(.A (n_12), .B (n_18), .Y (sum[1]));
  OAI21X2HVT g291(.A0 (n_2), .A1 (o_p), .B0 (cin), .Y (n_19));
  NOR2BX1HVT g292(.AN (n_6), .B (n_16), .Y (n_17));
  OAI2BB1X1HVT g293(.A0N (cin), .A1N (n_0), .B0 (n_8), .Y (n_18));
  NOR2X1HVT g294(.A (n_9), .B (n_15), .Y (n_16));
  NOR2X1HVT g295(.A (n_7), .B (n_13), .Y (n_15));
  XOR2XLHVT g296(.A (cin), .B (n_0), .Y (sum[0]));
  NOR2X1HVT g298(.A (n_8), .B (n_10), .Y (n_13));
  INVX1HVT g299(.A (n_10), .Y (n_12));
  XNOR2X1HVT g301(.A (n_2), .B (cin), .Y (n_11));
  XNOR2X1HVT g302(.A (a[1]), .B (b[1]), .Y (n_10));
  XNOR2X1HVT g304(.A (a[2]), .B (b[2]), .Y (n_9));
  NAND2XLHVT g305(.A (a[0]), .B (b[0]), .Y (n_8));
  AND2XLHVT g306(.A (a[1]), .B (b[1]), .Y (n_7));
  NAND2X1HVT g307(.A (a[2]), .B (b[2]), .Y (n_6));
  XNOR2XLHVT g303_dup(.A (a[0]), .B (b[0]), .Y (n_5));
  NOR3X1HVT g2(.A (n_4), .B (n_9), .C (n_5), .Y (o_p));
  OR2X1HVT g3(.A (n_11), .B (n_10), .Y (n_4));
  INVX1HVT drc_bufs(.A (n_1), .Y (n_2));
  INVX1HVT drc_bufs310(.A (a[3]), .Y (n_1));
  XOR2XLHVT g312(.A (b[0]), .B (a[0]), .Y (n_0));
endmodule

module CLA_4bit_3(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_0, n_1, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_15, n_16;
  assign o_g = 1'b0;
  assign o_p = 1'b0;
  XOR2XLHVT g288(.A (n_8), .B (n_15), .Y (sum[3]));
  MXI2XLHVT g289(.A (n_11), .B (n_6), .S0 (n_16), .Y (sum[2]));
  XOR2XLHVT g290(.A (n_5), .B (n_0), .Y (sum[1]));
  OAI21X1HVT g291(.A0 (n_4), .A1 (n_13), .B0 (n_9), .Y (n_16));
  OAI31XLHVT g292(.A0 (n_11), .A1 (n_4), .A2 (n_13), .B0 (n_12), .Y
       (n_15));
  XNOR2X1HVT g294(.A (cin), .B (n_7), .Y (sum[0]));
  NAND2BX1HVT g295(.AN (n_7), .B (cin), .Y (n_13));
  AOI21X1HVT g296(.A0 (a[2]), .A1 (b[0]), .B0 (n_10), .Y (n_12));
  INVX1HVT g297(.A (n_6), .Y (n_11));
  INVX1HVT g298(.A (n_9), .Y (n_10));
  OAI21X1HVT g299(.A0 (a[0]), .A1 (a[1]), .B0 (b[0]), .Y (n_9));
  MXI2XLHVT g300(.A (n_3), .B (b[0]), .S0 (a[3]), .Y (n_8));
  INVX1HVT g301(.A (n_4), .Y (n_5));
  XNOR2X1HVT g302(.A (a[0]), .B (b[0]), .Y (n_7));
  MX2XLHVT g303(.A (b[0]), .B (n_3), .S0 (a[2]), .Y (n_6));
  XNOR2X1HVT g304(.A (a[1]), .B (b[0]), .Y (n_4));
  INVX1HVT g305(.A (b[0]), .Y (n_3));
  NAND2X2HVT g2(.A (n_1), .B (n_13), .Y (n_0));
  NAND2XLHVT g3(.A (a[0]), .B (b[0]), .Y (n_1));
endmodule

module CLA_8bit_1(i_carry, i_data_a, i_data_b, o_sum, o_carry);
  input i_carry;
  input [7:0] i_data_a, i_data_b;
  output [7:0] o_sum;
  output o_carry;
  wire i_carry;
  wire [7:0] i_data_a, i_data_b;
  wire [7:0] o_sum;
  wire o_carry;
  wire n_0, w_C, w_G, w_G_22, w_P, w_P_20;
  assign o_carry = 1'b0;
  CLA_4bit_2 CLA_4BIT_UNIT_0(.a (i_data_a[3:0]), .b ({1'b0,
       i_data_b[2:0]}), .cin (i_data_b[3]), .sum (o_sum[3:0]), .o_p
       (w_P), .o_g (w_G));
  CLA_4bit_3 CLA_4BIT_UNIT_1(.a (i_data_a[7:4]), .b ({3'b000,
       i_data_b[3]}), .cin (w_C), .sum (o_sum[7:4]), .o_p (w_P_20),
       .o_g (w_G_22));
  INVX3HVT g7(.A (w_G), .Y (n_0));
  OAI2BB1X1HVT g20(.A0N (i_data_b[3]), .A1N (w_P), .B0 (n_0), .Y (w_C));
endmodule

module EXP_adjust_SIZE_EXP8_SIZE_LOPD8(i_overflow, i_underflow,
     i_zero_flag, i_lopd_value, i_exp_value, o_exp_result);
  input i_overflow, i_underflow, i_zero_flag;
  input [7:0] i_lopd_value, i_exp_value;
  output [7:0] o_exp_result;
  wire i_overflow, i_underflow, i_zero_flag;
  wire [7:0] i_lopd_value, i_exp_value;
  wire [7:0] o_exp_result;
  wire [7:0] w_data_b;
  wire [7:0] w_exp_result;
  wire UNCONNECTED, n_0, n_1, w_i_carry;
  CLA_8bit_1 CLA_8BIT_UNIT(.i_carry (1'b0), .i_data_a (i_exp_value),
       .i_data_b ({4'b0000, w_i_carry, w_data_b[2:0]}), .o_sum
       (w_exp_result), .o_carry (UNCONNECTED));
  NOR2BX1HVT g143(.AN (w_i_carry), .B (i_lopd_value[2]), .Y
       (w_data_b[2]));
  NOR2BX1HVT g144(.AN (w_i_carry), .B (i_lopd_value[1]), .Y
       (w_data_b[1]));
  OAI21X1HVT g145(.A0 (i_underflow), .A1 (i_lopd_value[0]), .B0 (n_1),
       .Y (w_data_b[0]));
  NOR2X2HVT g146(.A (i_overflow), .B (i_underflow), .Y (w_i_carry));
  INVX1HVT g147(.A (i_overflow), .Y (n_1));
  NOR2BX1HVT g154(.AN (w_exp_result[4]), .B (i_zero_flag), .Y
       (o_exp_result[4]));
  AND2XLHVT g155(.A (n_0), .B (w_exp_result[6]), .Y (o_exp_result[6]));
  NOR2BX1HVT g156(.AN (w_exp_result[7]), .B (i_zero_flag), .Y
       (o_exp_result[7]));
  NOR2BX1HVT g157(.AN (w_exp_result[0]), .B (i_zero_flag), .Y
       (o_exp_result[0]));
  NOR2BX1HVT g158(.AN (w_exp_result[2]), .B (i_zero_flag), .Y
       (o_exp_result[2]));
  AND2XLHVT g159(.A (n_0), .B (w_exp_result[5]), .Y (o_exp_result[5]));
  AND2XLHVT g160(.A (n_0), .B (w_exp_result[3]), .Y (o_exp_result[3]));
  AND2XLHVT g161(.A (n_0), .B (w_exp_result[1]), .Y (o_exp_result[1]));
  INVX1HVT g162(.A (i_zero_flag), .Y (n_0));
endmodule

module LOPD_8bit(i_data, o_pos_one, o_zero_flag);
  input [7:0] i_data;
  output [2:0] o_pos_one;
  output o_zero_flag;
  wire [7:0] i_data;
  wire [2:0] o_pos_one;
  wire o_zero_flag;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_8, n_10;
  AOI2BB1XLHVT g406(.A0N (n_10), .A1N (i_data[6]), .B0 (i_data[7]), .Y
       (o_pos_one[0]));
  NOR2X1HVT g407(.A (n_8), .B (i_data[5]), .Y (n_10));
  AND2X1HVT g408(.A (o_pos_one[2]), .B (n_4), .Y (o_zero_flag));
  NOR2X1HVT g409(.A (n_5), .B (i_data[4]), .Y (n_8));
  AOI211X2HVT g410(.A0 (n_1), .A1 (n_2), .B0 (i_data[6]), .C0
       (i_data[7]), .Y (o_pos_one[1]));
  NOR3XLHVT g411(.A (n_3), .B (i_data[6]), .C (i_data[7]), .Y
       (o_pos_one[2]));
  NOR2X1HVT g412(.A (n_0), .B (i_data[3]), .Y (n_5));
  NOR3X1HVT g413(.A (i_data[0]), .B (i_data[1]), .C (n_1), .Y (n_4));
  INVX1HVT g414(.A (n_2), .Y (n_3));
  NOR2X1HVT g415(.A (i_data[4]), .B (i_data[5]), .Y (n_2));
  NOR2BX1HVT g416(.AN (i_data[1]), .B (i_data[2]), .Y (n_0));
  OR2X1HVT g417(.A (i_data[2]), .B (i_data[3]), .Y (n_1));
endmodule

module CLA_4bit(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_14, n_15, n_16, n_17;
  wire n_20, n_22;
  XNOR2X1HVT g308(.A (n_3), .B (n_22), .Y (sum[3]));
  AOI21XLHVT g309(.A0 (n_9), .A1 (n_20), .B0 (n_8), .Y (n_22));
  CLKXOR2X1HVT g310(.A (n_9), .B (n_20), .Y (sum[2]));
  OAI21X1HVT g311(.A0 (n_7), .A1 (n_17), .B0 (n_2), .Y (n_20));
  OAI2BB1XLHVT g312(.A0N (n_3), .A1N (n_16), .B0 (n_0), .Y (o_g));
  CLKXOR2X1HVT g313(.A (n_7), .B (n_17), .Y (sum[1]));
  AOI21XLHVT g314(.A0 (cin), .A1 (n_6), .B0 (n_5), .Y (n_17));
  NAND2BX1HVT g315(.AN (n_8), .B (n_15), .Y (n_16));
  NAND2X1HVT g317(.A (n_9), .B (n_14), .Y (n_15));
  OAI2BB1X1HVT g318(.A0N (n_5), .A1N (n_4), .B0 (n_2), .Y (n_14));
  CLKXOR2X1HVT g319(.A (n_6), .B (cin), .Y (sum[0]));
  NOR2X1HVT g320(.A (n_11), .B (n_10), .Y (o_p));
  NAND2X2HVT g321(.A (n_3), .B (n_6), .Y (n_11));
  NAND2X2HVT g322(.A (n_4), .B (n_9), .Y (n_10));
  INVX1HVT g323(.A (n_4), .Y (n_7));
  ADDHX1HVT g324(.A (a[2]), .B (b[2]), .CO (n_8), .S (n_9));
  ADDHX1HVT g325(.A (a[0]), .B (b[0]), .CO (n_5), .S (n_6));
  XOR2XLHVT g326(.A (a[1]), .B (b[1]), .Y (n_4));
  XOR2XLHVT g327(.A (a[3]), .B (b[3]), .Y (n_3));
  NAND2X1HVT g328(.A (a[1]), .B (b[1]), .Y (n_2));
  AOI21X1HVT g2(.A0 (cin), .A1 (o_p), .B0 (n_1), .Y (n_0));
  AND2X1HVT g3(.A (a[3]), .B (b[3]), .Y (n_1));
endmodule

module CLA_4bit_1(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_13, n_14, n_15, n_17;
  wire n_18, n_21, n_23;
  XNOR2X1HVT g349(.A (n_6), .B (n_23), .Y (sum[2]));
  AOI21X1HVT g350(.A0 (n_9), .A1 (n_1), .B0 (n_8), .Y (n_23));
  XNOR2X1HVT g351(.A (n_5), .B (n_21), .Y (sum[3]));
  AOI21X1HVT g352(.A0 (n_10), .A1 (n_3), .B0 (n_14), .Y (n_21));
  OAI2BB1X1HVT g353(.A0N (o_p), .A1N (n_0), .B0 (n_18), .Y (o_g));
  CLKXOR2X1HVT g354(.A (n_9), .B (n_2), .Y (sum[1]));
  AOI22X1HVT g355(.A0 (n_5), .A1 (n_17), .B0 (a[3]), .B1 (b[3]), .Y
       (n_18));
  NAND2X1HVT g357(.A (n_13), .B (n_15), .Y (n_17));
  NAND2BX1HVT g358(.AN (n_4), .B (n_10), .Y (n_15));
  NOR2BX1HVT g359(.AN (n_10), .B (n_11), .Y (o_p));
  INVX1HVT g360(.A (n_13), .Y (n_14));
  CLKXOR2X1HVT g361(.A (n_0), .B (n_7), .Y (sum[0]));
  AOI22X1HVT g362(.A0 (n_8), .A1 (n_6), .B0 (a[2]), .B1 (b[2]), .Y
       (n_13));
  NAND2X1HVT g363(.A (n_5), .B (n_7), .Y (n_11));
  AND2XLHVT g364(.A (n_9), .B (n_6), .Y (n_10));
  ADDHX1HVT g365(.A (a[1]), .B (b[1]), .CO (n_8), .S (n_9));
  XOR2XLHVT g366(.A (a[0]), .B (b[0]), .Y (n_7));
  CLKXOR2X1HVT g367(.A (a[2]), .B (b[2]), .Y (n_6));
  XOR2XLHVT g368(.A (a[3]), .B (b[3]), .Y (n_5));
  NAND2X1HVT g369(.A (a[0]), .B (b[0]), .Y (n_4));
  OAI2BB1XLHVT g356_dup(.A0N (n_7), .A1N (cin), .B0 (n_4), .Y (n_3));
  OAI2BB1XLHVT g371(.A0N (n_7), .A1N (cin), .B0 (n_4), .Y (n_2));
  OAI2BB1XLHVT g370_dup(.A0N (n_7), .A1N (cin), .B0 (n_4), .Y (n_1));
  BUFX2HVT fopt(.A (cin), .Y (n_0));
endmodule

module CLA_8bit(i_carry, i_data_a, i_data_b, o_sum, o_carry);
  input i_carry;
  input [7:0] i_data_a, i_data_b;
  output [7:0] o_sum;
  output o_carry;
  wire i_carry;
  wire [7:0] i_data_a, i_data_b;
  wire [7:0] o_sum;
  wire o_carry;
  wire UNCONNECTED0, n_0, n_1, n_2, n_3, w_C, w_G, w_G_22;
  wire w_P, w_P_20;
  CLA_4bit CLA_4BIT_UNIT_0(.a (i_data_a[3:0]), .b (i_data_b[3:0]), .cin
       (i_carry), .sum (o_sum[3:0]), .o_p (w_P), .o_g (w_G));
  CLA_4bit_1 CLA_4BIT_UNIT_1(.a (i_data_a[7:4]), .b (i_data_b[7:4]),
       .cin (w_C), .sum (o_sum[7:4]), .o_p (w_P_20), .o_g (w_G_22));
  OR2X1HVT g5(.A (n_3), .B (w_G), .Y (w_C));
  AND2X1HVT g6(.A (i_carry), .B (w_P), .Y (n_3));
  OR2XLHVT g21(.A (n_2), .B (w_G_22), .Y (o_carry));
  BUFX2HVT drc_bufs(.A (w_P_20), .Y (n_1));
  BUFX2HVT drc_bufs22(.A (w_C), .Y (n_0));
  ADDHX1HVT g24(.A (n_1), .B (n_0), .CO (n_2), .S (UNCONNECTED0));
endmodule

module MAN_ALU_SIZE_MAN8(i_sign_a, i_sign_b, i_carry, i_man_max,
     i_man_min, o_man_alu, o_overflow);
  input i_sign_a, i_sign_b, i_carry;
  input [7:0] i_man_max, i_man_min;
  output [7:0] o_man_alu;
  output o_overflow;
  wire i_sign_a, i_sign_b, i_carry;
  wire [7:0] i_man_max, i_man_min;
  wire [7:0] o_man_alu;
  wire o_overflow;
  wire [7:0] w_i_man_b;
  wire n_0, n_18, w_i_carry_alu, w_overflow;
  CLA_8bit ALU_SUB_UNIT(.i_carry (w_i_carry_alu), .i_data_a
       (i_man_max), .i_data_b (w_i_man_b), .o_sum (o_man_alu), .o_carry
       (w_overflow));
  NOR2BX1HVT g34(.AN (w_overflow), .B (n_18), .Y (o_overflow));
  MX2XLHVT g123(.A (n_18), .B (n_0), .S0 (i_man_min[4]), .Y
       (w_i_man_b[4]));
  MXI2XLHVT g124(.A (n_0), .B (n_18), .S0 (i_man_min[6]), .Y
       (w_i_man_b[6]));
  MX2XLHVT g125(.A (n_18), .B (n_0), .S0 (i_man_min[7]), .Y
       (w_i_man_b[7]));
  MXI2XLHVT g126(.A (n_0), .B (n_18), .S0 (i_man_min[0]), .Y
       (w_i_man_b[0]));
  MXI2XLHVT g127(.A (n_0), .B (n_18), .S0 (i_man_min[2]), .Y
       (w_i_man_b[2]));
  MXI2XLHVT g128(.A (n_0), .B (n_18), .S0 (i_man_min[5]), .Y
       (w_i_man_b[5]));
  MX2XLHVT g129(.A (n_18), .B (n_0), .S0 (i_man_min[3]), .Y
       (w_i_man_b[3]));
  MX2XLHVT g130(.A (n_18), .B (n_0), .S0 (i_man_min[1]), .Y
       (w_i_man_b[1]));
  NOR2XLHVT g131(.A (n_0), .B (i_carry), .Y (w_i_carry_alu));
  INVX1HVT g132(.A (n_0), .Y (n_18));
  XNOR2X1HVT g133(.A (i_sign_b), .B (i_sign_a), .Y (n_0));
endmodule

module SHF_left_SIZE_DATA8_SIZE_SHIFT3(i_shift_number, i_data, o_data);
  input [2:0] i_shift_number;
  input [7:0] i_data;
  output [7:0] o_data;
  wire [2:0] i_shift_number;
  wire [7:0] i_data;
  wire [7:0] o_data;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18;
  assign o_data[7] = 1'b0;
  OAI222X1HVT g401(.A0 (n_11), .A1 (n_15), .B0 (n_10), .B1 (n_2), .C0
       (n_17), .C1 (n_12), .Y (o_data[6]));
  NOR2XLHVT g402(.A (i_shift_number[2]), .B (n_3), .Y (o_data[2]));
  OAI222X1HVT g403(.A0 (n_11), .A1 (n_17), .B0 (n_4), .B1 (n_12), .C0
       (n_13), .C1 (n_14), .Y (o_data[4]));
  OAI222X1HVT g404(.A0 (n_11), .A1 (n_16), .B0 (n_14), .B1 (n_1), .C0
       (n_18), .C1 (n_12), .Y (o_data[5]));
  OAI22X1HVT g406(.A0 (n_11), .A1 (n_18), .B0 (n_0), .B1 (n_12), .Y
       (o_data[3]));
  NOR2X1HVT g407(.A (n_11), .B (n_1), .Y (o_data[1]));
  NOR2X1HVT g408(.A (n_13), .B (n_11), .Y (o_data[0]));
  AOI22XLHVT g411(.A0 (i_data[5]), .A1 (n_6), .B0 (i_data[4]), .B1
       (n_8), .Y (n_16));
  AOI22XLHVT g412(.A0 (i_data[6]), .A1 (n_6), .B0 (i_data[5]), .B1
       (n_8), .Y (n_15));
  AOI22XLHVT g413(.A0 (i_data[3]), .A1 (n_6), .B0 (i_data[2]), .B1
       (n_8), .Y (n_18));
  AOI22XLHVT g414(.A0 (i_data[4]), .A1 (n_6), .B0 (i_data[3]), .B1
       (n_8), .Y (n_17));
  NAND2BXLHVT g415(.AN (i_shift_number[1]), .B (i_shift_number[2]), .Y
       (n_14));
  NAND2XLHVT g416(.A (i_data[0]), .B (n_9), .Y (n_13));
  NAND2X1HVT g417(.A (i_shift_number[1]), .B (n_10), .Y (n_12));
  NAND2BX1HVT g418(.AN (i_shift_number[1]), .B (n_10), .Y (n_11));
  INVX1HVT g419(.A (i_shift_number[2]), .Y (n_10));
  INVX1HVT g420(.A (i_shift_number[0]), .Y (n_9));
  BUFX2HVT fopt(.A (n_7), .Y (n_8));
  BUFX2HVT fopt421(.A (i_shift_number[0]), .Y (n_7));
  BUFX3HVT fopt422(.A (n_9), .Y (n_6));
  AOI21X2HVT g2(.A0 (i_data[2]), .A1 (n_9), .B0 (n_5), .Y (n_4));
  AND2X1HVT g3(.A (i_data[1]), .B (n_7), .Y (n_5));
  MX2XLHVT g423(.A (n_4), .B (n_13), .S0 (i_shift_number[1]), .Y (n_3));
  MX2XLHVT g405_dup(.A (n_4), .B (n_13), .S0 (i_shift_number[1]), .Y
       (n_2));
  AOI22XLHVT g425(.A0 (i_data[1]), .A1 (n_6), .B0 (i_data[0]), .B1
       (n_8), .Y (n_1));
  AOI22XLHVT g410_dup(.A0 (i_data[1]), .A1 (n_6), .B0 (i_data[0]), .B1
       (n_8), .Y (n_0));
endmodule

module NOR_unit_SIZE_LOPD3_SIZE_DATA8(i_overflow, i_zero_flag,
     i_one_position, i_mantissa, o_mantissa);
  input i_overflow, i_zero_flag;
  input [2:0] i_one_position;
  input [7:0] i_mantissa;
  output [7:0] o_mantissa;
  wire i_overflow, i_zero_flag;
  wire [2:0] i_one_position;
  wire [7:0] i_mantissa;
  wire [7:0] o_mantissa;
  wire [7:0] w_shift_left;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10;
  assign o_mantissa[7] = 1'b0;
  SHF_left_SIZE_DATA8_SIZE_SHIFT3 SHF_left_unit(.i_shift_number
       (i_one_position), .i_data ({1'b0, i_mantissa[6:0]}), .o_data
       (w_shift_left));
  OAI2BB1X1HVT g423(.A0N (n_3), .A1N (w_shift_left[5]), .B0 (n_6), .Y
       (o_mantissa[5]));
  OAI2BB1X1HVT g424(.A0N (n_3), .A1N (w_shift_left[4]), .B0 (n_8), .Y
       (o_mantissa[4]));
  OAI2BB1X1HVT g425(.A0N (n_3), .A1N (w_shift_left[2]), .B0 (n_9), .Y
       (o_mantissa[2]));
  OAI2BB1X1HVT g426(.A0N (n_3), .A1N (w_shift_left[1]), .B0 (n_7), .Y
       (o_mantissa[1]));
  OAI2BB1X1HVT g427(.A0N (n_3), .A1N (w_shift_left[3]), .B0 (n_10), .Y
       (o_mantissa[3]));
  OAI2BB1X1HVT g428(.A0N (n_3), .A1N (w_shift_left[0]), .B0 (n_5), .Y
       (o_mantissa[0]));
  OAI2BB1X1HVT g429(.A0N (n_3), .A1N (w_shift_left[6]), .B0 (n_4), .Y
       (o_mantissa[6]));
  AOI22X1HVT g430(.A0 (i_mantissa[3]), .A1 (n_2), .B0 (i_mantissa[4]),
       .B1 (n_0), .Y (n_10));
  AOI22X1HVT g431(.A0 (i_mantissa[2]), .A1 (n_2), .B0 (i_mantissa[3]),
       .B1 (n_0), .Y (n_9));
  AOI22X1HVT g432(.A0 (i_mantissa[4]), .A1 (n_2), .B0 (i_mantissa[5]),
       .B1 (n_0), .Y (n_8));
  AOI22X1HVT g433(.A0 (i_mantissa[1]), .A1 (n_2), .B0 (i_mantissa[2]),
       .B1 (n_0), .Y (n_7));
  AOI22X1HVT g434(.A0 (i_mantissa[5]), .A1 (n_2), .B0 (i_mantissa[6]),
       .B1 (n_0), .Y (n_6));
  AOI22X1HVT g435(.A0 (i_mantissa[0]), .A1 (n_2), .B0 (i_mantissa[1]),
       .B1 (n_0), .Y (n_5));
  OAI21X1HVT g436(.A0 (n_1), .A1 (n_0), .B0 (i_mantissa[7]), .Y (n_4));
  NOR3X1HVT g437(.A (i_overflow), .B (i_mantissa[7]), .C (i_zero_flag),
       .Y (n_3));
  NOR3BX1HVT g438(.AN (i_mantissa[7]), .B (i_overflow), .C
       (i_zero_flag), .Y (n_2));
  NOR2BX1HVT g439(.AN (i_mantissa[6]), .B (i_zero_flag), .Y (n_1));
  NOR2BX1HVT g440(.AN (i_overflow), .B (i_zero_flag), .Y (n_0));
endmodule

module PSC_unit(i_sign_a, i_exp_a, i_man_a, i_sign_b, i_exp_b, i_man_b,
     o_sel_exp, o_sel_man);
  input i_sign_a, i_sign_b;
  input [7:0] i_exp_a, i_exp_b;
  input [23:0] i_man_a, i_man_b;
  output o_sel_exp;
  output [1:0] o_sel_man;
  wire i_sign_a, i_sign_b;
  wire [7:0] i_exp_a, i_exp_b;
  wire [23:0] i_man_a, i_man_b;
  wire o_sel_exp;
  wire [1:0] o_sel_man;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_24;
  wire n_25;
  assign o_sel_man[1] = 1'b0;
  OAI22X1HVT g466(.A0 (n_18), .A1 (n_25), .B0 (n_20), .B1 (n_24), .Y
       (o_sel_man[0]));
  AOI211XLHVT g467(.A0 (n_4), .A1 (n_19), .B0 (n_17), .C0 (n_22), .Y
       (n_25));
  NOR4X1HVT g468(.A (i_man_a[0]), .B (n_0), .C (n_9), .D (n_21), .Y
       (n_24));
  NAND2X1HVT g469(.A (n_18), .B (n_20), .Y (o_sel_exp));
  NAND4X1HVT g470(.A (n_12), .B (n_1), .C (n_2), .D (n_8), .Y (n_22));
  NAND4X1HVT g471(.A (n_10), .B (n_11), .C (n_3), .D (n_5), .Y (n_21));
  INVX1HVT g472(.A (n_19), .Y (n_20));
  NOR2X1HVT g473(.A (n_14), .B (n_13), .Y (n_19));
  NAND2X1HVT g474(.A (n_6), .B (n_7), .Y (n_17));
  OR2X1HVT g475(.A (n_16), .B (n_15), .Y (n_18));
  NAND4X1HVT g476(.A (i_exp_b[0]), .B (i_exp_b[1]), .C (i_exp_b[2]), .D
       (i_exp_b[3]), .Y (n_16));
  NAND4X1HVT g477(.A (i_exp_b[4]), .B (i_exp_b[5]), .C (i_exp_b[6]), .D
       (i_exp_b[7]), .Y (n_15));
  NAND4X1HVT g478(.A (i_exp_a[0]), .B (i_exp_a[1]), .C (i_exp_a[2]), .D
       (i_exp_a[3]), .Y (n_14));
  NAND4X1HVT g479(.A (i_exp_a[4]), .B (i_exp_a[5]), .C (i_exp_a[6]), .D
       (i_exp_a[7]), .Y (n_13));
  NOR3X1HVT g480(.A (i_man_b[21]), .B (i_man_b[22]), .C (i_man_b[4]),
       .Y (n_12));
  NOR4X1HVT g481(.A (i_man_a[19]), .B (i_man_a[20]), .C (i_man_a[21]),
       .D (i_man_a[22]), .Y (n_11));
  NOR4X1HVT g482(.A (i_man_a[7]), .B (i_man_a[8]), .C (i_man_a[9]), .D
       (i_man_a[10]), .Y (n_10));
  OR4X1HVT g483(.A (i_man_a[1]), .B (i_man_a[2]), .C (i_man_a[3]), .D
       (i_man_a[4]), .Y (n_9));
  NOR4X1HVT g484(.A (i_man_b[17]), .B (i_man_b[18]), .C (i_man_b[19]),
       .D (i_man_b[20]), .Y (n_8));
  NOR4X1HVT g485(.A (i_man_b[11]), .B (i_man_b[12]), .C (i_man_b[13]),
       .D (i_man_b[14]), .Y (n_7));
  NOR4X1HVT g486(.A (i_man_b[7]), .B (i_man_b[8]), .C (i_man_b[9]), .D
       (i_man_b[10]), .Y (n_6));
  NOR4X1HVT g487(.A (i_man_a[15]), .B (i_man_a[16]), .C (i_man_a[17]),
       .D (i_man_a[18]), .Y (n_5));
  XOR2XLHVT g488(.A (i_sign_b), .B (i_sign_a), .Y (n_4));
  NOR4X1HVT g489(.A (i_man_a[11]), .B (i_man_a[12]), .C (i_man_a[13]),
       .D (i_man_a[14]), .Y (n_3));
  NOR4X1HVT g490(.A (i_man_b[2]), .B (i_man_b[3]), .C (i_man_b[15]), .D
       (i_man_b[16]), .Y (n_2));
  NOR4X1HVT g491(.A (i_man_b[0]), .B (i_man_b[1]), .C (i_man_b[5]), .D
       (i_man_b[6]), .Y (n_1));
  OR2XLHVT g492(.A (i_man_a[5]), .B (i_man_a[6]), .Y (n_0));
endmodule

module SHF_right_SIZE_DATA16_SIZE_SHIFT4(i_shift_number, i_data,
     o_data);
  input [3:0] i_shift_number;
  input [15:0] i_data;
  output [15:0] o_data;
  wire [3:0] i_shift_number;
  wire [15:0] i_data;
  wire [15:0] o_data;
  wire n_0, n_1, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_29, n_30;
  assign o_data[0] = 1'b0;
  assign o_data[1] = 1'b0;
  assign o_data[2] = 1'b0;
  assign o_data[3] = 1'b0;
  assign o_data[4] = 1'b0;
  assign o_data[5] = 1'b0;
  assign o_data[6] = 1'b0;
  NOR2X1HVT g993(.A (i_shift_number[3]), .B (n_30), .Y (o_data[9]));
  NOR2X1HVT g994(.A (i_shift_number[3]), .B (n_29), .Y (o_data[8]));
  OAI222X1HVT g995(.A0 (n_24), .A1 (n_7), .B0 (n_25), .B1 (n_0), .C0
       (n_16), .C1 (n_5), .Y (o_data[7]));
  OAI2BB1X1HVT g996(.A0N (n_22), .A1N (n_8), .B0 (n_1), .Y
       (o_data[10]));
  OAI22X1HVT g997(.A0 (n_25), .A1 (n_7), .B0 (n_6), .B1 (n_0), .Y
       (o_data[11]));
  MXI2XLHVT g998(.A (n_21), .B (n_23), .S0 (i_shift_number[2]), .Y
       (n_30));
  MX3XLHVT g999(.A (n_15), .B (n_11), .C (n_26), .S0
       (i_shift_number[1]), .S1 (i_shift_number[2]), .Y (n_29));
  NOR2X1HVT g1000(.A (n_26), .B (n_7), .Y (o_data[12]));
  NOR2BX1HVT g1001(.AN (n_23), .B (n_7), .Y (o_data[13]));
  AOI32X1HVT g1002(.A0 (i_data[8]), .A1 (i_shift_number[0]), .A2 (n_3),
       .B0 (n_14), .B1 (i_shift_number[1]), .Y (n_24));
  MX2XLHVT g1003(.A (n_12), .B (n_9), .S0 (i_shift_number[1]), .Y
       (n_26));
  MX2XLHVT g1004(.A (n_17), .B (n_10), .S0 (i_shift_number[1]), .Y
       (n_25));
  OAI22X1HVT g1005(.A0 (n_11), .A1 (i_shift_number[1]), .B0 (n_12), .B1
       (n_3), .Y (n_22));
  OAI22X1HVT g1006(.A0 (n_13), .A1 (i_shift_number[1]), .B0 (n_17), .B1
       (n_3), .Y (n_21));
  OAI22X1HVT g1007(.A0 (n_10), .A1 (i_shift_number[1]), .B0
       (i_shift_number[0]), .B1 (n_3), .Y (n_23));
  AND2X1HVT g1009(.A (n_18), .B (n_8), .Y (o_data[14]));
  NOR2X1HVT g1010(.A (n_16), .B (i_shift_number[3]), .Y (o_data[15]));
  AOI22X1HVT g1011(.A0 (i_data[8]), .A1 (n_4), .B0 (i_data[9]), .B1
       (i_shift_number[0]), .Y (n_15));
  NOR2X1HVT g1012(.A (n_9), .B (i_shift_number[1]), .Y (n_18));
  AOI22X1HVT g1013(.A0 (i_data[11]), .A1 (n_4), .B0 (i_data[12]), .B1
       (i_shift_number[0]), .Y (n_17));
  OR2X1HVT g1014(.A (i_shift_number[2]), .B (n_6), .Y (n_16));
  INVX1HVT g1015(.A (n_13), .Y (n_14));
  AOI22X1HVT g1016(.A0 (i_data[9]), .A1 (n_4), .B0 (i_data[10]), .B1
       (i_shift_number[0]), .Y (n_13));
  AOI22X1HVT g1017(.A0 (i_data[12]), .A1 (n_4), .B0 (i_data[13]), .B1
       (i_shift_number[0]), .Y (n_12));
  AOI22X1HVT g1018(.A0 (i_data[10]), .A1 (n_4), .B0 (i_data[11]), .B1
       (i_shift_number[0]), .Y (n_11));
  AOI22X1HVT g1019(.A0 (i_data[13]), .A1 (n_4), .B0 (i_data[14]), .B1
       (i_shift_number[0]), .Y (n_10));
  INVX1HVT g1020(.A (n_8), .Y (n_7));
  NOR2X1HVT g1021(.A (i_data[14]), .B (i_shift_number[0]), .Y (n_9));
  NOR2X1HVT g1022(.A (i_shift_number[2]), .B (i_shift_number[3]), .Y
       (n_8));
  NAND2X1HVT g1024(.A (n_4), .B (n_3), .Y (n_6));
  INVX1HVT g1026(.A (i_shift_number[3]), .Y (n_5));
  INVX1HVT g1028(.A (i_shift_number[0]), .Y (n_4));
  INVX1HVT g1029(.A (i_shift_number[1]), .Y (n_3));
  NAND2BX1HVT g2(.AN (n_0), .B (n_18), .Y (n_1));
  NAND2BX1HVT g1030(.AN (i_shift_number[3]), .B (i_shift_number[2]), .Y
       (n_0));
endmodule

module SIGN_unit(i_comp_man, i_sign_man_a, i_sign_man_b, o_sign_s);
  input i_comp_man, i_sign_man_a, i_sign_man_b;
  output o_sign_s;
  wire i_comp_man, i_sign_man_a, i_sign_man_b;
  wire o_sign_s;
  wire n_0, n_2;
  MX2X1HVT g23(.A (i_sign_man_a), .B (i_sign_man_b), .S0 (i_comp_man),
       .Y (n_2));
  BUFX6HVT drc_bufs(.A (n_2), .Y (n_0));
  CLKBUFX20HVT drc_bufs24(.A (n_0), .Y (o_sign_s));
endmodule

module CLA_4bit_4(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_1, n_2, n_3, n_4, n_5, n_7, n_8, n_9;
  wire n_10, n_12, n_14;
  assign o_g = 1'b0;
  assign o_p = 1'b0;
  CLKXOR2X1HVT g202(.A (n_7), .B (n_14), .Y (sum[3]));
  AOI2BB1XLHVT g203(.A0N (n_5), .A1N (n_12), .B0 (n_2), .Y (n_14));
  CLKXOR2X1HVT g204(.A (n_5), .B (n_12), .Y (sum[2]));
  AOI21X1HVT g205(.A0 (n_10), .A1 (n_8), .B0 (n_9), .Y (n_12));
  CLKXOR2X1HVT g206(.A (n_10), .B (n_8), .Y (sum[1]));
  ADDHX1HVT g207(.A (a[1]), .B (b[1]), .CO (n_9), .S (n_10));
  NAND2X2HVT g208(.A (n_1), .B (sum[0]), .Y (n_8));
  XNOR2X1HVT g209(.A (a[3]), .B (b[3]), .Y (n_7));
  NOR2X4HVT g210(.A (n_4), .B (n_3), .Y (sum[0]));
  XNOR2X1HVT g211(.A (a[2]), .B (b[2]), .Y (n_5));
  NOR2X1HVT g212(.A (a[0]), .B (n_1), .Y (n_4));
  NOR2BX1HVT g213(.AN (a[0]), .B (b[0]), .Y (n_3));
  AND2XLHVT g214(.A (a[2]), .B (b[2]), .Y (n_2));
  INVX1HVT g215(.A (b[0]), .Y (n_1));
endmodule

module CLA_8bit_2(i_carry, i_data_a, i_data_b, o_sum, o_carry);
  input i_carry;
  input [7:0] i_data_a, i_data_b;
  output [7:0] o_sum;
  output o_carry;
  wire i_carry;
  wire [7:0] i_data_a, i_data_b;
  wire [7:0] o_sum;
  wire o_carry;
  wire w_G, w_P;
  assign o_carry = 1'b0;
  assign o_sum[4] = 1'b0;
  assign o_sum[5] = 1'b0;
  assign o_sum[6] = 1'b0;
  assign o_sum[7] = 1'b0;
  CLA_4bit_4 CLA_4BIT_UNIT_0(.a (i_data_a[3:0]), .b (i_data_b[3:0]),
       .cin (1'b1), .sum (o_sum[3:0]), .o_p (w_P), .o_g (w_G));
endmodule

module SWAP_unit_SIZE_DATA8(i_comp_less, i_data_a, i_data_b,
     o_data_max, o_data_min);
  input i_comp_less;
  input [7:0] i_data_a, i_data_b;
  output [7:0] o_data_max, o_data_min;
  wire i_comp_less;
  wire [7:0] i_data_a, i_data_b;
  wire [7:0] o_data_max, o_data_min;
  assign o_data_min[4] = 1'b0;
  assign o_data_min[5] = 1'b0;
  assign o_data_min[6] = 1'b0;
  assign o_data_min[7] = 1'b0;
  MX2XLHVT g201(.A (i_data_a[7]), .B (i_data_b[7]), .S0 (i_comp_less),
       .Y (o_data_max[7]));
  MX2XLHVT g202(.A (i_data_a[4]), .B (i_data_b[4]), .S0 (i_comp_less),
       .Y (o_data_max[4]));
  MX2XLHVT g203(.A (i_data_a[1]), .B (i_data_b[1]), .S0 (i_comp_less),
       .Y (o_data_max[1]));
  MX2XLHVT g204(.A (i_data_a[0]), .B (i_data_b[0]), .S0 (i_comp_less),
       .Y (o_data_max[0]));
  MX2XLHVT g205(.A (i_data_a[3]), .B (i_data_b[3]), .S0 (i_comp_less),
       .Y (o_data_max[3]));
  MX2XLHVT g206(.A (i_data_b[3]), .B (i_data_a[3]), .S0 (i_comp_less),
       .Y (o_data_min[3]));
  MX2XLHVT g207(.A (i_data_b[2]), .B (i_data_a[2]), .S0 (i_comp_less),
       .Y (o_data_min[2]));
  MX2XLHVT g208(.A (i_data_a[6]), .B (i_data_b[6]), .S0 (i_comp_less),
       .Y (o_data_max[6]));
  MX2XLHVT g209(.A (i_data_a[5]), .B (i_data_b[5]), .S0 (i_comp_less),
       .Y (o_data_max[5]));
  MX2XLHVT g210(.A (i_data_b[1]), .B (i_data_a[1]), .S0 (i_comp_less),
       .Y (o_data_min[1]));
  MX2X1HVT g211(.A (i_data_a[2]), .B (i_data_b[2]), .S0 (i_comp_less),
       .Y (o_data_max[2]));
  MX2XLHVT g212(.A (i_data_b[0]), .B (i_data_a[0]), .S0 (i_comp_less),
       .Y (o_data_min[0]));
endmodule

module SWAP_unit_SIZE_DATA8_1(i_comp_less, i_data_a, i_data_b,
     o_data_max, o_data_min);
  input i_comp_less;
  input [7:0] i_data_a, i_data_b;
  output [7:0] o_data_max, o_data_min;
  wire i_comp_less;
  wire [7:0] i_data_a, i_data_b;
  wire [7:0] o_data_max, o_data_min;
  assign o_data_min[7] = 1'b1;
  assign o_data_max[7] = 1'b1;
  MX2XLHVT g226(.A (i_data_b[5]), .B (i_data_a[5]), .S0 (i_comp_less),
       .Y (o_data_min[5]));
  MX2X1HVT g227(.A (i_data_a[5]), .B (i_data_b[5]), .S0 (i_comp_less),
       .Y (o_data_max[5]));
  MX2XLHVT g228(.A (i_data_a[3]), .B (i_data_b[3]), .S0 (i_comp_less),
       .Y (o_data_max[3]));
  MX2XLHVT g229(.A (i_data_a[0]), .B (i_data_b[0]), .S0 (i_comp_less),
       .Y (o_data_max[0]));
  MX2XLHVT g230(.A (i_data_b[6]), .B (i_data_a[6]), .S0 (i_comp_less),
       .Y (o_data_min[6]));
  MX2XLHVT g231(.A (i_data_a[2]), .B (i_data_b[2]), .S0 (i_comp_less),
       .Y (o_data_max[2]));
  MX2X1HVT g232(.A (i_data_a[6]), .B (i_data_b[6]), .S0 (i_comp_less),
       .Y (o_data_max[6]));
  MX2XLHVT g233(.A (i_data_b[0]), .B (i_data_a[0]), .S0 (i_comp_less),
       .Y (o_data_min[0]));
  MX2XLHVT g234(.A (i_data_b[3]), .B (i_data_a[3]), .S0 (i_comp_less),
       .Y (o_data_min[3]));
  MX2X1HVT g235(.A (i_data_a[4]), .B (i_data_b[4]), .S0 (i_comp_less),
       .Y (o_data_max[4]));
  MX2XLHVT g236(.A (i_data_b[2]), .B (i_data_a[2]), .S0 (i_comp_less),
       .Y (o_data_min[2]));
  MX2XLHVT g237(.A (i_data_b[1]), .B (i_data_a[1]), .S0 (i_comp_less),
       .Y (o_data_min[1]));
  MX2XLHVT g238(.A (i_data_a[1]), .B (i_data_b[1]), .S0 (i_comp_less),
       .Y (o_data_max[1]));
  MX2XLHVT g239(.A (i_data_b[4]), .B (i_data_a[4]), .S0 (i_comp_less),
       .Y (o_data_min[4]));
endmodule

module SWAP_unit_SIZE_DATA8_2(i_comp_less, i_data_a, i_data_b,
     o_data_max, o_data_min);
  input i_comp_less;
  input [7:0] i_data_a, i_data_b;
  output [7:0] o_data_max, o_data_min;
  wire i_comp_less;
  wire [7:0] i_data_a, i_data_b;
  wire [7:0] o_data_max, o_data_min;
  wire n_0, n_1, n_2, n_3;
  MX2XLHVT g227(.A (i_data_b[4]), .B (i_data_a[4]), .S0 (n_2), .Y
       (o_data_min[4]));
  MX2XLHVT g228(.A (i_data_a[5]), .B (i_data_b[5]), .S0 (n_2), .Y
       (o_data_max[5]));
  MX2XLHVT g229(.A (i_data_a[3]), .B (i_data_b[3]), .S0 (n_1), .Y
       (o_data_max[3]));
  MX2XLHVT g230(.A (i_data_a[0]), .B (i_data_b[0]), .S0 (n_1), .Y
       (o_data_max[0]));
  MX2XLHVT g231(.A (i_data_b[6]), .B (i_data_a[6]), .S0 (n_2), .Y
       (o_data_min[6]));
  MX2XLHVT g232(.A (i_data_b[5]), .B (i_data_a[5]), .S0 (n_2), .Y
       (o_data_min[5]));
  MX2XLHVT g233(.A (i_data_a[6]), .B (i_data_b[6]), .S0 (n_2), .Y
       (o_data_max[6]));
  MX2XLHVT g234(.A (i_data_b[0]), .B (i_data_a[0]), .S0 (i_comp_less),
       .Y (o_data_min[0]));
  MX2XLHVT g235(.A (i_data_a[2]), .B (i_data_b[2]), .S0 (n_1), .Y
       (o_data_max[2]));
  MX2XLHVT g236(.A (i_data_b[3]), .B (i_data_a[3]), .S0 (n_3), .Y
       (o_data_min[3]));
  MX2XLHVT g237(.A (i_data_b[2]), .B (i_data_a[2]), .S0 (n_3), .Y
       (o_data_min[2]));
  MX2XLHVT g238(.A (i_data_b[1]), .B (i_data_a[1]), .S0 (i_comp_less),
       .Y (o_data_min[1]));
  MX2XLHVT g239(.A (i_data_a[1]), .B (i_data_b[1]), .S0 (n_1), .Y
       (o_data_max[1]));
  MX2XLHVT g240(.A (i_data_a[4]), .B (i_data_b[4]), .S0 (n_2), .Y
       (o_data_max[4]));
  NAND2BXLHVT g241(.AN (i_data_b[7]), .B (n_2), .Y (o_data_max[7]));
  OR2XLHVT g242(.A (i_data_b[7]), .B (n_2), .Y (o_data_min[7]));
  INVX1HVT fopt244(.A (n_0), .Y (n_3));
  BUFX3HVT fopt247(.A (n_1), .Y (n_2));
  INVX1HVT fopt248(.A (n_0), .Y (n_1));
  INVX1HVT fopt249(.A (i_comp_less), .Y (n_0));
endmodule

module BFP16_add(i_data_a, i_data_b, o_bfu_add);
  input [31:0] i_data_a, i_data_b;
  output [31:0] o_bfu_add;
  wire [31:0] i_data_a, i_data_b;
  wire [31:0] o_bfu_add;
  wire [7:0] w_swap_man0_max;
  wire [15:0] w_shf_right_man1_min;
  wire [7:0] w_alu_man_result;
  wire [2:0] w_lopd_one_pos;
  wire [7:0] w_swap_exp_max;
  wire [7:0] w_exp_adjust;
  wire [7:0] w_swap_man1_max;
  wire [7:0] w_swap_man1_min;
  wire [7:0] w_nor_man;
  wire [1:0] w_sel_man;
  wire [7:0] w_sub_exp_result;
  wire [7:0] w_swap_man0_min;
  wire [7:0] w_swap_exp_min;
  wire UNCONNECTED1, UNCONNECTED2, UNCONNECTED3, UNCONNECTED4, n_0,
       n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_71, n_72, n_73, n_74, n_75;
  wire n_78, w_alu_man_overflow, w_comp_exp_less, w_comp_man_less,
       w_lopd_zero_flag, w_sel_exp;
  COMP_8bit_SIZE_DATA8 COMP_EXP_UNIT(.i_data_a (i_data_a[30:23]),
       .i_data_b (i_data_b[30:23]), .o_less (w_comp_exp_less));
  COMP_8bit_SIZE_DATA8_1 COMP_MAN_UNIT(.i_data_a ({1'b1,
       w_swap_man0_max[6:0]}), .i_data_b (w_shf_right_man1_min[15:8]),
       .o_less (w_comp_man_less));
  EXP_adjust_SIZE_EXP8_SIZE_LOPD8 EXP_ADJUSTION_UNIT(.i_overflow
       (w_alu_man_overflow), .i_underflow (w_alu_man_result[7]),
       .i_zero_flag (w_lopd_zero_flag), .i_lopd_value ({5'b00000,
       w_lopd_one_pos}), .i_exp_value (w_swap_exp_max), .o_exp_result
       (w_exp_adjust));
  LOPD_8bit LOPD_UNIT(.i_data (w_alu_man_result), .o_pos_one
       (w_lopd_one_pos), .o_zero_flag (w_lopd_zero_flag));
  MAN_ALU_SIZE_MAN8 MAN_ALU_UNIT(.i_sign_a (i_data_a[31]), .i_sign_b
       (i_data_b[31]), .i_carry (w_shf_right_man1_min[7]), .i_man_max
       (w_swap_man1_max), .i_man_min (w_swap_man1_min), .o_man_alu
       (w_alu_man_result), .o_overflow (w_alu_man_overflow));
  NOR_unit_SIZE_LOPD3_SIZE_DATA8 NOR_UNIT(.i_overflow
       (w_alu_man_overflow), .i_zero_flag (w_lopd_zero_flag),
       .i_one_position (w_lopd_one_pos), .i_mantissa
       (w_alu_man_result), .o_mantissa (w_nor_man));
  PSC_unit PSC_UNIT(.i_sign_a (i_data_a[31]), .i_exp_a
       (i_data_a[30:23]), .i_man_a ({1'b1, i_data_a[22:0]}), .i_sign_b
       (i_data_b[31]), .i_exp_b (i_data_b[30:23]), .i_man_b ({1'b1,
       i_data_b[22:0]}), .o_sel_exp (w_sel_exp), .o_sel_man
       ({UNCONNECTED1, w_sel_man[0]}));
  SHF_right_SIZE_DATA16_SIZE_SHIFT4 SHF_RIGHT_MAN_UNIT(.i_shift_number
       (w_sub_exp_result[3:0]), .i_data ({1'b1, w_swap_man0_min[6:0],
       8'b00000000}), .o_data (w_shf_right_man1_min));
  SIGN_unit SIGN_UNIT(.i_comp_man (n_78), .i_sign_man_a (i_data_a[31]),
       .i_sign_man_b (i_data_b[31]), .o_sign_s (o_bfu_add[31]));
  CLA_8bit_2 SUB_EXP_UNIT(.i_carry (1'b1), .i_data_a ({4'b0000,
       w_swap_exp_max[3:0]}), .i_data_b ({4'b0000, n_74, n_75, n_72,
       n_73}), .o_sum (w_sub_exp_result), .o_carry (UNCONNECTED2));
  SWAP_unit_SIZE_DATA8 SWAP_EXP_UNIT(.i_comp_less (w_comp_exp_less),
       .i_data_a (i_data_a[30:23]), .i_data_b (i_data_b[30:23]),
       .o_data_max (w_swap_exp_max), .o_data_min (w_swap_exp_min));
  SWAP_unit_SIZE_DATA8_1 SWAP_MAN0_UNIT(.i_comp_less (w_comp_exp_less),
       .i_data_a ({1'b1, i_data_a[22:16]}), .i_data_b ({1'b1,
       i_data_b[22:16]}), .o_data_max ({UNCONNECTED3,
       w_swap_man0_max[6:0]}), .o_data_min ({UNCONNECTED4,
       w_swap_man0_min[6:0]}));
  SWAP_unit_SIZE_DATA8_2 SWAP_MAN1_UNIT(.i_comp_less (w_comp_man_less),
       .i_data_a ({1'b1, w_swap_man0_max[6:0]}), .i_data_b
       (w_shf_right_man1_min[15:8]), .o_data_max (w_swap_man1_max),
       .o_data_min (w_swap_man1_min));
  INVX1HVT g186(.A (w_swap_exp_min[2]), .Y (n_75));
  INVX1HVT g187(.A (w_swap_exp_min[3]), .Y (n_74));
  INVX1HVT g189(.A (w_swap_exp_min[0]), .Y (n_73));
  INVX1HVT g188(.A (w_swap_exp_min[1]), .Y (n_72));
  OR2X1HVT g761(.A (n_65), .B (n_53), .Y (n_71));
  OR2X1HVT g762(.A (n_21), .B (n_52), .Y (n_70));
  OR2X1HVT g763(.A (n_40), .B (n_61), .Y (n_69));
  OR2X1HVT g764(.A (n_38), .B (n_60), .Y (n_68));
  OR2X1HVT g765(.A (n_37), .B (n_59), .Y (n_67));
  OR2X1HVT g766(.A (n_42), .B (n_62), .Y (n_66));
  AO22X1HVT g767(.A0 (n_44), .A1 (w_sel_man[0]), .B0 (i_data_a[22]),
       .B1 (n_20), .Y (n_65));
  OR2X1HVT g768(.A (n_41), .B (n_58), .Y (n_64));
  OR2X6HVT g769(.A (n_47), .B (n_51), .Y (n_63));
  OR2X8HVT g771(.A (n_50), .B (n_57), .Y (o_bfu_add[27]));
  OR2X8HVT g772(.A (n_49), .B (n_56), .Y (o_bfu_add[26]));
  OR2X8HVT g774(.A (n_46), .B (n_54), .Y (o_bfu_add[23]));
  OR2X8HVT g775(.A (n_48), .B (n_55), .Y (o_bfu_add[25]));
  AND2X1HVT g777(.A (w_nor_man[0]), .B (n_43), .Y (n_62));
  AND2X1HVT g778(.A (w_nor_man[3]), .B (n_43), .Y (n_61));
  AND2X1HVT g779(.A (w_nor_man[2]), .B (n_43), .Y (n_60));
  AND2X1HVT g781(.A (w_nor_man[1]), .B (n_43), .Y (n_59));
  AND2X1HVT g782(.A (w_nor_man[4]), .B (n_43), .Y (n_58));
  AND2X1HVT g785(.A (w_exp_adjust[4]), .B (n_43), .Y (n_57));
  AND2X1HVT g786(.A (w_exp_adjust[3]), .B (n_43), .Y (n_56));
  AND2X1HVT g787(.A (w_exp_adjust[2]), .B (n_43), .Y (n_55));
  AND2X1HVT g789(.A (w_exp_adjust[0]), .B (n_43), .Y (n_54));
  AND2X1HVT g790(.A (w_nor_man[6]), .B (n_43), .Y (n_53));
  AND2X1HVT g791(.A (w_nor_man[5]), .B (n_43), .Y (n_52));
  AND2X1HVT g794(.A (w_exp_adjust[1]), .B (n_43), .Y (n_51));
  OAI2BB1X1HVT g795(.A0N (i_data_a[27]), .A1N (n_20), .B0 (n_45), .Y
       (n_50));
  OAI2BB1X1HVT g796(.A0N (i_data_a[26]), .A1N (n_20), .B0 (n_45), .Y
       (n_49));
  OAI2BB1X1HVT g797(.A0N (i_data_a[25]), .A1N (n_0), .B0 (n_45), .Y
       (n_48));
  OAI2BB1X1HVT g798(.A0N (i_data_a[24]), .A1N (n_20), .B0 (n_45), .Y
       (n_47));
  OAI2BB1X1HVT g799(.A0N (i_data_a[23]), .A1N (n_20), .B0 (n_45), .Y
       (n_46));
  INVX1HVT g800(.A (n_45), .Y (n_44));
  AND2XLHVT g801(.A (i_data_a[16]), .B (n_20), .Y (n_42));
  AND2XLHVT g802(.A (i_data_a[20]), .B (n_0), .Y (n_41));
  AND2XLHVT g803(.A (i_data_a[19]), .B (n_20), .Y (n_40));
  AND2X6HVT g804(.A (i_data_a[11]), .B (n_20), .Y (n_39));
  AND2XLHVT g805(.A (i_data_a[18]), .B (n_20), .Y (n_38));
  AND2XLHVT g806(.A (i_data_a[17]), .B (n_20), .Y (n_37));
  AND2X6HVT g807(.A (i_data_a[12]), .B (n_20), .Y (n_36));
  AND2X6HVT g808(.A (i_data_a[15]), .B (n_20), .Y (n_35));
  AND2X6HVT g809(.A (i_data_a[14]), .B (n_20), .Y (n_34));
  AND2X6HVT g810(.A (i_data_a[13]), .B (n_0), .Y (n_33));
  NAND2X2HVT g811(.A (w_sel_exp), .B (n_9), .Y (n_45));
  NOR2X1HVT g812(.A (w_sel_exp), .B (n_0), .Y (n_43));
  AND2X6HVT g813(.A (i_data_a[4]), .B (n_20), .Y (n_32));
  AND2X6HVT g814(.A (i_data_a[9]), .B (n_20), .Y (n_31));
  AND2X6HVT g815(.A (i_data_a[8]), .B (n_20), .Y (n_30));
  AND2X6HVT g816(.A (i_data_a[7]), .B (n_0), .Y (n_29));
  AND2X6HVT g817(.A (i_data_a[6]), .B (n_20), .Y (n_28));
  AND2X6HVT g818(.A (i_data_a[5]), .B (n_20), .Y (n_27));
  AND2X6HVT g819(.A (i_data_a[10]), .B (n_0), .Y (n_26));
  AND2X6HVT g820(.A (i_data_a[3]), .B (n_20), .Y (n_25));
  AND2X6HVT g821(.A (i_data_a[2]), .B (n_20), .Y (n_24));
  AND2X6HVT g822(.A (i_data_a[1]), .B (n_20), .Y (n_23));
  AND2X6HVT g823(.A (i_data_a[0]), .B (n_0), .Y (n_22));
  NOR2BX1HVT g824(.AN (i_data_a[21]), .B (n_9), .Y (n_21));
  NOR2X4HVT g826(.A (n_19), .B (n_18), .Y (n_20));
  OR4X1HVT g827(.A (n_10), .B (n_12), .C (n_17), .D (n_16), .Y (n_19));
  OR4X1HVT g828(.A (n_13), .B (n_11), .C (n_15), .D (n_14), .Y (n_18));
  OR4X1HVT g829(.A (i_data_b[4]), .B (i_data_b[5]), .C (i_data_b[6]),
       .D (i_data_b[7]), .Y (n_17));
  OR4X1HVT g830(.A (i_data_b[8]), .B (i_data_b[9]), .C (i_data_b[10]),
       .D (i_data_b[11]), .Y (n_16));
  OR4X1HVT g831(.A (i_data_b[20]), .B (i_data_b[21]), .C
       (i_data_b[22]), .D (i_data_b[23]), .Y (n_15));
  OR4X1HVT g832(.A (i_data_b[24]), .B (i_data_b[25]), .C
       (i_data_b[26]), .D (i_data_b[27]), .Y (n_14));
  OR4X1HVT g833(.A (i_data_b[16]), .B (i_data_b[17]), .C
       (i_data_b[18]), .D (i_data_b[19]), .Y (n_13));
  OR4X1HVT g834(.A (i_data_b[12]), .B (i_data_b[13]), .C
       (i_data_b[14]), .D (i_data_b[15]), .Y (n_12));
  OR4X1HVT g835(.A (i_data_b[28]), .B (i_data_b[29]), .C
       (i_data_b[30]), .D (i_data_b[31]), .Y (n_11));
  OR4X1HVT g836(.A (i_data_b[0]), .B (i_data_b[1]), .C (i_data_b[2]),
       .D (i_data_b[3]), .Y (n_10));
  CLKBUFX20HVT fopt(.A (n_7), .Y (o_bfu_add[29]));
  AO21X1HVT g2(.A0 (n_43), .A1 (w_exp_adjust[6]), .B0 (n_8), .Y (n_7));
  OAI2BB1X1HVT g3(.A0N (i_data_a[29]), .A1N (n_0), .B0 (n_45), .Y
       (n_8));
  CLKBUFX20HVT fopt837(.A (n_5), .Y (o_bfu_add[28]));
  AO21X1HVT g839(.A0 (w_exp_adjust[5]), .A1 (n_43), .B0 (n_6), .Y
       (n_5));
  OAI2BB1X1HVT g840(.A0N (i_data_a[28]), .A1N (n_20), .B0 (n_45), .Y
       (n_6));
  OAI2BB1X1HVT g842(.A0N (i_data_a[30]), .A1N (n_20), .B0 (n_45), .Y
       (n_4));
  CLKINVX20HVT g10(.A (n_2), .Y (o_bfu_add[30]));
  NOR2X6HVT g8(.A (n_3), .B (n_1), .Y (n_2));
  CLKAND2X3HVT g9(.A (n_43), .B (w_exp_adjust[7]), .Y (n_3));
  INVX3HVT drc_bufs843(.A (n_9), .Y (n_0));
  INVX1HVT drc_bufs846(.A (n_20), .Y (n_9));
  CLKBUFX20HVT drc_bufs853(.A (n_63), .Y (o_bfu_add[24]));
  CLKBUFX20HVT drc_bufs855(.A (n_71), .Y (o_bfu_add[22]));
  CLKBUFX20HVT drc_bufs856(.A (n_68), .Y (o_bfu_add[18]));
  CLKBUFX20HVT drc_bufs857(.A (n_70), .Y (o_bfu_add[21]));
  CLKBUFX20HVT drc_bufs858(.A (n_67), .Y (o_bfu_add[17]));
  CLKBUFX20HVT drc_bufs859(.A (n_69), .Y (o_bfu_add[19]));
  CLKBUFX20HVT drc_bufs860(.A (n_66), .Y (o_bfu_add[16]));
  CLKBUFX20HVT drc_bufs861(.A (n_64), .Y (o_bfu_add[20]));
  CLKBUFX20HVT drc_bufs862(.A (n_29), .Y (o_bfu_add[7]));
  CLKBUFX20HVT drc_bufs863(.A (n_25), .Y (o_bfu_add[3]));
  CLKBUFX20HVT drc_bufs864(.A (n_31), .Y (o_bfu_add[9]));
  CLKBUFX20HVT drc_bufs865(.A (n_23), .Y (o_bfu_add[1]));
  CLKBUFX20HVT drc_bufs866(.A (n_34), .Y (o_bfu_add[14]));
  CLKBUFX20HVT drc_bufs867(.A (n_33), .Y (o_bfu_add[13]));
  CLKBUFX20HVT drc_bufs868(.A (n_35), .Y (o_bfu_add[15]));
  CLKBUFX20HVT drc_bufs869(.A (n_22), .Y (o_bfu_add[0]));
  CLKBUFX20HVT drc_bufs870(.A (n_39), .Y (o_bfu_add[11]));
  CLKBUFX20HVT drc_bufs871(.A (n_32), .Y (o_bfu_add[4]));
  CLKBUFX20HVT drc_bufs872(.A (n_28), .Y (o_bfu_add[6]));
  CLKBUFX20HVT drc_bufs873(.A (n_24), .Y (o_bfu_add[2]));
  CLKBUFX20HVT drc_bufs874(.A (n_30), .Y (o_bfu_add[8]));
  CLKBUFX20HVT drc_bufs875(.A (n_26), .Y (o_bfu_add[10]));
  CLKBUFX20HVT drc_bufs876(.A (n_27), .Y (o_bfu_add[5]));
  CLKBUFX20HVT drc_bufs877(.A (n_36), .Y (o_bfu_add[12]));
  BUFX3HVT drc_bufs878(.A (n_4), .Y (n_1));
  OR2XLHVT g182(.A (w_comp_exp_less), .B (w_comp_man_less), .Y (n_78));
endmodule

