
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: Dec  9 2025 03:22:34

// Verification Directory fv/BFP16_add 

module COMP_4bit(i_data_a, i_data_b, o_less, o_equal);
  input [3:0] i_data_a, i_data_b;
  output o_less, o_equal;
  wire [3:0] i_data_a, i_data_b;
  wire o_less, o_equal;
  wire n_3, n_4, n_6, n_7, n_9, n_10, n_11, n_16;
  wire n_17, n_21, n_24, n_29, n_30, n_34, n_36, n_38;
  wire n_43, n_44, n_48, n_50, n_52, n_53, n_55, n_60;
  wire n_65, n_69, n_74, n_75, n_76, n_77, n_78, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  not g1 (n_3, i_data_a[3]);
  not g2 (n_4, i_data_a[2]);
  and g3 (n_6, n_3, n_4);
  not g4 (n_7, i_data_a[1]);
  and g5 (n_9, n_6, n_7);
  not g6 (n_10, i_data_a[0]);
  and g7 (n_11, n_9, n_10);
  and g8 (n_16, n_11, i_data_b[0]);
  and g11 (n_17, n_9, i_data_b[1]);
  and g14 (n_21, n_6, i_data_b[2]);
  and g16 (n_24, n_3, i_data_b[3]);
  and g23 (n_30, n_3, n_7);
  and g29 (n_36, n_30, i_data_b[2]);
  and g30 (n_38, n_36, i_data_b[1]);
  and g37 (n_44, n_4, n_7);
  and g43 (n_50, n_44, i_data_b[3]);
  and g44 (n_52, n_50, i_data_b[1]);
  and g46 (n_53, n_4, i_data_b[3]);
  and g47 (n_55, n_53, i_data_b[2]);
  xor g70 (n_75, i_data_a[0], i_data_b[0]);
  xor g71 (n_76, i_data_a[1], i_data_b[1]);
  xor g72 (n_77, i_data_a[2], i_data_b[2]);
  xor g73 (n_78, i_data_a[3], i_data_b[3]);
  nor g74 (o_equal, n_78, n_77, n_76, n_75);
  or g75 (n_81, n_16, n_17, n_21, n_24);
  or g76 (n_82, n_29, n_34, n_38, n_43);
  or g77 (n_83, n_48, n_52, n_55, n_60);
  or g78 (n_84, n_65, n_69, n_74);
  or g79 (o_less, n_81, n_82, n_83, n_84);
  and g80 (n_29, n_6, n_10, i_data_b[1], i_data_b[0]);
  and g81 (n_34, n_30, n_10, i_data_b[2], i_data_b[0]);
  and g82 (n_85, n_3, n_10);
  and g83 (n_43, i_data_b[2], i_data_b[1], i_data_b[0], n_85);
  and g84 (n_48, n_44, n_10, i_data_b[3], i_data_b[0]);
  and g85 (n_86, n_4, n_10);
  and g86 (n_60, i_data_b[3], i_data_b[1], i_data_b[0], n_86);
  and g87 (n_87, n_7, n_10);
  and g88 (n_65, i_data_b[3], i_data_b[2], i_data_b[0], n_87);
  and g89 (n_69, n_7, i_data_b[3], i_data_b[2], i_data_b[1]);
  and g90 (n_88, n_10, i_data_b[3]);
  and g91 (n_74, i_data_b[2], i_data_b[1], i_data_b[0], n_88);
endmodule

module COMP_8bit_SIZE_DATA8(i_data_a, i_data_b, o_less);
  input [7:0] i_data_a, i_data_b;
  output o_less;
  wire [7:0] i_data_a, i_data_b;
  wire o_less;
  wire n_17, w_equal_high, w_equal_low, w_less_high, w_less_low;
  COMP_4bit u_low(.i_data_a (i_data_a[3:0]), .i_data_b (i_data_b[3:0]),
       .o_less (w_less_low), .o_equal (w_equal_low));
  COMP_4bit u_high(.i_data_a (i_data_a[7:4]), .i_data_b
       (i_data_b[7:4]), .o_less (w_less_high), .o_equal (w_equal_high));
  and g1 (n_17, w_equal_high, w_less_low);
  or g2 (o_less, w_less_high, n_17);
endmodule

module bmux(ctl, in_0, in_1, z);
  input ctl;
  input [7:0] in_0, in_1;
  output [7:0] z;
  wire ctl;
  wire [7:0] in_0, in_1;
  wire [7:0] z;
  CDN_bmux2 g1(.sel0 (ctl), .data0 (in_0[7]), .data1 (in_1[7]), .z
       (z[7]));
  CDN_bmux2 g2(.sel0 (ctl), .data0 (in_0[6]), .data1 (in_1[6]), .z
       (z[6]));
  CDN_bmux2 g3(.sel0 (ctl), .data0 (in_0[5]), .data1 (in_1[5]), .z
       (z[5]));
  CDN_bmux2 g4(.sel0 (ctl), .data0 (in_0[4]), .data1 (in_1[4]), .z
       (z[4]));
  CDN_bmux2 g5(.sel0 (ctl), .data0 (in_0[3]), .data1 (in_1[3]), .z
       (z[3]));
  CDN_bmux2 g6(.sel0 (ctl), .data0 (in_0[2]), .data1 (in_1[2]), .z
       (z[2]));
  CDN_bmux2 g7(.sel0 (ctl), .data0 (in_0[1]), .data1 (in_1[1]), .z
       (z[1]));
  CDN_bmux2 g8(.sel0 (ctl), .data0 (in_0[0]), .data1 (in_1[0]), .z
       (z[0]));
endmodule

module SWAP_unit_SIZE_DATA8(i_comp_less, i_data_a, i_data_b,
     o_data_max, o_data_min);
  input i_comp_less;
  input [7:0] i_data_a, i_data_b;
  output [7:0] o_data_max, o_data_min;
  wire i_comp_less;
  wire [7:0] i_data_a, i_data_b;
  wire [7:0] o_data_max, o_data_min;
  bmux mux_13_19(.ctl (i_comp_less), .in_0 (i_data_b), .in_1
       (i_data_a), .z (o_data_min));
  bmux mux_12_19(.ctl (i_comp_less), .in_0 (i_data_a), .in_1
       (i_data_b), .z (o_data_max));
endmodule

module CLA_4bit(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire [3:0] w_p;
  wire [3:0] w_g;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_17;
  wire n_19, n_21, n_22, n_23, n_25, n_27, n_29, n_32;
  wire n_34, n_41, n_42, \w_c[1] , \w_c[2] , \w_c[3] ;
  and g3 (n_9, w_p[0], cin);
  or g4 (\w_c[1] , w_g[0], n_9);
  and g5 (n_10, w_p[1], w_g[0]);
  or g6 (n_12, w_g[1], n_10);
  and g7 (n_11, w_p[1], w_p[0]);
  and g8 (n_13, n_11, cin);
  or g9 (\w_c[2] , n_12, n_13);
  and g10 (n_14, w_p[2], w_g[1]);
  and g12 (n_15, w_p[2], w_p[1]);
  and g13 (n_17, n_15, w_g[0]);
  and g16 (n_19, n_15, w_p[0]);
  and g17 (n_21, n_19, cin);
  and g21 (n_22, w_p[3], w_g[2]);
  and g23 (n_23, w_p[3], w_p[2]);
  and g24 (n_25, n_23, w_g[1]);
  and g27 (n_27, n_23, w_p[1]);
  and g28 (n_29, n_27, w_g[0]);
  and g32 (n_32, n_27, w_p[0]);
  and g33 (n_34, n_32, cin);
  and g1 (w_g[0], a[0], b[0]);
  and g35 (w_g[1], a[1], b[1]);
  and g36 (w_g[2], a[2], b[2]);
  and g37 (w_g[3], a[3], b[3]);
  xor g38 (w_p[0], a[0], b[0]);
  xor g2 (w_p[1], a[1], b[1]);
  xor g39 (w_p[2], a[2], b[2]);
  xor g40 (w_p[3], a[3], b[3]);
  xor g41 (sum[0], w_p[0], cin);
  xor g42 (sum[1], w_p[1], \w_c[1] );
  xor g43 (sum[2], w_p[2], \w_c[2] );
  xor g44 (sum[3], w_p[3], \w_c[3] );
  nand g45 (n_41, w_p[3], w_p[2], w_p[1], w_p[0]);
  not g46 (o_p, n_41);
  or g47 (\w_c[3] , w_g[2], n_14, n_17, n_21);
  or g48 (n_42, w_g[3], n_22);
  or g49 (o_g, n_25, n_29, n_34, n_42);
endmodule

module CLA_8bit(i_carry, i_data_a, i_data_b, o_sum, o_carry);
  input i_carry;
  input [7:0] i_data_a, i_data_b;
  output [7:0] o_sum;
  output o_carry;
  wire i_carry;
  wire [7:0] i_data_a, i_data_b;
  wire [7:0] o_sum;
  wire o_carry;
  wire n_18, n_23, w_C, w_G, w_G_22, w_P, w_P_20;
  CLA_4bit CLA_4BIT_UNIT_0(.a (i_data_a[3:0]), .b (i_data_b[3:0]), .cin
       (i_carry), .sum (o_sum[3:0]), .o_p (w_P), .o_g (w_G));
  CLA_4bit CLA_4BIT_UNIT_1(.a (i_data_a[7:4]), .b (i_data_b[7:4]), .cin
       (w_C), .sum (o_sum[7:4]), .o_p (w_P_20), .o_g (w_G_22));
  and g1 (n_18, w_P, i_carry);
  or g2 (w_C, w_G, n_18);
  and g5 (n_23, w_P_20, w_C);
  or g6 (o_carry, w_G_22, n_23);
endmodule

module bmux_2(ctl, in_0, in_1, z);
  input ctl;
  input [15:0] in_0, in_1;
  output [15:0] z;
  wire ctl;
  wire [15:0] in_0, in_1;
  wire [15:0] z;
  CDN_bmux2 g1(.sel0 (ctl), .data0 (in_0[15]), .data1 (in_1[15]), .z
       (z[15]));
  CDN_bmux2 g2(.sel0 (ctl), .data0 (in_0[14]), .data1 (in_1[14]), .z
       (z[14]));
  CDN_bmux2 g3(.sel0 (ctl), .data0 (in_0[13]), .data1 (in_1[13]), .z
       (z[13]));
  CDN_bmux2 g4(.sel0 (ctl), .data0 (in_0[12]), .data1 (in_1[12]), .z
       (z[12]));
  CDN_bmux2 g5(.sel0 (ctl), .data0 (in_0[11]), .data1 (in_1[11]), .z
       (z[11]));
  CDN_bmux2 g6(.sel0 (ctl), .data0 (in_0[10]), .data1 (in_1[10]), .z
       (z[10]));
  CDN_bmux2 g7(.sel0 (ctl), .data0 (in_0[9]), .data1 (in_1[9]), .z
       (z[9]));
  CDN_bmux2 g8(.sel0 (ctl), .data0 (in_0[8]), .data1 (in_1[8]), .z
       (z[8]));
  CDN_bmux2 g9(.sel0 (ctl), .data0 (in_0[7]), .data1 (in_1[7]), .z
       (z[7]));
  CDN_bmux2 g10(.sel0 (ctl), .data0 (in_0[6]), .data1 (in_1[6]), .z
       (z[6]));
  CDN_bmux2 g11(.sel0 (ctl), .data0 (in_0[5]), .data1 (in_1[5]), .z
       (z[5]));
  CDN_bmux2 g12(.sel0 (ctl), .data0 (in_0[4]), .data1 (in_1[4]), .z
       (z[4]));
  CDN_bmux2 g13(.sel0 (ctl), .data0 (in_0[3]), .data1 (in_1[3]), .z
       (z[3]));
  CDN_bmux2 g14(.sel0 (ctl), .data0 (in_0[2]), .data1 (in_1[2]), .z
       (z[2]));
  CDN_bmux2 g15(.sel0 (ctl), .data0 (in_0[1]), .data1 (in_1[1]), .z
       (z[1]));
  CDN_bmux2 g16(.sel0 (ctl), .data0 (in_0[0]), .data1 (in_1[0]), .z
       (z[0]));
endmodule

module SHF_right_SIZE_DATA16_SIZE_SHIFT4(i_shift_number, i_data,
     o_data);
  input [3:0] i_shift_number;
  input [15:0] i_data;
  output [15:0] o_data;
  wire [3:0] i_shift_number;
  wire [15:0] i_data;
  wire [15:0] o_data;
  wire [15:0] \stage[1] ;
  wire [15:0] \stage[2] ;
  wire [15:0] \stage[3] ;
  bmux_2 mux_19_33(.ctl (i_shift_number[0]), .in_0 (i_data), .in_1
       ({1'b0, i_data[15:1]}), .z ({\stage[1] [15], \stage[1] [14],
       \stage[1] [13], \stage[1] [12], \stage[1] [11], \stage[1] [10],
       \stage[1] [9], \stage[1] [8], \stage[1] [7], \stage[1] [6],
       \stage[1] [5], \stage[1] [4], \stage[1] [3], \stage[1] [2],
       \stage[1] [1], \stage[1] [0]}));
  bmux_2 mux_19_5(.ctl (i_shift_number[1]), .in_0 ({\stage[1] [15],
       \stage[1] [14], \stage[1] [13], \stage[1] [12], \stage[1] [11],
       \stage[1] [10], \stage[1] [9], \stage[1] [8], \stage[1] [7],
       \stage[1] [6], \stage[1] [5], \stage[1] [4], \stage[1] [3],
       \stage[1] [2], \stage[1] [1], \stage[1] [0]}), .in_1 ({2'b00,
       \stage[1] [15], \stage[1] [14], \stage[1] [13], \stage[1] [12],
       \stage[1] [11], \stage[1] [10], \stage[1] [9], \stage[1] [8],
       \stage[1] [7], \stage[1] [6], \stage[1] [5], \stage[1] [4],
       \stage[1] [3], \stage[1] [2]}), .z ({\stage[2] [15],
       \stage[2] [14], \stage[2] [13], \stage[2] [12], \stage[2] [11],
       \stage[2] [10], \stage[2] [9], \stage[2] [8], \stage[2] [7],
       \stage[2] [6], \stage[2] [5], \stage[2] [4], \stage[2] [3],
       \stage[2] [2], \stage[2] [1], \stage[2] [0]}));
  bmux_2 mux_19_6(.ctl (i_shift_number[2]), .in_0 ({\stage[2] [15],
       \stage[2] [14], \stage[2] [13], \stage[2] [12], \stage[2] [11],
       \stage[2] [10], \stage[2] [9], \stage[2] [8], \stage[2] [7],
       \stage[2] [6], \stage[2] [5], \stage[2] [4], \stage[2] [3],
       \stage[2] [2], \stage[2] [1], \stage[2] [0]}), .in_1 ({4'b0000,
       \stage[2] [15], \stage[2] [14], \stage[2] [13], \stage[2] [12],
       \stage[2] [11], \stage[2] [10], \stage[2] [9], \stage[2] [8],
       \stage[2] [7], \stage[2] [6], \stage[2] [5], \stage[2] [4]}), .z
       ({\stage[3] [15], \stage[3] [14], \stage[3] [13], \stage[3]
       [12], \stage[3] [11], \stage[3] [10], \stage[3] [9],
       \stage[3] [8], \stage[3] [7], \stage[3] [6], \stage[3] [5],
       \stage[3] [4], \stage[3] [3], \stage[3] [2], \stage[3] [1],
       \stage[3] [0]}));
  bmux_2 mux_19_7(.ctl (i_shift_number[3]), .in_0 ({\stage[3] [15],
       \stage[3] [14], \stage[3] [13], \stage[3] [12], \stage[3] [11],
       \stage[3] [10], \stage[3] [9], \stage[3] [8], \stage[3] [7],
       \stage[3] [6], \stage[3] [5], \stage[3] [4], \stage[3] [3],
       \stage[3] [2], \stage[3] [1], \stage[3] [0]}), .in_1
       ({8'b00000000, \stage[3] [15], \stage[3] [14], \stage[3] [13],
       \stage[3] [12], \stage[3] [11], \stage[3] [10], \stage[3] [9],
       \stage[3] [8]}), .z (o_data));
endmodule

module not_op(A, Z);
  input [7:0] A;
  output [7:0] Z;
  wire [7:0] A;
  wire [7:0] Z;
  not g1 (Z[7], A[7]);
  not g2 (Z[6], A[6]);
  not g3 (Z[5], A[5]);
  not g4 (Z[4], A[4]);
  not g5 (Z[3], A[3]);
  not g6 (Z[2], A[2]);
  not g7 (Z[1], A[1]);
  not g8 (Z[0], A[0]);
endmodule

module bmux_7(ctl, in_0, in_1, z);
  input ctl, in_0, in_1;
  output z;
  wire ctl, in_0, in_1;
  wire z;
  CDN_bmux2 g1(.sel0 (ctl), .data0 (in_0), .data1 (in_1), .z (z));
endmodule

module MAN_ALU_SIZE_MAN8(i_sign_a, i_sign_b, i_carry, i_man_max,
     i_man_min, o_man_alu, o_overflow);
  input i_sign_a, i_sign_b, i_carry;
  input [7:0] i_man_max, i_man_min;
  output [7:0] o_man_alu;
  output o_overflow;
  wire i_sign_a, i_sign_b, i_carry;
  wire [7:0] i_man_max, i_man_min;
  wire [7:0] o_man_alu;
  wire o_overflow;
  wire [7:0] w_i_man_b;
  wire [7:0] w_n_man_b;
  wire n_20, n_22, w_i_carry_alu, w_i_fpu_op, w_overflow;
  CLA_8bit ALU_SUB_UNIT(.i_carry (w_i_carry_alu), .i_data_a
       (i_man_max), .i_data_b (w_i_man_b), .o_sum (o_man_alu), .o_carry
       (w_overflow));
  not_op g3(.A (i_man_min), .Z (w_n_man_b));
  bmux mux_21_20(.ctl (w_i_fpu_op), .in_0 (w_n_man_b), .in_1
       (i_man_min), .z (w_i_man_b));
  bmux_7 mux_31_21(.ctl (w_i_fpu_op), .in_0 (1'b0), .in_1 (w_overflow),
       .z (o_overflow));
  xor g1 (n_20, i_sign_a, i_sign_b);
  not g2 (w_i_fpu_op, n_20);
  or g4 (n_22, i_carry, w_i_fpu_op);
  not g5 (w_i_carry_alu, n_22);
endmodule

module bmux_8(ctl, in_0, in_1, z);
  input ctl;
  input [2:0] in_0, in_1;
  output [2:0] z;
  wire ctl;
  wire [2:0] in_0, in_1;
  wire [2:0] z;
  CDN_bmux2 g1(.sel0 (ctl), .data0 (in_0[2]), .data1 (in_1[2]), .z
       (z[2]));
  CDN_bmux2 g2(.sel0 (ctl), .data0 (in_0[1]), .data1 (in_1[1]), .z
       (z[1]));
  CDN_bmux2 g3(.sel0 (ctl), .data0 (in_0[0]), .data1 (in_1[0]), .z
       (z[0]));
endmodule

module LOPD_8bit(i_data, o_pos_one, o_zero_flag);
  input [7:0] i_data;
  output [2:0] o_pos_one;
  output o_zero_flag;
  wire [7:0] i_data;
  wire [2:0] o_pos_one;
  wire o_zero_flag;
  wire [2:0] w_o_pos_one;
  wire n_7, n_8, n_10, n_11, n_13, n_14, n_15, n_20;
  wire n_21, n_25, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_37, n_38, n_41, n_44, n_46, n_47, n_48, n_52;
  wire n_53, n_58, n_63, n_70, n_74, n_75, n_76, n_77;
  bmux_8 mux_41_20(.ctl (o_zero_flag), .in_0 (w_o_pos_one), .in_1
       (3'b111), .z (o_pos_one));
  not g1 (n_7, i_data[7]);
  not g2 (n_8, i_data[5]);
  and g3 (n_10, n_7, n_8);
  not g4 (n_11, i_data[3]);
  and g5 (n_13, n_10, n_11);
  not g6 (n_14, i_data[1]);
  and g7 (n_15, n_13, n_14);
  and g8 (n_20, n_15, i_data[0]);
  and g11 (n_21, n_13, i_data[2]);
  and g14 (n_25, n_10, i_data[4]);
  and g16 (n_28, n_7, i_data[6]);
  not g18 (n_29, i_data[6]);
  and g19 (n_30, n_7, n_29);
  and g20 (n_31, n_30, n_11);
  not g21 (n_32, i_data[2]);
  and g22 (n_33, n_31, n_32);
  and g23 (n_37, n_33, i_data[0]);
  and g27 (n_38, n_33, i_data[1]);
  and g30 (n_41, n_30, i_data[4]);
  and g33 (n_44, n_30, i_data[5]);
  and g36 (n_46, n_30, n_8);
  not g37 (n_47, i_data[4]);
  and g38 (n_48, n_46, n_47);
  and g39 (n_52, n_48, i_data[0]);
  and g43 (n_53, n_48, i_data[1]);
  and g48 (n_58, n_48, i_data[2]);
  and g53 (n_63, n_48, i_data[3]);
  not g62 (o_zero_flag, n_70);
  or g64 (w_o_pos_one[2], n_52, n_53, n_58, n_63);
  or g65 (w_o_pos_one[1], n_37, n_38, n_41, n_44);
  or g66 (w_o_pos_one[0], n_20, n_21, n_25, n_28);
  or g67 (n_74, i_data[7], i_data[6]);
  or g68 (n_75, i_data[5], i_data[4]);
  or g69 (n_76, i_data[3], i_data[2]);
  or g70 (n_77, i_data[1], i_data[0]);
  or g71 (n_70, n_74, n_75, n_76, n_77);
endmodule

module SHF_left_SIZE_DATA8_SIZE_SHIFT3(i_shift_number, i_data, o_data);
  input [2:0] i_shift_number;
  input [7:0] i_data;
  output [7:0] o_data;
  wire [2:0] i_shift_number;
  wire [7:0] i_data;
  wire [7:0] o_data;
  wire [7:0] \stage[1] ;
  wire [7:0] \stage[2] ;
  bmux mux_20_33(.ctl (i_shift_number[0]), .in_0 (i_data), .in_1
       ({i_data[6:0], 1'b0}), .z ({\stage[1] [7], \stage[1] [6],
       \stage[1] [5], \stage[1] [4], \stage[1] [3], \stage[1] [2],
       \stage[1] [1], \stage[1] [0]}));
  bmux mux_20_4(.ctl (i_shift_number[1]), .in_0 ({\stage[1] [7],
       \stage[1] [6], \stage[1] [5], \stage[1] [4], \stage[1] [3],
       \stage[1] [2], \stage[1] [1], \stage[1] [0]}), .in_1
       ({\stage[1] [5], \stage[1] [4], \stage[1] [3], \stage[1] [2],
       \stage[1] [1], \stage[1] [0], 2'b00}), .z ({\stage[2] [7],
       \stage[2] [6], \stage[2] [5], \stage[2] [4], \stage[2] [3],
       \stage[2] [2], \stage[2] [1], \stage[2] [0]}));
  bmux mux_20_5(.ctl (i_shift_number[2]), .in_0 ({\stage[2] [7],
       \stage[2] [6], \stage[2] [5], \stage[2] [4], \stage[2] [3],
       \stage[2] [2], \stage[2] [1], \stage[2] [0]}), .in_1
       ({\stage[2] [3], \stage[2] [2], \stage[2] [1], \stage[2] [0],
       4'b0000}), .z (o_data));
endmodule

module NOR_unit_SIZE_LOPD3_SIZE_DATA8(i_overflow, i_zero_flag,
     i_one_position, i_mantissa, o_mantissa);
  input i_overflow, i_zero_flag;
  input [2:0] i_one_position;
  input [7:0] i_mantissa;
  output [7:0] o_mantissa;
  wire i_overflow, i_zero_flag;
  wire [2:0] i_one_position;
  wire [7:0] i_mantissa;
  wire [7:0] o_mantissa;
  wire [7:0] w_shift_left;
  wire n_12, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36;
  SHF_left_SIZE_DATA8_SIZE_SHIFT3 SHF_left_unit(.i_shift_number
       (i_one_position), .i_data (i_mantissa), .o_data (w_shift_left));
  bmux mux_23_91(.ctl (n_12), .in_0 (i_mantissa), .in_1 (w_shift_left),
       .z ({n_28, n_27, n_26, n_25, n_24, n_23, n_22, n_21}));
  bmux mux_23_41(.ctl (i_overflow), .in_0 ({n_28, n_27, n_26, n_25,
       n_24, n_23, n_22, n_21}), .in_1 ({1'b1, i_mantissa[7:1]}), .z
       ({n_36, n_35, n_34, n_33, n_32, n_31, n_30, n_29}));
  bmux mux_23_21(.ctl (i_zero_flag), .in_0 ({n_36, n_35, n_34, n_33,
       n_32, n_31, n_30, n_29}), .in_1 (8'b00000000), .z (o_mantissa));
  not g1 (n_12, i_mantissa[7]);
endmodule

module not_op_3(A, Z);
  input [7:0] A;
  output [7:0] Z;
  wire [7:0] A;
  wire [7:0] Z;
  not g1 (Z[7], A[7]);
  not g2 (Z[6], A[6]);
  not g3 (Z[5], A[5]);
  not g4 (Z[4], A[4]);
  not g5 (Z[3], A[3]);
  not g6 (Z[2], A[2]);
  not g7 (Z[1], A[1]);
  not g8 (Z[0], A[0]);
endmodule

module EXP_adjust_SIZE_EXP8_SIZE_LOPD8(i_overflow, i_underflow,
     i_zero_flag, i_lopd_value, i_exp_value, o_exp_result);
  input i_overflow, i_underflow, i_zero_flag;
  input [7:0] i_lopd_value, i_exp_value;
  output [7:0] o_exp_result;
  wire i_overflow, i_underflow, i_zero_flag;
  wire [7:0] i_lopd_value, i_exp_value;
  wire [7:0] o_exp_result;
  wire [7:0] w_data_b;
  wire [7:0] w_exp_result;
  wire UNCONNECTED, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_52, w_i_carry;
  CLA_8bit CLA_8BIT_UNIT(.i_carry (w_i_carry), .i_data_a (i_exp_value),
       .i_data_b (w_data_b), .o_sum (w_exp_result), .o_carry
       (UNCONNECTED));
  not_op_3 g3(.A (i_lopd_value), .Z ({n_35, n_34, n_33, n_32, n_31,
       n_30, n_29, n_28}));
  bmux mux_21_48(.ctl (i_underflow), .in_0 ({n_35, n_34, n_33, n_32,
       n_31, n_30, n_29, n_28}), .in_1 (8'b00000000), .z ({n_43, n_42,
       n_41, n_40, n_39, n_38, n_37, n_36}));
  bmux mux_21_19(.ctl (i_overflow), .in_0 ({n_43, n_42, n_41, n_40,
       n_39, n_38, n_37, n_36}), .in_1 (8'b00000001), .z (w_data_b));
  bmux mux_33_23(.ctl (i_zero_flag), .in_0 (w_exp_result), .in_1
       (8'b00000000), .z (o_exp_result));
  or g1 (n_52, i_overflow, i_underflow);
  not g2 (w_i_carry, n_52);
endmodule

module SIGN_unit(i_comp_man, i_sign_man_a, i_sign_man_b, o_sign_s);
  input i_comp_man, i_sign_man_a, i_sign_man_b;
  output o_sign_s;
  wire i_comp_man, i_sign_man_a, i_sign_man_b;
  wire o_sign_s;
  wire n_4, n_5, n_6;
  and g1 (n_5, i_sign_man_b, i_comp_man);
  not g2 (n_4, i_comp_man);
  and g3 (n_6, i_sign_man_a, n_4);
  or g4 (o_sign_s, n_5, n_6);
endmodule

module PSC_unit(i_sign_a, i_exp_a, i_man_a, i_sign_b, i_exp_b, i_man_b,
     o_sel_exp, o_sel_man);
  input i_sign_a, i_sign_b;
  input [7:0] i_exp_a, i_exp_b;
  input [23:0] i_man_a, i_man_b;
  output o_sel_exp;
  output [1:0] o_sel_man;
  wire i_sign_a, i_sign_b;
  wire [7:0] i_exp_a, i_exp_b;
  wire [23:0] i_man_a, i_man_b;
  wire o_sel_exp;
  wire [1:0] o_sel_man;
  wire n_63, n_64, n_65, n_66, n_73, n_78, n_82, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_96, n_97, n_98, n_99;
  wire n_100, n_101, n_102, n_103, w_E_one_A, w_E_one_B, w_M_zero_A,
       w_M_zero_B;
  assign o_sel_man[1] = o_sel_exp;
  or g5 (o_sel_exp, w_E_one_A, w_E_one_B);
  not g7 (n_63, w_M_zero_B);
  and g8 (n_65, w_E_one_B, n_63);
  not g9 (n_64, w_M_zero_A);
  and g10 (n_66, w_E_one_A, n_64);
  nand g1 (n_83, i_exp_a[7], i_exp_a[6], i_exp_a[5], i_exp_a[4]);
  nand g22 (n_82, i_exp_a[3], i_exp_a[2], i_exp_a[1], i_exp_a[0]);
  nor g23 (w_E_one_A, n_82, n_83);
  nand g24 (n_85, i_exp_b[7], i_exp_b[6], i_exp_b[5], i_exp_b[4]);
  nand g2 (n_84, i_exp_b[3], i_exp_b[2], i_exp_b[1], i_exp_b[0]);
  nor g25 (w_E_one_B, n_84, n_85);
  nor g26 (n_86, i_man_a[22], i_man_a[21], i_man_a[20], i_man_a[19]);
  nor g27 (n_87, i_man_a[18], i_man_a[17], i_man_a[16], i_man_a[15]);
  nor g3 (n_88, i_man_a[14], i_man_a[13], i_man_a[12], i_man_a[11]);
  nor g28 (n_89, i_man_a[10], i_man_a[9], i_man_a[8], i_man_a[7]);
  nor g29 (n_90, i_man_a[6], i_man_a[5], i_man_a[4], i_man_a[3]);
  nor g30 (n_91, i_man_a[2], i_man_a[1], i_man_a[0]);
  nand g31 (n_93, n_86, n_87, n_88, n_89);
  nand g32 (n_92, n_90, n_91);
  nor g33 (w_M_zero_A, n_92, n_93);
  nor g34 (n_94, i_man_b[22], i_man_b[21], i_man_b[20], i_man_b[19]);
  nor g35 (n_95, i_man_b[18], i_man_b[17], i_man_b[16], i_man_b[15]);
  nor g36 (n_96, i_man_b[14], i_man_b[13], i_man_b[12], i_man_b[11]);
  nor g4 (n_97, i_man_b[10], i_man_b[9], i_man_b[8], i_man_b[7]);
  nor g37 (n_98, i_man_b[6], i_man_b[5], i_man_b[4], i_man_b[3]);
  nor g38 (n_99, i_man_b[2], i_man_b[1], i_man_b[0]);
  nand g39 (n_101, n_94, n_95, n_96, n_97);
  nand g40 (n_100, n_98, n_99);
  nor g41 (w_M_zero_B, n_100, n_101);
  or g42 (o_sel_man[0], n_65, n_66, n_73, n_78);
  and g43 (n_73, n_102, w_E_one_A, i_sign_b, w_E_one_B);
  not g44 (n_102, i_sign_a);
  and g45 (n_78, n_103, i_sign_a, w_E_one_A, w_E_one_B);
  not g46 (n_103, i_sign_b);
endmodule

module not_op_6(A, Z);
  input [7:0] A;
  output [7:0] Z;
  wire [7:0] A;
  wire [7:0] Z;
  not g1 (Z[7], A[7]);
  not g2 (Z[6], A[6]);
  not g3 (Z[5], A[5]);
  not g4 (Z[4], A[4]);
  not g5 (Z[3], A[3]);
  not g6 (Z[2], A[2]);
  not g7 (Z[1], A[1]);
  not g8 (Z[0], A[0]);
endmodule

module BFP16_add(i_data_a, i_data_b, o_bfu_add);
  input [31:0] i_data_a, i_data_b;
  output [31:0] o_bfu_add;
  wire [31:0] i_data_a, i_data_b;
  wire [31:0] o_bfu_add;
  wire [7:0] w_swap_exp_max;
  wire [7:0] w_swap_exp_min;
  wire [7:0] w_sub_exp_result;
  wire [7:0] w_swap_man0_max;
  wire [7:0] w_swap_man0_min;
  wire [15:0] w_shf_right_man1_min;
  wire [7:0] w_swap_man1_max;
  wire [7:0] w_swap_man1_min;
  wire [7:0] w_alu_man_result;
  wire [2:0] w_lopd_one_pos;
  wire [7:0] w_nor_man;
  wire [7:0] w_exp_adjust;
  wire [1:0] w_sel_man;
  wire [7:0] w_man_result;
  wire UNCONNECTED0, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, w_alu_man_overflow, w_comp_exp_less,
       w_comp_man_less, w_lopd_zero_flag, w_sel_exp;
  assign o_bfu_add[0] = 1'b0;
  assign o_bfu_add[1] = 1'b0;
  assign o_bfu_add[2] = 1'b0;
  assign o_bfu_add[3] = 1'b0;
  assign o_bfu_add[4] = 1'b0;
  assign o_bfu_add[5] = 1'b0;
  assign o_bfu_add[6] = 1'b0;
  assign o_bfu_add[7] = 1'b0;
  assign o_bfu_add[8] = 1'b0;
  assign o_bfu_add[9] = 1'b0;
  assign o_bfu_add[10] = 1'b0;
  assign o_bfu_add[11] = 1'b0;
  assign o_bfu_add[12] = 1'b0;
  assign o_bfu_add[13] = 1'b0;
  assign o_bfu_add[14] = 1'b0;
  assign o_bfu_add[15] = 1'b0;
  COMP_8bit_SIZE_DATA8 COMP_EXP_UNIT(.i_data_a (i_data_a[30:23]),
       .i_data_b (i_data_b[30:23]), .o_less (w_comp_exp_less));
  SWAP_unit_SIZE_DATA8 SWAP_EXP_UNIT(.i_comp_less (w_comp_exp_less),
       .i_data_a (i_data_a[30:23]), .i_data_b (i_data_b[30:23]),
       .o_data_max (w_swap_exp_max), .o_data_min (w_swap_exp_min));
  CLA_8bit SUB_EXP_UNIT(.i_carry (1'b1), .i_data_a (w_swap_exp_max),
       .i_data_b ({n_67, n_66, n_65, n_64, n_63, n_62, n_61, n_60}),
       .o_sum (w_sub_exp_result), .o_carry (UNCONNECTED0));
  SWAP_unit_SIZE_DATA8 SWAP_MAN0_UNIT(.i_comp_less (w_comp_exp_less),
       .i_data_a ({1'b1, i_data_a[22:16]}), .i_data_b ({1'b1,
       i_data_b[22:16]}), .o_data_max (w_swap_man0_max), .o_data_min
       (w_swap_man0_min));
  SHF_right_SIZE_DATA16_SIZE_SHIFT4 SHF_RIGHT_MAN_UNIT(.i_shift_number
       (w_sub_exp_result[3:0]), .i_data ({w_swap_man0_min,
       8'b00000000}), .o_data (w_shf_right_man1_min));
  COMP_8bit_SIZE_DATA8 COMP_MAN_UNIT(.i_data_a (w_swap_man0_max),
       .i_data_b (w_shf_right_man1_min[15:8]), .o_less
       (w_comp_man_less));
  SWAP_unit_SIZE_DATA8 SWAP_MAN1_UNIT(.i_comp_less (w_comp_man_less),
       .i_data_a (w_swap_man0_max), .i_data_b
       (w_shf_right_man1_min[15:8]), .o_data_max (w_swap_man1_max),
       .o_data_min (w_swap_man1_min));
  MAN_ALU_SIZE_MAN8 MAN_ALU_UNIT(.i_sign_a (i_data_a[31]), .i_sign_b
       (i_data_b[31]), .i_carry (w_shf_right_man1_min[7]), .i_man_max
       (w_swap_man1_max), .i_man_min (w_swap_man1_min), .o_man_alu
       (w_alu_man_result), .o_overflow (w_alu_man_overflow));
  LOPD_8bit LOPD_UNIT(.i_data (w_alu_man_result), .o_pos_one
       (w_lopd_one_pos), .o_zero_flag (w_lopd_zero_flag));
  NOR_unit_SIZE_LOPD3_SIZE_DATA8 NOR_UNIT(.i_overflow
       (w_alu_man_overflow), .i_zero_flag (w_lopd_zero_flag),
       .i_one_position (w_lopd_one_pos), .i_mantissa
       (w_alu_man_result), .o_mantissa (w_nor_man));
  EXP_adjust_SIZE_EXP8_SIZE_LOPD8 EXP_ADJUSTION_UNIT(.i_overflow
       (w_alu_man_overflow), .i_underflow (w_alu_man_result[7]),
       .i_zero_flag (w_lopd_zero_flag), .i_lopd_value ({5'b00000,
       w_lopd_one_pos}), .i_exp_value (w_swap_exp_max), .o_exp_result
       (w_exp_adjust));
  SIGN_unit SIGN_UNIT(.i_comp_man (n_68), .i_sign_man_a (i_data_a[31]),
       .i_sign_man_b (i_data_b[31]), .o_sign_s (o_bfu_add[31]));
  PSC_unit PSC_UNIT(.i_sign_a (i_data_a[31]), .i_exp_a
       (i_data_a[30:23]), .i_man_a ({1'b1, i_data_a[22:0]}), .i_sign_b
       (i_data_b[31]), .i_exp_b (i_data_b[30:23]), .i_man_b ({1'b1,
       i_data_b[22:0]}), .o_sel_exp (w_sel_exp), .o_sel_man
       (w_sel_man));
  not_op_6 g1(.A (w_swap_exp_min), .Z ({n_67, n_66, n_65, n_64, n_63,
       n_62, n_61, n_60}));
  bmux_7 mux_165_39(.ctl (w_sel_man[0]), .in_0 (1'b0), .in_1 (1'b1), .z
       (n_59));
  bmux mux_165_23(.ctl (w_sel_man[1]), .in_0 (w_nor_man), .in_1 ({1'b1,
       n_59, 6'b000000}), .z ({w_man_result[7], o_bfu_add[22:16]}));
  bmux mux_164_23(.ctl (w_sel_exp), .in_0 (w_exp_adjust), .in_1
       (8'b11111111), .z (o_bfu_add[30:23]));
  or g2 (n_68, w_comp_exp_less, w_comp_man_less);
endmodule

`ifdef RC_CDN_GENERIC_GATE
`else
`ifdef ONE_HOT_MUX
module CDN_bmux2(sel0, data0, data1, z);
  input sel0, data0, data1;
  output z;
  wire sel0, data0, data1;
  reg  z;
  always 
    @(sel0 or data0 or data1) 
      case ({sel0})
       1'b0: z = data0;
       1'b1: z = data1;
      endcase
endmodule
`else
module CDN_bmux2(sel0, data0, data1, z);
  input sel0, data0, data1;
  output z;
  wire sel0, data0, data1;
  wire z;
  wire inv_sel0, w_0, w_1;
  not i_0 (inv_sel0, sel0);
  and a_0 (w_0, inv_sel0, data0);
  and a_1 (w_1, sel0, data1);
  or org (z, w_0, w_1);
endmodule
`endif // ONE_HOT_MUX
`endif
